/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — DB connectivity + worker status. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregated system rollups. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of system rollups by classification × currency. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemRollupsEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List journals (cursor-paginated, descending id). */
        get: {
            parameters: {
                query?: {
                    cursor?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Journals page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /** Post a balanced journal. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JournalInput"];
                };
            };
            responses: {
                /** @description Journal created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalEnvelope"];
                    };
                };
                409: components["responses"]["DomainError"];
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render a template into a journal and post it. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateExecutionRequest"];
                };
            };
            responses: {
                /** @description Journal created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalEnvelope"];
                    };
                };
                409: components["responses"]["DomainError"];
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/deposit-tolerance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve deposit shortfall / overage atomically. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plan executed. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one journal with all its entries. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Journal + entries. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalWithEntriesEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post the full reversal of an existing journal.
         * @description Rejected (409) once the journal has any reversal history, full or partial — use reverse-partial to continue a partially-reversed journal.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        reason: string;
                        idempotency_key: string;
                    };
                };
            };
            responses: {
                /** @description Reversal posted. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Already reversed. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journals/{id}/reverse-partial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reverse num/den of a journal (partial reversal).
         * @description Reverses num/den of every entry, per-currency balanced via largest-remainder allocation. Cumulative reversals never exceed the original (409 on overshoot). num == den ("1/1") reverses exactly the remaining un-reversed amount — the only way to complete a reversal whose earlier fractional steps rounded up.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        num: number;
                        /** Format: int64 */
                        den: number;
                        reason: string;
                        idempotency_key: string;
                    };
                };
            };
            responses: {
                /** @description Partial reversal posted. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
                /** @description Cumulative reversal would exceed the original. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entries on one account dimension (cursor-paginated). */
        get: {
            parameters: {
                query: {
                    holder: number;
                    currency: number;
                    cursor?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entries page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balances/{holder}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All balances for one holder across currencies. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    holder: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balances. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalancesEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balances/{holder}/{currency}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balances for one holder × currency. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    holder: number;
                    currency: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalancesEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balances/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch balance lookup. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        holders: number[];
                        /** Format: int64 */
                        currency_id: number;
                    };
                };
            };
            responses: {
                /** @description Map of holder → balances. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reservations. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reservations. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Reserve funds (TOCTOU-safe). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReserveInput"];
                };
            };
            responses: {
                /** @description Reservation created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReservationEnvelope"];
                    };
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Settle reservation with actual amount; remainder auto-released. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Decimal as string. */
                        actual_amount: string;
                    };
                };
            };
            responses: {
                /** @description Settled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/settle-partial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Settle part of a reservation; call repeatedly to accumulate.
         * @description First call transitions active → settling. Cumulative settled amount may never exceed the reserved amount. The unsettled remainder stays held against the balance until finalize. Finish with /reservations/{id}/finalize.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Decimal as string. */
                        amount: string;
                    };
                };
            };
            responses: {
                /** @description Partial settlement recorded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish a partially-settled reservation (settling → settled).
         * @description Releases the unsettled remainder. Rejected on a reservation with no partial settlements.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Finalized. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release a reservation without settling. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Released. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{holder}/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set (create or update) the freeze/close + balance-floor policy for an account dimension. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    holder: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountPolicyInput"];
                };
            };
            responses: {
                /** @description Policy set. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountPolicyEnvelope"];
                    };
                };
                422: components["responses"]["DomainError"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{holder}/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every policy row for an account holder (across currencies/classifications). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    holder: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Policies. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List bookings. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Bookings page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a booking against a classification's lifecycle. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateBookingInput"];
                };
            };
            responses: {
                /** @description Booking created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingEnvelope"];
                    };
                };
                422: components["responses"]["DomainError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one booking. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Advance a booking's lifecycle state. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TransitionInput"];
                };
            };
            responses: {
                /** @description Event for the transition. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one event. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{channel}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inbound channel callback (e.g. on-chain deposit).
         * @description Body shape and signing are channel-specific. Hot path is HMAC-verified.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    channel: "evm" | "btc" | "custom";
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted. */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description HMAC verification failed. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List classifications. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Classifications. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a classification (with optional lifecycle). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClassificationInput"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classifications/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a classification. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List journal types. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Journal types. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create a journal type. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journal-types/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entry templates. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Templates. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** Create an entry template. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateInput"];
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{code}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render a template without posting. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    code: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TemplateParams"];
                };
            };
            responses: {
                /** @description Rendered JournalInput. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/templates/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Currencies. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        code: string;
                        name: string;
                        /** @description Max decimal places entries in this currency may carry (JPY=0, USD=2, USDT=6, wei=18). Required — 0 is a legal value, so it cannot be defaulted. */
                        exponent: number;
                    };
                };
            };
            responses: {
                /** @description Created. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/currencies/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a currency. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deactivated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run global accounting-equation check. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reconciliation result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconcileResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconcile/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile a single account dimension. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        holder: number;
                        /** Format: int64 */
                        currency_id: number;
                    };
                };
            };
            responses: {
                /** @description Reconciliation result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reconcile/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the complete 10-check reconciliation suite on-demand.
         * @description Heavier, fleet-wide counterpart to `/reconcile` — also verifies
         *     checkpoint-vs-entries consistency (fleet-scanned, capped by a
         *     configurable scan limit/timeout and reported as partial if capped),
         *     orphan entries/reservations, the accounting equation, settlement
         *     netting, non-negative balances, idempotency-key uniqueness, and stale
         *     rollup queue items. Runs on the same schedule in the background
         *     worker; this endpoint triggers an out-of-band run.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full reconciliation report. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconcileReport"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List balance snapshots for an account dimension. */
        get: {
            parameters: {
                query: {
                    holder: number;
                    currency: number;
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshots. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/journals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List journals by account dimension or by global time range.
         * @description Exactly one mode is selected by the params provided: pass `holder` +
         *     `currency_id` (optionally narrowed by `classification_id` and/or
         *     `from`/`to`) to list journals touching that account dimension; pass
         *     `from`/`to` alone to scan a global time range instead. Providing
         *     neither, or `holder` without `currency_id`, is a 400.
         */
        get: {
            parameters: {
                query?: {
                    holder?: number;
                    currency_id?: number;
                    classification_id?: number;
                    from?: components["schemas"]["Timestamp"];
                    to?: components["schemas"]["Timestamp"];
                    cursor?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Journals page. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalListEnvelope"];
                    };
                };
                400: components["responses"]["DomainError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/bookings/{id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trace a booking end-to-end (booking + every event + every linked journal). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Booking trace. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BookingTraceEnvelope"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/journals/{id}/reversals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the reversal chain for a journal (root journal + every journal that transitively reverses it). */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reversal chain, oldest first. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalListEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Real-time per-classification balance breakdown for a currency.
         * @description Computed as `checkpoint.balance + delta`, so it reflects every
         *     committed journal immediately without waiting for the rollup worker.
         */
        get: {
            parameters: {
                query: {
                    currency_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Platform balance breakdown. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlatformBalanceEnvelope"];
                    };
                };
                400: components["responses"]["DomainError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/platform/solvency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare total user-side liability against custodial system balance for a currency. */
        get: {
            parameters: {
                query: {
                    currency_id: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Solvency report. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SolvencyEnvelope"];
                    };
                };
                400: components["responses"]["DomainError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/balances/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Historical daily balance series for an account dimension.
         * @description One point per calendar day in `[from, to]`. Days without journal
         *     activity are forward-filled from the previous known balance;
         *     today's point is always the live checkpoint+delta value.
         */
        get: {
            parameters: {
                query: {
                    holder: number;
                    currency_id: number;
                    classification_id?: number;
                    from: components["schemas"]["Timestamp"];
                    to: components["schemas"]["Timestamp"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance trend points, ascending by date. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BalanceTrendListEnvelope"];
                    };
                };
                400: components["responses"]["DomainError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Arbitrary-precision decimal as a string (e.g. 123.456789). NUMERIC(30,18) on the wire.
         * @example 100.00
         */
        Decimal: string;
        /**
         * Format: date-time
         * @example 2026-04-29T10:00:00Z
         */
        Timestamp: string;
        Envelope: {
            /** @example 0 */
            code: number;
            /** @example ok */
            message: string;
        };
        ErrorResponse: components["schemas"]["Envelope"] & {
            /** @example 14001 */
            code?: number;
            /** @example Insufficient balance for this operation */
            message?: string;
            /**
             * @description Whether the client may safely retry using the SAME
             *     idempotency_key. See docs/api.md "Error handling contract".
             * @example false
             */
            retryable?: boolean;
        };
        /** @enum {string} */
        EntryType: "debit" | "credit";
        /** @enum {string} */
        NormalSide: "debit" | "credit";
        /** @enum {string} */
        HolderRole: "user" | "system";
        EntryInput: {
            /** Format: int64 */
            account_holder: number;
            /** Format: int64 */
            currency_id: number;
            /** Format: int64 */
            classification_id: number;
            entry_type: components["schemas"]["EntryType"];
            amount: components["schemas"]["Decimal"];
        };
        JournalInput: {
            /** Format: int64 */
            journal_type_id: number;
            idempotency_key: string;
            /** Format: int64 */
            event_id?: number;
            entries: components["schemas"]["EntryInput"][];
            metadata?: {
                [key: string]: string;
            };
            /** Format: int64 */
            actor_id?: number;
            source?: string;
        };
        Journal: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            journal_type_id?: number;
            idempotency_key?: string;
            total_debit?: components["schemas"]["Decimal"];
            total_credit?: components["schemas"]["Decimal"];
            metadata?: {
                [key: string]: string;
            };
            /** Format: int64 */
            actor_id?: number;
            source?: string;
            /** Format: int64 */
            reversal_of?: number | null;
            /** Format: int64 */
            event_id?: number | null;
            created_at?: components["schemas"]["Timestamp"];
        };
        Entry: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            journal_id?: number;
            /** Format: int64 */
            account_holder?: number;
            /** Format: int64 */
            currency_id?: number;
            /** Format: int64 */
            classification_id?: number;
            entry_type?: components["schemas"]["EntryType"];
            amount?: components["schemas"]["Decimal"];
            created_at?: components["schemas"]["Timestamp"];
        };
        JournalEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Journal"];
        };
        JournalListEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Journal"][];
        };
        JournalWithEntriesEnvelope: components["schemas"]["Envelope"] & {
            data?: {
                journal?: components["schemas"]["Journal"];
                entries?: components["schemas"]["Entry"][];
            };
        };
        Balance: {
            /** Format: int64 */
            account_holder?: number;
            /** Format: int64 */
            currency_id?: number;
            /** Format: int64 */
            classification_id?: number;
            balance?: components["schemas"]["Decimal"];
        };
        BalancesEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Balance"][];
        };
        SystemRollup: {
            /** Format: int64 */
            currency_id?: number;
            /** Format: int64 */
            classification_id?: number;
            total_balance?: components["schemas"]["Decimal"];
            updated_at?: components["schemas"]["Timestamp"];
        };
        SystemRollupsEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["SystemRollup"][];
        };
        ReserveInput: {
            /** Format: int64 */
            account_holder: number;
            /** Format: int64 */
            currency_id: number;
            amount: components["schemas"]["Decimal"];
            idempotency_key: string;
            /** @description Go duration string (e.g. 1h, 30m). */
            expires_in?: string;
        };
        Reservation: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            account_holder?: number;
            /** Format: int64 */
            currency_id?: number;
            reserved_amount?: components["schemas"]["Decimal"];
            settled_amount?: components["schemas"]["Decimal"];
            /** @enum {string} */
            status?: "active" | "settling" | "settled" | "released";
            /** Format: int64 */
            journal_id?: number | null;
            idempotency_key?: string;
            expires_at?: components["schemas"]["Timestamp"];
            created_at?: components["schemas"]["Timestamp"];
            updated_at?: components["schemas"]["Timestamp"];
        };
        ReservationEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Reservation"];
        };
        AccountPolicyInput: {
            /**
             * Format: int64
             * @description 0 = all currencies for this holder.
             */
            currency_id?: number;
            /**
             * Format: int64
             * @description 0 = all classifications for this holder/currency.
             */
            classification_id?: number;
            /** @enum {string} */
            status: "active" | "frozen" | "closed";
            /** @description 0 = no overdraft; negative = overdraft limit; positive = dust floor. */
            min_balance?: components["schemas"]["Decimal"];
            enforce_min_balance?: boolean;
            note?: string;
            /** Format: int64 */
            actor_id?: number;
        };
        AccountPolicy: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            account_holder?: number;
            /** Format: int64 */
            currency_id?: number;
            /** Format: int64 */
            classification_id?: number;
            /** @enum {string} */
            status?: "active" | "frozen" | "closed";
            min_balance?: components["schemas"]["Decimal"];
            enforce_min_balance?: boolean;
            note?: string;
            updated_at?: components["schemas"]["Timestamp"];
            created_at?: components["schemas"]["Timestamp"];
        };
        AccountPolicyEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["AccountPolicy"];
        };
        CreateBookingInput: {
            classification_code: string;
            /** Format: int64 */
            account_holder: number;
            /** Format: int64 */
            currency_id: number;
            amount: components["schemas"]["Decimal"];
            idempotency_key: string;
            channel_name?: string;
            metadata?: {
                [key: string]: unknown;
            };
            expires_at?: components["schemas"]["Timestamp"];
        };
        TransitionInput: {
            to_status: string;
            channel_ref?: string;
            amount?: components["schemas"]["Decimal"];
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            actor_id?: number;
            source?: string;
        };
        Booking: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            classification_id?: number;
            /** Format: int64 */
            account_holder?: number;
            /** Format: int64 */
            currency_id?: number;
            amount?: components["schemas"]["Decimal"];
            settled_amount?: components["schemas"]["Decimal"];
            status?: string;
            channel_name?: string;
            channel_ref?: string;
            /** Format: int64 */
            reservation_id?: number | null;
            /** Format: int64 */
            journal_id?: number | null;
            idempotency_key?: string;
            metadata?: {
                [key: string]: unknown;
            };
            expires_at?: components["schemas"]["Timestamp"];
            created_at?: components["schemas"]["Timestamp"];
            updated_at?: components["schemas"]["Timestamp"];
        };
        BookingEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Booking"];
        };
        Event: {
            /** Format: int64 */
            id?: number;
            classification_code?: string;
            /** Format: int64 */
            booking_id?: number;
            /** Format: int64 */
            account_holder?: number;
            /** Format: int64 */
            currency_id?: number;
            from_status?: string;
            to_status?: string;
            amount?: components["schemas"]["Decimal"];
            settled_amount?: components["schemas"]["Decimal"];
            /** Format: int64 */
            journal_id?: number | null;
            metadata?: {
                [key: string]: unknown;
            };
            occurred_at?: components["schemas"]["Timestamp"];
            /** Format: int64 */
            actor_id?: number;
            source?: string;
        };
        EventEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["Event"];
        };
        Lifecycle: {
            initial: string;
            terminal?: string[];
            transitions: {
                [key: string]: string[];
            };
        };
        ClassificationInput: {
            code: string;
            name: string;
            normal_side: components["schemas"]["NormalSide"];
            is_system?: boolean;
            lifecycle?: components["schemas"]["Lifecycle"];
        };
        TemplateLineInput: {
            /** Format: int64 */
            classification_id: number;
            entry_type: components["schemas"]["EntryType"];
            holder_role: components["schemas"]["HolderRole"];
            amount_key: string;
            sort_order?: number;
        };
        TemplateInput: {
            code: string;
            name: string;
            /** Format: int64 */
            journal_type_id: number;
            lines: components["schemas"]["TemplateLineInput"][];
        };
        TemplateParams: {
            /** Format: int64 */
            holder_id: number;
            /** Format: int64 */
            currency_id: number;
            idempotency_key: string;
            /** Format: int64 */
            event_id?: number;
            amounts: {
                [key: string]: components["schemas"]["Decimal"];
            };
            /** Format: int64 */
            actor_id?: number;
            source?: string;
            metadata?: {
                [key: string]: string;
            };
        };
        TemplateExecutionRequest: {
            template_code: string;
            /** Format: int64 */
            holder_id: number;
            /** Format: int64 */
            currency_id: number;
            idempotency_key: string;
            /** Format: int64 */
            event_id?: number;
            amounts: {
                [key: string]: components["schemas"]["Decimal"];
            };
            /** Format: int64 */
            actor_id?: number;
            source?: string;
            metadata?: {
                [key: string]: string;
            };
        };
        ReconcileResult: {
            balanced?: boolean;
            gap?: components["schemas"]["Decimal"];
            details?: {
                /** Format: int64 */
                account_holder?: number;
                /** Format: int64 */
                currency_id?: number;
                /** Format: int64 */
                classification_id?: number;
                expected?: components["schemas"]["Decimal"];
                actual?: components["schemas"]["Decimal"];
                drift?: components["schemas"]["Decimal"];
            }[];
            checked_at?: components["schemas"]["Timestamp"];
        };
        BookingTrace: {
            booking?: components["schemas"]["Booking"];
            events?: components["schemas"]["Event"][];
            journals?: components["schemas"]["Journal"][];
        };
        BookingTraceEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["BookingTrace"];
        };
        PlatformBalance: {
            /** Format: int64 */
            currency_id?: number;
            /** @description classification code → total (holder > 0). */
            user_side?: {
                [key: string]: components["schemas"]["Decimal"];
            };
            /** @description classification code → total (holder < 0). */
            system_side?: {
                [key: string]: components["schemas"]["Decimal"];
            };
        };
        PlatformBalanceEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["PlatformBalance"];
        };
        SolvencyReport: {
            /** Format: int64 */
            currency_id?: number;
            liability?: components["schemas"]["Decimal"];
            custodial?: components["schemas"]["Decimal"];
            solvent?: boolean;
            /** @description custodial - liability; negative = under-collateralised. */
            margin?: components["schemas"]["Decimal"];
        };
        SolvencyEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["SolvencyReport"];
        };
        BalanceTrendPoint: {
            /** Format: date */
            date?: string;
            balance?: components["schemas"]["Decimal"];
            inflow?: components["schemas"]["Decimal"];
            outflow?: components["schemas"]["Decimal"];
        };
        BalanceTrendListEnvelope: components["schemas"]["Envelope"] & {
            data?: components["schemas"]["BalanceTrendPoint"][];
        };
        ReconcileReport: {
            overall_passed?: boolean;
            run_at?: components["schemas"]["Timestamp"];
            checks?: {
                /** @description e.g. orphan_entries, checkpoint_balance, accounting_equation */
                name?: string;
                passed?: boolean;
                checked_at?: components["schemas"]["Timestamp"];
                findings?: {
                    description?: string;
                    detail?: string;
                }[];
            }[];
        };
    };
    responses: {
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ledger / domain invariant violation. */
        DomainError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
