// Domain types for the ledger HTTP API — the front-end consumption view:
// required fields, ergonomic shapes, framework-agnostic (no React, no env reads).
//
// `./schema.ts` is the machine-generated mirror of docs/openapi.yaml (the backend
// contract), regenerated by `npm run codegen` and pinned by the `codegen:check`
// CI gate so it can never drift from the spec. These hand-written types are the
// stable surface the hooks/components consume; keep them aligned with schema.ts
// when the backend contract changes.

export interface ApiError {
  code: number;
  message: string;
}

export interface Journal {
  uid: string;
  journal_type_uid: string;
  idempotency_key: string;
  total_debit: string;
  total_credit: string;
  metadata: Record<string, unknown>;
  actor_id: number;
  source: string;
  reversal_of_uid: string;  // "" = not linked
  created_at: string;
}

export interface Entry {
  journal_uid: string;
  account_holder: number;
  currency_uid: string;
  classification_uid: string;
  entry_type: "debit" | "credit";
  amount: string;
  created_at: string;
}

export interface JournalWithEntries {
  journal: Journal;
  entries: Entry[];
}

export interface Balance {
  account_holder: number;
  currency_uid: string;
  classification_uid: string;
  balance: string;
}

export interface Reservation {
  uid: string;
  account_holder: number;
  currency_uid: string;
  reserved_amount: string;
  settled_amount: string;
  status: "active" | "settling" | "settled" | "released";
  journal_uid: string;  // "" = not linked
  idempotency_key: string;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface Lifecycle {
  initial: string;
  terminal: string[];
  transitions: Record<string, string[]>;
}

// Booking is the unified record replacing v1 Deposit/Withdrawal.
// Its lifecycle is governed by the classification.
export interface Booking {
  uid: string;
  classification_uid: string;
  account_holder: number;
  currency_uid: string;
  amount: string;
  settled_amount: string;
  status: string;
  channel_name: string;
  channel_ref: string;
  // reservation_uid / journal_uid are empty strings until linked.
  reservation_uid: string;  // "" = not linked
  journal_uid: string;  // "" = not linked
  idempotency_key: string;
  metadata: Record<string, unknown>;
  expires_at: string;
  created_at: string;
  updated_at: string;
}

export interface Event {
  uid: string;
  classification_code: string;
  booking_uid: string;
  account_holder: number;
  currency_uid: string;
  from_status: string;
  to_status: string;
  amount: string;
  settled_amount: string;
  journal_uid: string;  // "" = not linked
  metadata: Record<string, unknown>;
  occurred_at: string;
}

export interface Classification {
  uid: string;
  code: string;
  name: string;
  normal_side: "debit" | "credit";
  is_system: boolean;
  is_active: boolean;
  lifecycle: Lifecycle | null;
  created_at: string;
}

export interface JournalType {
  uid: string;
  code: string;
  name: string;
  is_active: boolean;
  created_at: string;
}

export interface TemplateLine {
  classification_uid: string;
  entry_type: "debit" | "credit";
  holder_role: "user" | "system";
  amount_key: string;
  sort_order: number;
}

export interface EntryTemplate {
  uid: string;
  code: string;
  name: string;
  journal_type_uid: string;
  is_active: boolean;
  lines: TemplateLine[];
  created_at: string;
}

export interface Currency {
  uid: string;
  code: string;
  name: string;
  is_active: boolean;
  /** Max decimal places entries in this currency may carry (JPY=0, USD=2, wei=18). */
  exponent: number;
}

export interface HealthStatus {
  status: string;
  rollup_queue_depth: number;
  checkpoint_max_age_seconds: number;
  active_reservations: number;
}

export interface SystemBalance {
  currency_uid: string;
  classification_uid: string;
  total_balance: string;
  updated_at: string;
}

export interface ReconcileResult {
  balanced: boolean;
  gap: string;
  details: Array<{
    account_holder: number;
    currency_uid: string;
    classification_uid: string;
    expected: string;
    actual: string;
    drift: string;
  }>;
  checked_at: string;
}

export interface Snapshot {
  account_holder: number;
  currency_uid: string;
  classification_uid: string;
  snapshot_date: string;
  balance: string;
}

export interface PaginatedResponse<T> {
  list: T[];
  /** Opaque cursor; absent/empty when exhausted or when the endpoint is not paginated. */
  next_cursor?: string;
}

// Holder-facing liquidity view (see docs/INVARIANTS.md I-11):
//   total = available + locked + pending; Reserve enforces against the same
//   available figure this reports.
export interface BalanceBreakdown {
  account_holder: number;
  currency_uid: string;
  available: string;
  pending: string;
  locked: string;
  total: string;
}

export interface BalanceByCurrency {
  total: string;
  classifications: Balance[];
}

export interface HolderBalances {
  holder_id: number;
  balances: Balance[];
}

export interface PreviewResult {
  entries: Array<{
    account_holder: number;
    currency_uid: string;
    classification_uid: string;
    entry_type: "debit" | "credit";
    amount: string;
  }>;
  total_debit: string;
  total_credit: string;
}

export interface CreateBookingBody {
  classification_code: string;
  account_holder: number;
  currency_uid: string;
  amount: string;
  idempotency_key: string;
  channel_name: string;
  metadata?: Record<string, unknown>;
  expires_at?: string;
}

export interface TransitionBookingBody {
  to_status: string;
  channel_ref?: string;
  amount?: string;
  metadata?: Record<string, unknown>;
  actor_id?: number;
}

export interface ListBookingsParams {
  holder?: number;
  classification_uid?: string;
  status?: string;
  cursor?: string;
  limit?: number;
}
