// Package core — audit and trend types + interfaces.
// These are consumer-side interfaces (hexagonal: defined where they are used,
// not where they are implemented). No net/http, pgx, slog, or chi imports.
package core

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

// BalanceTrendPoint is one day's snapshot in a historical balance series.
// Inflow and Outflow represent the net credit/debit posted for that day.
type BalanceTrendPoint struct {
	Date    time.Time       `json:"date"`
	Balance decimal.Decimal `json:"balance"`
	Inflow  decimal.Decimal `json:"inflow"`
	Outflow decimal.Decimal `json:"outflow"`
}

// BalanceTrendFilter specifies the account and date window to query.
// ClassificationID 0 means "all classifications" (sum across them).
type BalanceTrendFilter struct {
	AccountHolder    int64
	CurrencyID       int64
	ClassificationID int64 // 0 = all
	From             time.Time
	Until            time.Time
}

// BalanceTrendReader queries historical balance time-series.
type BalanceTrendReader interface {
	// GetBalanceTrends returns one BalanceTrendPoint per calendar day in [From, Until].
	// Days with no journal activity are forward-filled from the previous known balance.
	// Today's balance is always overridden with the live checkpoint+delta value.
	GetBalanceTrends(ctx context.Context, filter BalanceTrendFilter) ([]BalanceTrendPoint, error)
}

// JournalAuditRow is a lightweight journal record used for audit list APIs.
// It includes the classification + currency dimension so callers can filter
// without extra lookups.
type JournalAuditRow struct {
	Journal          Journal   `json:"journal"`
	AccountHolder    int64     `json:"account_holder"`
	CurrencyID       int64     `json:"currency_id"`
	ClassificationID int64     `json:"classification_id"`
}

// BookingTrace bundles a booking with all its events and linked journals.
// Useful for audit / customer support investigation.
type BookingTrace struct {
	Booking  Booking   `json:"booking"`
	Events   []Event   `json:"events"`
	Journals []Journal `json:"journals"`
}

// AuditFilter is the input for list-style audit queries.
// Zero values for optional fields are treated as "no filter".
type AuditFilter struct {
	AccountHolder    int64
	CurrencyID       int64
	ClassificationID int64
	Since            time.Time // inclusive lower bound on journal created_at
	Until            time.Time // inclusive upper bound on journal created_at
	Cursor           int64     // keyset cursor (journal id); 0 = start from beginning
	Limit            int32     // max rows; callers should cap at a reasonable value
}

// AuditQuerier provides read-only list/trace queries for audit workflows.
// All methods return results in ascending ID order (oldest first) unless noted.
type AuditQuerier interface {
	// ListJournalsByAccount returns journals whose entries touch the given
	// (holder, currencyID, classificationID) dimension. classificationID=0 matches all.
	ListJournalsByAccount(ctx context.Context, filter AuditFilter) ([]Journal, error)

	// ListEntriesByJournal returns all entries belonging to a single journal.
	ListEntriesByJournal(ctx context.Context, journalID int64) ([]Entry, error)

	// ListJournalsByTimeRange returns journals created within [Since, Until].
	ListJournalsByTimeRange(ctx context.Context, filter AuditFilter) ([]Journal, error)

	// TraceBooking returns the booking together with every event and every
	// journal that was generated by those events.
	TraceBooking(ctx context.Context, bookingID int64) (*BookingTrace, error)

	// ListReversals returns the reversal chain for a journal (the original
	// journal plus any journals that reverse it, transitively).
	ListReversals(ctx context.Context, journalID int64) ([]Journal, error)
}
