// Package core — audit and trend types + interfaces.
// These are consumer-side interfaces (hexagonal: defined where they are used,
// not where they are implemented). No net/http, pgx, slog, or chi imports.
package core

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

// BalanceTrendPoint is one day's snapshot in a historical balance series.
// Inflow and Outflow represent the net credit/debit posted for that day.
type BalanceTrendPoint struct {
	Date    time.Time       `json:"date"`
	Balance decimal.Decimal `json:"balance"`
	Inflow  decimal.Decimal `json:"inflow"`
	Outflow decimal.Decimal `json:"outflow"`
}

// BalanceTrendFilter specifies the account and date window to query.
// ClassificationUID "" means "all classifications" (sum across them).
type BalanceTrendFilter struct {
	AccountHolder     int64
	CurrencyUID       string
	ClassificationUID string // "" = all
	From              time.Time
	Until             time.Time
}

// BalanceTrendReader queries historical balance time-series.
type BalanceTrendReader interface {
	// GetBalanceTrends returns one BalanceTrendPoint per calendar day in [From, Until].
	// Days with no journal activity are forward-filled from the previous known balance.
	// Today's balance is always overridden with the live checkpoint+delta value.
	GetBalanceTrends(ctx context.Context, filter BalanceTrendFilter) ([]BalanceTrendPoint, error)
}

// JournalAuditRow is a lightweight journal record used for audit list APIs.
// It includes the classification + currency dimension so callers can filter
// without extra lookups.
type JournalAuditRow struct {
	Journal           Journal `json:"journal"`
	AccountHolder     int64   `json:"account_holder"`
	CurrencyUID       string  `json:"currency_uid"`
	ClassificationUID string  `json:"classification_uid"`
}

// BookingTrace bundles a booking with all its events and linked journals.
// Useful for audit / customer support investigation.
type BookingTrace struct {
	Booking  Booking   `json:"booking"`
	Events   []Event   `json:"events"`
	Journals []Journal `json:"journals"`
}

// AuditFilter is the input for list-style audit queries.
// Zero values for optional fields are treated as "no filter".
type AuditFilter struct {
	AccountHolder     int64
	CurrencyUID       string
	ClassificationUID string
	Since             time.Time // inclusive lower bound on journal created_at
	Until             time.Time // inclusive upper bound on journal created_at
	// Cursor is the opaque keyset cursor from the previous page ("" = start).
	// It encodes internal ordering only; it is not an entity identifier.
	Cursor string
	Limit  int32 // max rows; callers should cap at a reasonable value
}

// AuditQuerier provides read-only list/trace queries for audit workflows.
// All methods return results in ascending ID order (oldest first) unless noted.
type AuditQuerier interface {
	// ListJournalsByAccount returns journals whose entries touch the given
	// (holder, currency, classification) dimension. ClassificationUID "" matches
	// all. The second return value is the opaque cursor for the next page
	// ("" when exhausted).
	ListJournalsByAccount(ctx context.Context, filter AuditFilter) ([]Journal, string, error)

	// ListEntriesByJournal returns all entries belonging to a single journal.
	ListEntriesByJournal(ctx context.Context, journalUID string) ([]Entry, error)

	// ListJournalsByTimeRange returns journals created within [Since, Until].
	// The second return value is the opaque cursor for the next page ("" when
	// exhausted).
	ListJournalsByTimeRange(ctx context.Context, filter AuditFilter) ([]Journal, string, error)

	// TraceBooking returns the booking together with every event and every
	// journal that was generated by those events.
	TraceBooking(ctx context.Context, bookingUID string) (*BookingTrace, error)

	// ListReversals returns the reversal chain for a journal (the original
	// journal plus any journals that reverse it, transitively).
	ListReversals(ctx context.Context, journalUID string) ([]Journal, error)
}
