package core

import (
	"encoding/hex"
	"testing"
	"time"

	"github.com/shopspring/decimal"
)

// ---------------------------------------------------------------------------
// Algorithm-level golden vectors (arbitrary byte payloads, independent of
// core/attestation.go's AttestedEntry encoding).
//
// IMPORTANT PROVENANCE NOTE: this environment has no internet access this
// session, so these values were NOT cross-checked against externally
// published RFC 6962 / Certificate Transparency reference test vectors --
// only against an independently written Python transcription of the same
// RFC 6962 MTH/PATH algorithm (not generated by calling this package). The
// n=0 case (SHA-256 of the empty string) IS independently, unambiguously
// verifiable (it is a universally known constant); n=1..8 are pinned
// against the Python cross-check only. See core/merkle.go's package doc
// comment for the same disclosure.
// ---------------------------------------------------------------------------

func testPayloads(n int) [][]byte {
	out := make([][]byte, n)
	for i := 0; i < n; i++ {
		out[i] = []byte{byte(i)}
	}
	return out
}

func TestMerkleRoot_GoldenVectors(t *testing.T) {
	cases := []struct {
		n    int
		want string
	}{
		{0, "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"},
		{1, "96a296d224f285c67bee93c30f8a309157f0daa35dc5b87e410b78630a09cfc7"},
		{2, "a20bf9a7cc2dc8a08f5f415a71b19f6ac427bab54d24eec868b5d3103449953a"},
		{3, "3b6cccd7e3e023ff393006f030315ee7ad9eb111b022b41fba7e5b7a3973f688"},
		{4, "9bcd51240af4005168f033121ba85be5a6ed4f0e6a5fac262066729b8fbfdecb"},
		{5, "b855b42d6c30f5b087e05266783fbd6e394f7b926013ccaa67700a8b0c5a596f"},
		{6, "bb36e7d3d4cee5720cbd323d02fab15962e2ba1dadf5f8fc6eeef4fd6ad056a8"},
		{7, "3560191803028444b232018ac047fdb561c09c23a7a6876c85e08b5e4d48e9f3"},
		{8, "ef7f49b620f6c7ea9b963a214da34b5021c6ded8ed57734380a311ab726aa907"},
	}
	for _, tc := range cases {
		t.Run(fmt_n(tc.n), func(t *testing.T) {
			tree := buildMerkleTreeFromPayloads(testPayloads(tc.n))
			got := hex.EncodeToString(tree.Root())
			if got != tc.want {
				t.Errorf("Root() for n=%d = %s, want %s", tc.n, got, tc.want)
			}
			if tree.LeafCount() != tc.n {
				t.Errorf("LeafCount() = %d, want %d", tree.LeafCount(), tc.n)
			}
		})
	}
}

func fmt_n(n int) string {
	return "n=" + string(rune('0'+n))
}

func TestMerkleTree_EmptyRootMatchesConstant(t *testing.T) {
	tree := buildMerkleTreeFromPayloads(nil)
	if hex.EncodeToString(tree.Root()) != hex.EncodeToString(EmptyMerkleRoot) {
		t.Errorf("empty tree root = %x, want EmptyMerkleRoot %x", tree.Root(), EmptyMerkleRoot)
	}
}

// TestMerkleTree_NoDuplicationOfOddLeaf pins the CVE-2012-2459 defense:
// a 3-leaf tree's root must NOT equal what you would get by naively
// duplicating the last leaf to pad to 4 (a common naive Merkle tree bug).
func TestMerkleTree_NoDuplicationOfOddLeaf(t *testing.T) {
	payloads := testPayloads(3)
	tree := buildMerkleTreeFromPayloads(payloads)

	// The naive (WRONG) construction: pair (leaf0,leaf1) and (leaf2,leaf2).
	l0 := merkleLeafHash(payloads[0])
	l1 := merkleLeafHash(payloads[1])
	l2 := merkleLeafHash(payloads[2])
	naiveRoot := merkleNodeHash(merkleNodeHash(l0, l1), merkleNodeHash(l2, l2))

	if hex.EncodeToString(tree.Root()) == hex.EncodeToString(naiveRoot) {
		t.Error("3-leaf tree root matches the naive odd-leaf-duplication construction -- CVE-2012-2459 defense is broken")
	}
	// Cross-checked against the Python reference's identical assertion.
	const wantRoot = "3b6cccd7e3e023ff393006f030315ee7ad9eb111b022b41fba7e5b7a3973f688"
	const wantNaive = "100f9f6b8976fb123218e5e0493c19b856301b9a938716b14040c47f1c98c56e"
	if hex.EncodeToString(tree.Root()) != wantRoot {
		t.Errorf("root = %x, want %s", tree.Root(), wantRoot)
	}
	if hex.EncodeToString(naiveRoot) != wantNaive {
		t.Errorf("naiveRoot = %x, want %s", naiveRoot, wantNaive)
	}
}

// TestMerkleTree_InclusionProofRoundTrip_AllSizesAndIndices exercises
// GenerateInclusionProof + VerifyInclusion for every (n, index) pair for
// n=1..32, cross-checked structurally against the Python reference
// (same recursive algorithm, independently written).
func TestMerkleTree_InclusionProofRoundTrip_AllSizesAndIndices(t *testing.T) {
	for n := 1; n <= 32; n++ {
		payloads := testPayloads(n)
		tree := buildMerkleTreeFromPayloads(payloads)
		root := tree.Root()
		for m := 0; m < n; m++ {
			proof, err := tree.GenerateInclusionProof(m)
			if err != nil {
				t.Fatalf("n=%d m=%d: GenerateInclusionProof: %v", n, m, err)
			}
			leafHash, err := tree.LeafHash(m)
			if err != nil {
				t.Fatalf("n=%d m=%d: LeafHash: %v", n, m, err)
			}
			if !VerifyInclusion(leafHash, *proof, root) {
				t.Errorf("n=%d m=%d: VerifyInclusion returned false for a genuine proof", n, m)
			}
		}
	}
}

func TestMerkleTree_InclusionProof_GoldenVector(t *testing.T) {
	// n=5, m=4 (the lone right-hand leaf at the deepest level of an
	// unbalanced tree) -- independently computed in Python.
	payloads := testPayloads(5)
	tree := buildMerkleTreeFromPayloads(payloads)
	proof, err := tree.GenerateInclusionProof(4)
	if err != nil {
		t.Fatalf("GenerateInclusionProof: %v", err)
	}
	if proof.TreeSize != 5 || proof.LeafIndex != 4 {
		t.Fatalf("proof = %+v, want TreeSize=5 LeafIndex=4", proof)
	}
	if len(proof.Path) != 1 {
		t.Fatalf("len(proof.Path) = %d, want 1 (leaf 4 of 5 pairs directly with MTH(leaves[0:4]))", len(proof.Path))
	}
	// The single sibling must be MTH(leaves[0:4]) -- the n=4 golden root.
	const wantSibling = "9bcd51240af4005168f033121ba85be5a6ed4f0e6a5fac262066729b8fbfdecb"
	if hex.EncodeToString(proof.Path[0]) != wantSibling {
		t.Errorf("proof.Path[0] = %x, want %s", proof.Path[0], wantSibling)
	}
}

func TestVerifyInclusion_RejectsTamperedLeaf(t *testing.T) {
	payloads := testPayloads(7)
	tree := buildMerkleTreeFromPayloads(payloads)
	root := tree.Root()
	proof, err := tree.GenerateInclusionProof(3)
	if err != nil {
		t.Fatalf("GenerateInclusionProof: %v", err)
	}
	wrongLeaf := merkleLeafHash([]byte{99})
	if VerifyInclusion(wrongLeaf, *proof, root) {
		t.Error("VerifyInclusion accepted a leaf hash that does not match the proof")
	}
}

func TestVerifyInclusion_RejectsTamperedPath(t *testing.T) {
	payloads := testPayloads(7)
	tree := buildMerkleTreeFromPayloads(payloads)
	root := tree.Root()
	proof, err := tree.GenerateInclusionProof(3)
	if err != nil {
		t.Fatalf("GenerateInclusionProof: %v", err)
	}
	leafHash, err := tree.LeafHash(3)
	if err != nil {
		t.Fatalf("LeafHash: %v", err)
	}
	tampered := *proof
	tampered.Path = append([][]byte{}, proof.Path...)
	tampered.Path[0] = merkleLeafHash([]byte{123})
	if VerifyInclusion(leafHash, tampered, root) {
		t.Error("VerifyInclusion accepted a tampered audit path")
	}
}

func TestVerifyInclusion_RejectsOutOfRangeIndex(t *testing.T) {
	proof := InclusionProof{LeafIndex: 5, TreeSize: 5, Path: nil}
	if VerifyInclusion([]byte("leaf"), proof, []byte("root")) {
		t.Error("VerifyInclusion accepted LeafIndex == TreeSize")
	}
}

func TestGenerateInclusionProof_RejectsOutOfRangeIndex(t *testing.T) {
	tree := buildMerkleTreeFromPayloads(testPayloads(3))
	if _, err := tree.GenerateInclusionProof(3); err == nil {
		t.Error("expected error for out-of-range index, got nil")
	}
	if _, err := tree.GenerateInclusionProof(-1); err == nil {
		t.Error("expected error for negative index, got nil")
	}
}

func TestGenerateInclusionProof_EmptyTree(t *testing.T) {
	tree := buildMerkleTreeFromPayloads(nil)
	if _, err := tree.GenerateInclusionProof(0); err == nil {
		t.Error("expected error generating a proof against an empty tree, got nil")
	}
}

// ---------------------------------------------------------------------------
// LocateMismatches
// ---------------------------------------------------------------------------

func TestLocateMismatches_FindsSingleTamperedLeaf(t *testing.T) {
	reference := buildMerkleTreeFromPayloads(testPayloads(8))
	tamperedPayloads := testPayloads(8)
	tamperedPayloads[5] = []byte{200} // tamper leaf index 5
	actual := buildMerkleTreeFromPayloads(tamperedPayloads)

	got, err := LocateMismatches(reference, actual)
	if err != nil {
		t.Fatalf("LocateMismatches: %v", err)
	}
	if len(got) != 1 || got[0] != 5 {
		t.Errorf("LocateMismatches = %v, want [5]", got)
	}
}

func TestLocateMismatches_FindsMultipleTamperedLeaves(t *testing.T) {
	reference := buildMerkleTreeFromPayloads(testPayloads(11))
	tamperedPayloads := testPayloads(11)
	tamperedPayloads[0] = []byte{200}
	tamperedPayloads[10] = []byte{201}
	actual := buildMerkleTreeFromPayloads(tamperedPayloads)

	got, err := LocateMismatches(reference, actual)
	if err != nil {
		t.Fatalf("LocateMismatches: %v", err)
	}
	if len(got) != 2 || got[0] != 0 || got[1] != 10 {
		t.Errorf("LocateMismatches = %v, want [0 10]", got)
	}
}

func TestLocateMismatches_NoMismatchesReturnsEmpty(t *testing.T) {
	reference := buildMerkleTreeFromPayloads(testPayloads(6))
	actual := buildMerkleTreeFromPayloads(testPayloads(6))
	got, err := LocateMismatches(reference, actual)
	if err != nil {
		t.Fatalf("LocateMismatches: %v", err)
	}
	if len(got) != 0 {
		t.Errorf("LocateMismatches = %v, want empty", got)
	}
}

func TestLocateMismatches_RejectsDifferentSizes(t *testing.T) {
	reference := buildMerkleTreeFromPayloads(testPayloads(5))
	actual := buildMerkleTreeFromPayloads(testPayloads(6))
	if _, err := LocateMismatches(reference, actual); err == nil {
		t.Error("expected error for mismatched tree sizes, got nil")
	}
}

func TestLocateMismatches_BothEmpty(t *testing.T) {
	reference := buildMerkleTreeFromPayloads(nil)
	actual := buildMerkleTreeFromPayloads(nil)
	got, err := LocateMismatches(reference, actual)
	if err != nil {
		t.Fatalf("LocateMismatches: %v", err)
	}
	if len(got) != 0 {
		t.Errorf("LocateMismatches = %v, want empty", got)
	}
}

// ---------------------------------------------------------------------------
// BuildMerkleTree (AttestedEntry-based, shared encoding with
// CanonicalBatchDigest).
// ---------------------------------------------------------------------------

func TestBuildMerkleTree_EmptyBatch(t *testing.T) {
	tree, err := BuildMerkleTree(nil)
	if err != nil {
		t.Fatalf("BuildMerkleTree(nil): %v", err)
	}
	if hex.EncodeToString(tree.Root()) != hex.EncodeToString(EmptyMerkleRoot) {
		t.Errorf("empty batch root = %x, want EmptyMerkleRoot", tree.Root())
	}
}

func TestBuildMerkleTree_SharesEncodingWithCanonicalBatchDigest(t *testing.T) {
	// Not a golden vector -- a structural pin: changing one entry's amount
	// must change the Merkle root (proving the leaf actually depends on
	// the full entry payload, the same fields CanonicalBatchDigest hashes,
	// not some subset).
	entries := []AttestedEntry{
		{EntryID: 1, JournalID: 1, AccountHolder: 100, CurrencyID: 1, ClassificationID: 1, EntryType: EntryTypeDebit, Amount: decimal.NewFromInt(10), EffectiveAt: time.Date(2026, 8, 21, 0, 0, 0, 0, time.UTC)},
		{EntryID: 2, JournalID: 1, AccountHolder: 200, CurrencyID: 1, ClassificationID: 2, EntryType: EntryTypeCredit, Amount: decimal.NewFromInt(10), EffectiveAt: time.Date(2026, 8, 21, 0, 0, 0, 0, time.UTC)},
	}
	treeA, err := BuildMerkleTree(entries)
	if err != nil {
		t.Fatalf("BuildMerkleTree: %v", err)
	}

	modified := make([]AttestedEntry, len(entries))
	copy(modified, entries)
	modified[0].Amount = modified[0].Amount.Add(decimal.NewFromInt(1))
	treeB, err := BuildMerkleTree(modified)
	if err != nil {
		t.Fatalf("BuildMerkleTree: %v", err)
	}

	if hex.EncodeToString(treeA.Root()) == hex.EncodeToString(treeB.Root()) {
		t.Error("changing an entry's amount did not change the Merkle root")
	}
}
