// Package server: handler_audit.go
// Read-only audit / investigation endpoints backed by core.AuditQuerier.
// These expose facade capability (ledger.Service.Audit()) that was previously
// only reachable via cmd/ledger-cli.
package server

import (
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/azex-ai/ledger/core"
	"github.com/azex-ai/ledger/pkg/httpx"
)

type bookingTraceResponse struct {
	Booking  bookingResponse   `json:"booking"`
	Events   []eventResponse   `json:"events"`
	Journals []journalResponse `json:"journals"`
}

// parseRFC3339Param parses an optional RFC3339 query value. An empty value
// returns the zero time and no error — callers treat the zero time as
// "unbounded" on that side of a range filter. Shared by handler_trends.go.
func parseRFC3339Param(name, raw string) (time.Time, error) {
	if raw == "" {
		return time.Time{}, nil
	}
	t, err := time.Parse(time.RFC3339, raw)
	if err != nil {
		return time.Time{}, httpx.ErrBadRequest(name + " must be RFC3339 format")
	}
	return t, nil
}

// handleListAuditJournals lists journals either by account dimension
// (holder+currency_uid, optionally narrowed by classification_uid and/or
// from/to) or by a global time range (from/to with no holder). Exactly one
// of the two modes must be selected by the query params provided.
func (s *Server) handleListAuditJournals(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()

	var holder int64
	var err error
	if h := q.Get("holder"); h != "" {
		if holder, err = strconv.ParseInt(h, 10, 64); err != nil {
			httpx.Error(w, httpx.ErrBadRequest("holder must be a number"))
			return
		}
	}
	currencyUID := q.Get("currency_uid")
	classificationUID := q.Get("classification_uid")

	from, err := parseRFC3339Param("from", q.Get("from"))
	if err != nil {
		httpx.Error(w, err)
		return
	}
	to, err := parseRFC3339Param("to", q.Get("to"))
	if err != nil {
		httpx.Error(w, err)
		return
	}

	limit := parsePageLimit(r)

	filter := core.AuditFilter{
		AccountHolder:     holder,
		CurrencyUID:       currencyUID,
		ClassificationUID: classificationUID,
		Since:             from,
		Until:             to,
		Cursor:            q.Get("cursor"),
		Limit:             limit,
	}

	var journals []core.Journal
	var nextCursor string
	switch {
	case holder != 0 || currencyUID != "":
		if holder == 0 || currencyUID == "" {
			httpx.Error(w, httpx.ErrBadRequest("holder and currency_uid must be provided together"))
			return
		}
		journals, nextCursor, err = s.audit.ListJournalsByAccount(r.Context(), filter)
	case !from.IsZero() || !to.IsZero():
		journals, nextCursor, err = s.audit.ListJournalsByTimeRange(r.Context(), filter)
	default:
		httpx.Error(w, httpx.ErrBadRequest("provide holder+currency_uid or from/to"))
		return
	}
	if err != nil {
		httpx.Error(w, err)
		return
	}

	resp := PagedResponse[journalResponse]{
		List:       make([]journalResponse, len(journals)),
		NextCursor: nextCursor,
	}
	for i, j := range journals {
		resp.List[i] = toJournalResponse(&j)
	}
	httpx.OK(w, resp)
}

// handleTraceBooking returns a booking together with every event and every
// journal generated by those events — the standard support/audit
// investigation shape.
func (s *Server) handleTraceBooking(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		httpx.Error(w, httpx.ErrBadRequest("invalid booking uid"))
		return
	}

	trace, err := s.audit.TraceBooking(r.Context(), uid)
	if err != nil {
		httpx.Error(w, err)
		return
	}

	events := make([]eventResponse, len(trace.Events))
	for i, e := range trace.Events {
		events[i] = eventToResponse(&e)
	}
	journals := make([]journalResponse, len(trace.Journals))
	for i, j := range trace.Journals {
		journals[i] = toJournalResponse(&j)
	}

	httpx.OK(w, bookingTraceResponse{
		Booking:  bookingToResponse(&trace.Booking),
		Events:   events,
		Journals: journals,
	})
}

// handleListReversals returns the full reversal chain for a journal — the
// root journal plus any journals that transitively reverse it.
func (s *Server) handleListReversals(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		httpx.Error(w, httpx.ErrBadRequest("invalid journal uid"))
		return
	}

	journals, err := s.audit.ListReversals(r.Context(), uid)
	if err != nil {
		httpx.Error(w, err)
		return
	}

	data := make([]journalResponse, len(journals))
	for i, j := range journals {
		data[i] = toJournalResponse(&j)
	}
	httpx.OK(w, PagedResponse[journalResponse]{List: data})
}
