// Package server: handler_audit.go
// Read-only audit / investigation endpoints backed by core.AuditQuerier.
// These expose facade capability (ledger.Service.Audit()) that was previously
// only reachable via cmd/ledger-cli.
package server

import (
	"net/http"
	"strconv"
	"time"

	"github.com/go-chi/chi/v5"

	"github.com/azex-ai/ledger/core"
	"github.com/azex-ai/ledger/pkg/httpx"
)

type bookingTraceResponse struct {
	Booking  bookingResponse   `json:"booking"`
	Events   []eventResponse   `json:"events"`
	Journals []journalResponse `json:"journals"`
}

// parseRFC3339Param parses an optional RFC3339 query value. An empty value
// returns the zero time and no error — callers treat the zero time as
// "unbounded" on that side of a range filter. Shared by handler_trends.go.
func parseRFC3339Param(name, raw string) (time.Time, error) {
	if raw == "" {
		return time.Time{}, nil
	}
	t, err := time.Parse(time.RFC3339, raw)
	if err != nil {
		return time.Time{}, httpx.ErrBadRequest(name + " must be RFC3339 format")
	}
	return t, nil
}

// handleListAuditJournals lists journals either by account dimension
// (holder+currency_id, optionally narrowed by classification_id and/or
// from/to) or by a global time range (from/to with no holder). Exactly one
// of the two modes must be selected by the query params provided.
func (s *Server) handleListAuditJournals(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()

	var holder, currencyID, classificationID int64
	var err error
	if h := q.Get("holder"); h != "" {
		if holder, err = strconv.ParseInt(h, 10, 64); err != nil {
			httpx.Error(w, httpx.ErrBadRequest("holder must be a number"))
			return
		}
	}
	if c := q.Get("currency_id"); c != "" {
		if currencyID, err = strconv.ParseInt(c, 10, 64); err != nil {
			httpx.Error(w, httpx.ErrBadRequest("currency_id must be a number"))
			return
		}
	}
	if c := q.Get("classification_id"); c != "" {
		if classificationID, err = strconv.ParseInt(c, 10, 64); err != nil {
			httpx.Error(w, httpx.ErrBadRequest("classification_id must be a number"))
			return
		}
	}

	from, err := parseRFC3339Param("from", q.Get("from"))
	if err != nil {
		httpx.Error(w, err)
		return
	}
	to, err := parseRFC3339Param("to", q.Get("to"))
	if err != nil {
		httpx.Error(w, err)
		return
	}

	cursor, err := decodeCursor(q.Get("cursor"))
	if err != nil {
		httpx.Error(w, httpx.ErrBadRequest("invalid cursor value"))
		return
	}
	limit := parsePageLimit(r)

	filter := core.AuditFilter{
		AccountHolder:    holder,
		CurrencyID:       currencyID,
		ClassificationID: classificationID,
		Since:            from,
		Until:            to,
		Cursor:           cursor,
		Limit:            limit,
	}

	var journals []core.Journal
	switch {
	case holder != 0 || currencyID != 0:
		if holder == 0 || currencyID == 0 {
			httpx.Error(w, httpx.ErrBadRequest("holder and currency_id must be provided together"))
			return
		}
		journals, err = s.audit.ListJournalsByAccount(r.Context(), filter)
	case !from.IsZero() || !to.IsZero():
		journals, err = s.audit.ListJournalsByTimeRange(r.Context(), filter)
	default:
		httpx.Error(w, httpx.ErrBadRequest("provide holder+currency_id or from/to"))
		return
	}
	if err != nil {
		httpx.Error(w, err)
		return
	}

	resp := PagedResponse[journalResponse]{
		Data: make([]journalResponse, len(journals)),
	}
	for i, j := range journals {
		resp.Data[i] = toJournalResponse(&j)
	}
	if len(journals) == int(limit) {
		resp.NextCursor = encodeCursor(journals[len(journals)-1].ID)
	}
	httpx.OK(w, resp)
}

// handleTraceBooking returns a booking together with every event and every
// journal generated by those events — the standard support/audit
// investigation shape.
func (s *Server) handleTraceBooking(w http.ResponseWriter, r *http.Request) {
	id, err := parseIDParam(chi.URLParam(r, "id"))
	if err != nil {
		httpx.Error(w, httpx.ErrBadRequest("invalid booking ID"))
		return
	}

	trace, err := s.audit.TraceBooking(r.Context(), id)
	if err != nil {
		httpx.Error(w, err)
		return
	}

	events := make([]eventResponse, len(trace.Events))
	for i, e := range trace.Events {
		events[i] = eventToResponse(&e)
	}
	journals := make([]journalResponse, len(trace.Journals))
	for i, j := range trace.Journals {
		journals[i] = toJournalResponse(&j)
	}

	httpx.OK(w, bookingTraceResponse{
		Booking:  bookingToResponse(&trace.Booking),
		Events:   events,
		Journals: journals,
	})
}

// handleListReversals returns the full reversal chain for a journal — the
// root journal plus any journals that transitively reverse it.
func (s *Server) handleListReversals(w http.ResponseWriter, r *http.Request) {
	id, err := parseIDParam(chi.URLParam(r, "id"))
	if err != nil {
		httpx.Error(w, httpx.ErrBadRequest("invalid journal ID"))
		return
	}

	journals, err := s.audit.ListReversals(r.Context(), id)
	if err != nil {
		httpx.Error(w, err)
		return
	}

	data := make([]journalResponse, len(journals))
	for i, j := range journals {
		data[i] = toJournalResponse(&j)
	}
	httpx.OK(w, data)
}
