// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_lists.sql

package sqlcgen

import (
	"context"
	"time"
)

const getReversalChain = `-- name: GetReversalChain :many
WITH RECURSIVE chain AS (
    -- Anchor: walk UP to find the root of the chain
    SELECT j.id AS journal_id, j.reversal_of
    FROM journals j
    WHERE j.id = $1

    UNION ALL

    SELECT anc.id AS journal_id, anc.reversal_of
    FROM journals anc
    JOIN chain c ON anc.id = c.reversal_of
    WHERE anc.reversal_of IS NOT NULL
),
root AS (
    SELECT journal_id FROM chain WHERE reversal_of IS NULL
    LIMIT 1
),
full_chain AS (
    -- Walk DOWN from root to find all reversals
    SELECT j.id AS journal_id, j.reversal_of
    FROM journals j
    WHERE j.id = (SELECT journal_id FROM root)

    UNION ALL

    SELECT j.id AS journal_id, j.reversal_of
    FROM journals j
    JOIN full_chain fc ON j.reversal_of = fc.journal_id
)
SELECT DISTINCT j.id, j.journal_type_id, j.idempotency_key, j.total_debit, j.total_credit, j.metadata, j.actor_id, j.source, j.reversal_of, j.created_at, j.event_id
FROM journals j
JOIN full_chain fc ON fc.journal_id = j.id
ORDER BY j.id ASC
`

// Returns the reversal chain for a journal.
// Includes: the root journal + any journals that reference it (direct reversals).
// Transitively follows reversal_of links up the chain (up to the root)
// and down the chain (journals that reverse the given journal or any of its ancestors).
func (q *Queries) GetReversalChain(ctx context.Context, id int64) ([]Journal, error) {
	rows, err := q.db.Query(ctx, getReversalChain, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsByAccount = `-- name: ListJournalsByAccount :many

SELECT DISTINCT j.id, j.journal_type_id, j.idempotency_key, j.total_debit, j.total_credit, j.metadata, j.actor_id, j.source, j.reversal_of, j.created_at, j.event_id
FROM journals j
JOIN journal_entries je ON je.journal_id = j.id
WHERE je.account_holder = $1::bigint
  AND je.currency_id    = $2::bigint
  AND ($3::bigint = 0 OR je.classification_id = $3::bigint)
  AND ($4::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR j.created_at >= $4::timestamptz)
  AND ($5::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR j.created_at <= $5::timestamptz)
  AND j.id > $6::bigint
ORDER BY j.id ASC
LIMIT $7::int
`

type ListJournalsByAccountParams struct {
	Holder           int64     `json:"holder"`
	CurrencyID       int64     `json:"currency_id"`
	ClassificationID int64     `json:"classification_id"`
	Since            time.Time `json:"since"`
	Until            time.Time `json:"until"`
	CursorID         int64     `json:"cursor_id"`
	PageLimit        int32     `json:"page_limit"`
}

// audit_lists.sql
// Read-only queries for the audit layer.
// All list queries use keyset (cursor) pagination on journal.id ASC.
// Returns journals whose entries touch (holder, currency_id[, classification_id]).
// classification_id = 0 means "all classifications".
// Keyset cursor: id > cursor_id, ordered by id ASC.
// since/until zero value (year 0001) is treated as unbounded.
func (q *Queries) ListJournalsByAccount(ctx context.Context, arg ListJournalsByAccountParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listJournalsByAccount,
		arg.Holder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.Since,
		arg.Until,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsByTimeRange = `-- name: ListJournalsByTimeRange :many
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id
FROM journals
WHERE ($1::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR created_at >= $1::timestamptz)
  AND ($2::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR created_at <= $2::timestamptz)
  AND id > $3::bigint
ORDER BY id ASC
LIMIT $4::int
`

type ListJournalsByTimeRangeParams struct {
	Since     time.Time `json:"since"`
	Until     time.Time `json:"until"`
	CursorID  int64     `json:"cursor_id"`
	PageLimit int32     `json:"page_limit"`
}

// Returns journals created within [since, until].
// since/until zero value (year 0001) is treated as unbounded on that side.
func (q *Queries) ListJournalsByTimeRange(ctx context.Context, arg ListJournalsByTimeRangeParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listJournalsByTimeRange,
		arg.Since,
		arg.Until,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traceBookingEvents = `-- name: TraceBookingEvents :many
SELECT id, classification_code, booking_id, account_holder, currency_id, from_status, to_status, amount, settled_amount, journal_id, metadata, occurred_at, delivery_status, attempts, max_attempts, next_attempt_at, delivered_at, created_at, actor_id, source
FROM events
WHERE booking_id = $1
ORDER BY id ASC
`

// Returns all events for a booking in ascending order.
func (q *Queries) TraceBookingEvents(ctx context.Context, bookingID int64) ([]Event, error) {
	rows, err := q.db.Query(ctx, traceBookingEvents, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationCode,
			&i.BookingID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Amount,
			&i.SettledAmount,
			&i.JournalID,
			&i.Metadata,
			&i.OccurredAt,
			&i.DeliveryStatus,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
			&i.ActorID,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const traceBookingJournals = `-- name: TraceBookingJournals :many
SELECT DISTINCT j.id, j.journal_type_id, j.idempotency_key, j.total_debit, j.total_credit, j.metadata, j.actor_id, j.source, j.reversal_of, j.created_at, j.event_id
FROM journals j
JOIN events e ON e.journal_id = j.id
WHERE e.booking_id = $1
ORDER BY j.id ASC
`

// Returns all journals linked to events for a booking, ordered by id.
func (q *Queries) TraceBookingJournals(ctx context.Context, bookingID int64) ([]Journal, error) {
	rows, err := q.db.Query(ctx, traceBookingJournals, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
