// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance_trends.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalanceTrendGapFill = `-- name: GetBalanceTrendGapFill :many

WITH
date_series AS (
    SELECT d::date AS day
    FROM generate_series(
        $1::date,
        $2::date,
        interval '1 day'
    ) AS d
),
snapshots AS (
    SELECT
        snapshot_date,
        balance
    FROM balance_snapshots
    WHERE account_holder    = $3::bigint
      AND currency_id       = $4::bigint
      AND ($5::bigint = 0 OR classification_id = $5::bigint)
      AND snapshot_date BETWEEN $1::date AND $2::date
),
daily_flows AS (
    SELECT
        (j.created_at AT TIME ZONE 'UTC')::date AS flow_date,
        COALESCE(SUM(CASE WHEN je.entry_type = 'credit' THEN je.amount ELSE 0::numeric END), 0) AS inflow,
        COALESCE(SUM(CASE WHEN je.entry_type = 'debit'  THEN je.amount ELSE 0::numeric END), 0) AS outflow
    FROM journal_entries je
    JOIN journals j ON j.id = je.journal_id
    WHERE je.account_holder = $3::bigint
      AND je.currency_id    = $4::bigint
      AND ($5::bigint = 0 OR je.classification_id = $5::bigint)
      AND (j.created_at AT TIME ZONE 'UTC')::date
            BETWEEN $1::date AND $2::date
    GROUP BY flow_date
),
joined AS (
    SELECT
        ds.day,
        s.balance                          AS snap_balance,
        COALESCE(df.inflow,  0::numeric)   AS inflow,
        COALESCE(df.outflow, 0::numeric)   AS outflow,
        -- Group counter: increments each time a non-null snapshot appears.
        -- All consecutive NULLs following a known value get the same group number,
        -- allowing MAX() to carry the last known balance forward.
        COUNT(s.balance) OVER (
            ORDER BY ds.day
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS grp
    FROM date_series ds
    LEFT JOIN snapshots       s  ON s.snapshot_date = ds.day
    LEFT JOIN daily_flows     df ON df.flow_date    = ds.day
)
SELECT
    day,
    COALESCE(
        MAX(snap_balance) OVER (PARTITION BY grp ORDER BY day ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
        0::numeric
    ) AS balance,
    inflow,
    outflow
FROM joined
ORDER BY day
`

type GetBalanceTrendGapFillParams struct {
	FromDate         pgtype.Date `json:"from_date"`
	UntilDate        pgtype.Date `json:"until_date"`
	Holder           int64       `json:"holder"`
	CurrencyID       int64       `json:"currency_id"`
	ClassificationID int64       `json:"classification_id"`
}

type GetBalanceTrendGapFillRow struct {
	Day     pgtype.Date `json:"day"`
	Balance interface{} `json:"balance"`
	Inflow  interface{} `json:"inflow"`
	Outflow interface{} `json:"outflow"`
}

// balance_trends.sql
// Gap-filled daily balance time series.
//
// Strategy:
//  1. generate_series expands the full date range so every day is present.
//  2. LEFT JOIN balance_snapshots brings in known data points.
//  3. A "last non-null" forward-fill is done with a subquery that groups by
//     a running count of non-null snapshots (standard PostgreSQL idiom).
//  4. Daily inflow/outflow are aggregated from journal_entries.
//
// The caller is responsible for overriding today's balance with the live
// checkpoint+delta value (done in Go, not SQL, to avoid coupling).
// Returns one row per calendar day in [from_date, until_date] (inclusive).
func (q *Queries) GetBalanceTrendGapFill(ctx context.Context, arg GetBalanceTrendGapFillParams) ([]GetBalanceTrendGapFillRow, error) {
	rows, err := q.db.Query(ctx, getBalanceTrendGapFill,
		arg.FromDate,
		arg.UntilDate,
		arg.Holder,
		arg.CurrencyID,
		arg.ClassificationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceTrendGapFillRow{}
	for rows.Next() {
		var i GetBalanceTrendGapFillRow
		if err := rows.Scan(
			&i.Day,
			&i.Balance,
			&i.Inflow,
			&i.Outflow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
