// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: balance_trends.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalanceAtForTrendDimension = `-- name: GetBalanceAtForTrendDimension :one
SELECT COALESCE(SUM(ledger_signed_amount(c.normal_side, je.entry_type, je.amount)), 0)::numeric AS balance
FROM journal_entries je
INNER JOIN classifications c ON c.id = je.classification_id
WHERE je.account_holder = $1::bigint
  AND je.currency_id    = $2::bigint
  AND ($3::bigint = 0 OR je.classification_id = $3::bigint)
  AND je.effective_at   < $4::timestamptz
`

type GetBalanceAtForTrendDimensionParams struct {
	Holder           int64     `json:"holder"`
	CurrencyID       int64     `json:"currency_id"`
	ClassificationID int64     `json:"classification_id"`
	Cutoff           time.Time `json:"cutoff"`
}

// The live, snapshot-free balance for one trend dimension as of cutoff. Used
// to replace a stale cached day in the series.
func (q *Queries) GetBalanceAtForTrendDimension(ctx context.Context, arg GetBalanceAtForTrendDimensionParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBalanceAtForTrendDimension,
		arg.Holder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.Cutoff,
	)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const getBalanceTrendGapFill = `-- name: GetBalanceTrendGapFill :many

WITH
date_series AS (
    SELECT d::date AS day
    FROM generate_series(
        $1::date,
        $2::date,
        interval '1 day'
    ) AS d
),
snapshots AS (
    SELECT
        snapshot_date,
        balance
    FROM balance_snapshots
    WHERE account_holder    = $3::bigint
      AND currency_id       = $4::bigint
      AND ($5::bigint = 0 OR classification_id = $5::bigint)
      AND snapshot_date BETWEEN $1::date AND $2::date
),
daily_flows AS (
    -- "Day" is keyed on effective_at (business date), not created_at (write
    -- date). effective_at is denormalized onto journal_entries so this no
    -- longer needs to join journals — see
    -- docs/plans/2026-07-02-financial-core-hardening-design.md §1.
    --
    -- inflow / outflow are normal_side-aware and go through the ledger's
    -- single sign authority (ledger_signed_amount, migration 009,
    -- docs/INVARIANTS.md I-43). "inflow" means "made this dimension's balance
    -- go UP", the same definition holder.sql:17 states for its net_amount.
    --
    -- These two columns used to test entry_type directly -- credit = inflow,
    -- debit = outflow -- without joining classifications at all. For
    -- main_wallet (debit-normal, the canonical user wallet) that is exactly
    -- backwards: the 2026-09-02 audit measured one JSON row reading
    -- balance=395 inflow=105 outflow=500 for a holder who had DEPOSITED 500.
    -- It was the eighteenth independent copy of the sign convention in the
    -- repository and the only one whose answer was wrong; two rounds of
    -- manual enumeration had missed the file. It is now enumerated by
    -- machine instead -- see postgres/sign_authority_gate_test.go (I-50).
    SELECT
        (je.effective_at AT TIME ZONE 'UTC')::date AS flow_date,
        COALESCE(SUM(GREATEST(ledger_signed_amount(c.normal_side, je.entry_type, je.amount), 0::numeric)), 0) AS inflow,
        COALESCE(SUM(GREATEST(-ledger_signed_amount(c.normal_side, je.entry_type, je.amount), 0::numeric)), 0) AS outflow
    FROM journal_entries je
    INNER JOIN classifications c ON c.id = je.classification_id
    WHERE je.account_holder = $3::bigint
      AND je.currency_id    = $4::bigint
      AND ($5::bigint = 0 OR je.classification_id = $5::bigint)
      AND (je.effective_at AT TIME ZONE 'UTC')::date
            BETWEEN $1::date AND $2::date
    GROUP BY flow_date
),
joined AS (
    SELECT
        ds.day,
        s.balance                          AS snap_balance,
        COALESCE(df.inflow,  0::numeric)   AS inflow,
        COALESCE(df.outflow, 0::numeric)   AS outflow,
        -- Group counter: increments each time a non-null snapshot appears.
        -- All consecutive NULLs following a known value get the same group number,
        -- allowing MAX() to carry the last known balance forward.
        COUNT(s.balance) OVER (
            ORDER BY ds.day
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS grp
    FROM date_series ds
    LEFT JOIN snapshots       s  ON s.snapshot_date = ds.day
    LEFT JOIN daily_flows     df ON df.flow_date    = ds.day
)
SELECT
    day,
    COALESCE(
        MAX(snap_balance) OVER (PARTITION BY grp ORDER BY day ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW),
        0::numeric
    ) AS balance,
    inflow,
    outflow
FROM joined
ORDER BY day
`

type GetBalanceTrendGapFillParams struct {
	FromDate         pgtype.Date `json:"from_date"`
	UntilDate        pgtype.Date `json:"until_date"`
	Holder           int64       `json:"holder"`
	CurrencyID       int64       `json:"currency_id"`
	ClassificationID int64       `json:"classification_id"`
}

type GetBalanceTrendGapFillRow struct {
	Day     pgtype.Date `json:"day"`
	Balance interface{} `json:"balance"`
	Inflow  interface{} `json:"inflow"`
	Outflow interface{} `json:"outflow"`
}

// balance_trends.sql
// Gap-filled daily balance time series.
//
// Strategy:
//  1. generate_series expands the full date range so every day is present.
//  2. LEFT JOIN balance_snapshots brings in known data points.
//  3. A "last non-null" forward-fill is done with a subquery that groups by
//     a running count of non-null snapshots (standard PostgreSQL idiom).
//  4. Daily inflow/outflow are aggregated from journal_entries.
//
// The caller is responsible for overriding today's balance with the live
// checkpoint+delta value (done in Go, not SQL, to avoid coupling).
// Returns one row per calendar day in [from_date, until_date] (inclusive).
func (q *Queries) GetBalanceTrendGapFill(ctx context.Context, arg GetBalanceTrendGapFillParams) ([]GetBalanceTrendGapFillRow, error) {
	rows, err := q.db.Query(ctx, getBalanceTrendGapFill,
		arg.FromDate,
		arg.UntilDate,
		arg.Holder,
		arg.CurrencyID,
		arg.ClassificationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBalanceTrendGapFillRow{}
	for rows.Next() {
		var i GetBalanceTrendGapFillRow
		if err := rows.Scan(
			&i.Day,
			&i.Balance,
			&i.Inflow,
			&i.Outflow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalanceTrendSnapshotStaleness = `-- name: ListBalanceTrendSnapshotStaleness :many
SELECT
    ds.day::date                AS day,
    s.snapshot_created_at,
    e.max_entry_created_at
FROM (
    SELECT d::date AS day
    FROM generate_series(
        $1::date,
        $2::date,
        interval '1 day'
    ) AS d
) ds
LEFT JOIN LATERAL (
    -- Deliberately NOT filtered by classification. A snapshot is taken for a
    -- whole (holder, currency) at once, so its timestamp is the baseline for
    -- every dimension of that day -- including a dimension that has no row of
    -- its own. Filtering here would make the query blind to exactly the case
    -- that motivated it: a backdated journal opening a position that did not
    -- exist when the snapshot ran has nothing to compare against, so it would
    -- read as "not cached, therefore not stale" and gap-fill to zero.
    SELECT MIN(bs.created_at) AS snapshot_created_at
    FROM balance_snapshots bs
    WHERE bs.account_holder = $3::bigint
      AND bs.currency_id    = $4::bigint
      AND bs.snapshot_date  = ds.day
) s ON TRUE
LEFT JOIN LATERAL (
    SELECT MAX(je.created_at) AS max_entry_created_at
    FROM journal_entries je
    WHERE je.account_holder = $3::bigint
      AND je.currency_id    = $4::bigint
      AND je.effective_at   < (ds.day + 1)
) e ON TRUE
ORDER BY ds.day
`

type ListBalanceTrendSnapshotStalenessParams struct {
	FromDate   pgtype.Date `json:"from_date"`
	UntilDate  pgtype.Date `json:"until_date"`
	Holder     int64       `json:"holder"`
	CurrencyID int64       `json:"currency_id"`
}

type ListBalanceTrendSnapshotStalenessRow struct {
	Day               pgtype.Date `json:"day"`
	SnapshotCreatedAt interface{} `json:"snapshot_created_at"`
	MaxEntryCreatedAt interface{} `json:"max_entry_created_at"`
}

// Per calendar day in [from_date, until_date]: when the day's snapshot rows
// were written, and the latest write of any entry that BELONGS to that day
// (effective_at < day + 1).
//
// GetBalanceTrendGapFill reads balance_snapshots directly, so it inherits
// none of the self-healing RollupAdapter.GetSnapshotBalances does. That was
// not a theoretical gap: /holders/{h}/trends is a user-facing endpoint and it
// returned pre-backdating values for every day except today, while the
// as-of endpoint next to it returned the corrected ones -- two reads of the
// same business date disagreeing, with only one of them documented as
// self-healing (docs/INVARIANTS.md I-14, audit A-M5).
//
// A day is stale when max_entry_created_at > snapshot_created_at: an entry
// dated into that day was WRITTEN after the snapshot that was supposed to
// summarise it. Days with no snapshot row are not stale -- they are
// forward-filled from the last known value, which is the gap-fill contract,
// not a cache.
func (q *Queries) ListBalanceTrendSnapshotStaleness(ctx context.Context, arg ListBalanceTrendSnapshotStalenessParams) ([]ListBalanceTrendSnapshotStalenessRow, error) {
	rows, err := q.db.Query(ctx, listBalanceTrendSnapshotStaleness,
		arg.FromDate,
		arg.UntilDate,
		arg.Holder,
		arg.CurrencyID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalanceTrendSnapshotStalenessRow{}
	for rows.Next() {
		var i ListBalanceTrendSnapshotStalenessRow
		if err := rows.Scan(&i.Day, &i.SnapshotCreatedAt, &i.MaxEntryCreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
