// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBooking = `-- name: GetBooking :one
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM bookings WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByIdempotencyKey = `-- name: GetBookingByIdempotencyKey :one
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM bookings WHERE idempotency_key = $1
`

func (q *Queries) GetBookingByIdempotencyKey(ctx context.Context, idempotencyKey string) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIdempotencyKey, idempotencyKey)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingForUpdate = `-- name: GetBookingForUpdate :one
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM bookings WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBookingForUpdate(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingForUpdate, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBooking = `-- name: InsertBooking :one
INSERT INTO bookings (
    classification_id, account_holder, currency_id, amount, status,
    channel_name, idempotency_key, metadata, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
`

type InsertBookingParams struct {
	ClassificationID int64          `json:"classification_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	Amount           pgtype.Numeric `json:"amount"`
	Status           string         `json:"status"`
	ChannelName      string         `json:"channel_name"`
	IdempotencyKey   string         `json:"idempotency_key"`
	Metadata         []byte         `json:"metadata"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, insertBooking,
		arg.ClassificationID,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.Amount,
		arg.Status,
		arg.ChannelName,
		arg.IdempotencyKey,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkBookingJournal = `-- name: LinkBookingJournal :one
UPDATE bookings
SET journal_id = $2, updated_at = now()
WHERE id = $1
  AND journal_id IS NULL
RETURNING id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
`

type LinkBookingJournalParams struct {
	ID        int64       `json:"id"`
	JournalID pgtype.Int8 `json:"journal_id"`
}

func (q *Queries) LinkBookingJournal(ctx context.Context, arg LinkBookingJournalParams) (Booking, error) {
	row := q.db.QueryRow(ctx, linkBookingJournal, arg.ID, arg.JournalID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookingsByFilter = `-- name: ListBookingsByFilter :many
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM bookings
WHERE (account_holder = $1 OR $1 = 0)
  AND (classification_id = $2 OR $2 = 0)
  AND (status = $3 OR $3 = '')
  AND id > $4
ORDER BY id
LIMIT $5
`

type ListBookingsByFilterParams struct {
	AccountHolder    int64  `json:"account_holder"`
	ClassificationID int64  `json:"classification_id"`
	Status           string `json:"status"`
	ID               int64  `json:"id"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) ListBookingsByFilter(ctx context.Context, arg ListBookingsByFilterParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByFilter,
		arg.AccountHolder,
		arg.ClassificationID,
		arg.Status,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.Amount,
			&i.SettledAmount,
			&i.Status,
			&i.ChannelName,
			&i.ChannelRef,
			&i.ReservationID,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredBookings = `-- name: ListExpiredBookings :many
SELECT b.id, b.classification_id, b.account_holder, b.currency_id, b.amount, b.settled_amount, b.status, b.channel_name, b.channel_ref, b.reservation_id, b.journal_id, b.idempotency_key, b.metadata, b.expires_at, b.created_at, b.updated_at
FROM bookings b
INNER JOIN classifications c ON c.id = b.classification_id
WHERE b.expires_at != 'epoch'
  AND b.expires_at < now()
  AND COALESCE(c.lifecycle -> 'transitions' -> b.status, '[]'::jsonb) ? 'expired'
LIMIT $1
`

func (q *Queries) ListExpiredBookings(ctx context.Context, limit int32) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listExpiredBookings, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Booking{}
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.Amount,
			&i.SettledAmount,
			&i.Status,
			&i.ChannelName,
			&i.ChannelRef,
			&i.ReservationID,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingTransition = `-- name: UpdateBookingTransition :exec
UPDATE bookings
SET status = $2, channel_ref = $3, settled_amount = $4,
    journal_id = $5, metadata = $6, updated_at = now()
WHERE id = $1
`

type UpdateBookingTransitionParams struct {
	ID            int64          `json:"id"`
	Status        string         `json:"status"`
	ChannelRef    string         `json:"channel_ref"`
	SettledAmount pgtype.Numeric `json:"settled_amount"`
	JournalID     pgtype.Int8    `json:"journal_id"`
	Metadata      []byte         `json:"metadata"`
}

func (q *Queries) UpdateBookingTransition(ctx context.Context, arg UpdateBookingTransitionParams) error {
	_, err := q.db.Exec(ctx, updateBookingTransition,
		arg.ID,
		arg.Status,
		arg.ChannelRef,
		arg.SettledAmount,
		arg.JournalID,
		arg.Metadata,
	)
	return err
}
