// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain_cursors.sql

package sqlcgen

import (
	"context"
)

const getChainCursor = `-- name: GetChainCursor :one
SELECT chain_id, last_scanned_block, updated_at FROM chain_cursors WHERE chain_id = $1
`

func (q *Queries) GetChainCursor(ctx context.Context, chainID int64) (ChainCursor, error) {
	row := q.db.QueryRow(ctx, getChainCursor, chainID)
	var i ChainCursor
	err := row.Scan(&i.ChainID, &i.LastScannedBlock, &i.UpdatedAt)
	return i, err
}

const setChainCursor = `-- name: SetChainCursor :exec
INSERT INTO chain_cursors (chain_id, last_scanned_block)
VALUES ($1, $2)
ON CONFLICT (chain_id) DO UPDATE SET
    last_scanned_block = EXCLUDED.last_scanned_block,
    updated_at          = now()
`

type SetChainCursorParams struct {
	ChainID          int64 `json:"chain_id"`
	LastScannedBlock int64 `json:"last_scanned_block"`
}

// Upsert: first call for a chain initializes the row, subsequent calls
// advance it. The watcher is expected to call this monotonically
// (last_scanned_block only moves forward); this query does not enforce
// monotonicity -- that is an orchestration-layer invariant (service/), not a
// storage one.
func (q *Queries) SetChainCursor(ctx context.Context, arg SetChainCursorParams) error {
	_, err := q.db.Exec(ctx, setChainCursor, arg.ChainID, arg.LastScannedBlock)
	return err
}
