// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chain_cursors.sql

package sqlcgen

import (
	"context"
)

const getChainCursor = `-- name: GetChainCursor :one
SELECT chain_id, last_scanned_block, updated_at FROM chain_cursors WHERE chain_id = $1
`

func (q *Queries) GetChainCursor(ctx context.Context, chainID int64) (ChainCursor, error) {
	row := q.db.QueryRow(ctx, getChainCursor, chainID)
	var i ChainCursor
	err := row.Scan(&i.ChainID, &i.LastScannedBlock, &i.UpdatedAt)
	return i, err
}

const setChainCursor = `-- name: SetChainCursor :exec
INSERT INTO chain_cursors (chain_id, last_scanned_block)
VALUES ($1, $2)
ON CONFLICT (chain_id) DO UPDATE SET
    last_scanned_block = EXCLUDED.last_scanned_block,
    updated_at          = now()
WHERE chain_cursors.last_scanned_block < EXCLUDED.last_scanned_block
`

type SetChainCursorParams struct {
	ChainID          int64 `json:"chain_id"`
	LastScannedBlock int64 `json:"last_scanned_block"`
}

// Upsert: first call for a chain initializes the row, subsequent calls
// advance it. Monotonicity (last_scanned_block only ever moves forward) is
// enforced HERE, by the WHERE clause below -- the same shape
// UpsertBalanceCheckpoint (checkpoints.sql) already uses.
//
// It used to say monotonicity was "an orchestration-layer invariant
// (service/)", and service/ did not implement it (concurrency.md B-m7): with
// two replicas both running the watcher, a slow one that read cursor=100,
// stalled, then wrote 200 while a fast one had already reached 300 would drag
// the cursor backwards. Re-scanning is idempotent so no deposit was lost, but
// an invariant nobody implements is worse than no invariant -- and the
// fail-closed cursor semantics I-52 now depends on (a window is only marked
// scanned once every sighting in it is ingested or dead-lettered) would be
// silently undone by a backwards write.
func (q *Queries) SetChainCursor(ctx context.Context, arg SetChainCursorParams) error {
	_, err := q.db.Exec(ctx, setChainCursor, arg.ChainID, arg.LastScannedBlock)
	return err
}
