// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkpoints.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateCheckpointsByClassification = `-- name: AggregateCheckpointsByClassification :many
SELECT
  currency_id,
  classification_id,
  COALESCE(SUM(balance), 0) as total_balance
FROM balance_checkpoints
GROUP BY currency_id, classification_id
ORDER BY currency_id, classification_id
`

type AggregateCheckpointsByClassificationRow struct {
	CurrencyID       int64       `json:"currency_id"`
	ClassificationID int64       `json:"classification_id"`
	TotalBalance     interface{} `json:"total_balance"`
}

func (q *Queries) AggregateCheckpointsByClassification(ctx context.Context) ([]AggregateCheckpointsByClassificationRow, error) {
	rows, err := q.db.Query(ctx, aggregateCheckpointsByClassification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateCheckpointsByClassificationRow{}
	for rows.Next() {
		var i AggregateCheckpointsByClassificationRow
		if err := rows.Scan(&i.CurrencyID, &i.ClassificationID, &i.TotalBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingRollups = `-- name: CountPendingRollups :one
SELECT COUNT(*) FROM rollup_queue WHERE processed_at IS NULL
`

func (q *Queries) CountPendingRollups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRollups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dequeueRollupBatch = `-- name: DequeueRollupBatch :many
WITH claimed AS (
    SELECT id
    FROM rollup_queue
    WHERE processed_at IS NULL
      AND (claimed_until IS NULL OR claimed_until < now())
      AND failed_attempts < 10
    ORDER BY created_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE rollup_queue AS q
SET claimed_until = $2
FROM claimed
WHERE q.id = claimed.id
RETURNING q.id, q.account_holder, q.currency_id, q.classification_id, q.created_at
`

type DequeueRollupBatchParams struct {
	Limit        int32              `json:"limit"`
	ClaimedUntil pgtype.Timestamptz `json:"claimed_until"`
}

type DequeueRollupBatchRow struct {
	ID               int64     `json:"id"`
	AccountHolder    int64     `json:"account_holder"`
	CurrencyID       int64     `json:"currency_id"`
	ClassificationID int64     `json:"classification_id"`
	CreatedAt        time.Time `json:"created_at"`
}

// Skip items that have failed too many times (failed_attempts >= 10) — they
// need operator attention, not another retry loop.
func (q *Queries) DequeueRollupBatch(ctx context.Context, arg DequeueRollupBatchParams) ([]DequeueRollupBatchRow, error) {
	rows, err := q.db.Query(ctx, dequeueRollupBatch, arg.Limit, arg.ClaimedUntil)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DequeueRollupBatchRow{}
	for rows.Next() {
		var i DequeueRollupBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueRollup = `-- name: EnqueueRollup :exec
INSERT INTO rollup_queue (account_holder, currency_id, classification_id)
VALUES ($1, $2, $3)
ON CONFLICT (account_holder, currency_id, classification_id) WHERE processed_at IS NULL DO NOTHING
`

type EnqueueRollupParams struct {
	AccountHolder    int64 `json:"account_holder"`
	CurrencyID       int64 `json:"currency_id"`
	ClassificationID int64 `json:"classification_id"`
}

func (q *Queries) EnqueueRollup(ctx context.Context, arg EnqueueRollupParams) error {
	_, err := q.db.Exec(ctx, enqueueRollup, arg.AccountHolder, arg.CurrencyID, arg.ClassificationID)
	return err
}

const getBalanceCheckpoint = `-- name: GetBalanceCheckpoint :one
SELECT account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at, updated_at
FROM balance_checkpoints
WHERE account_holder = $1 AND currency_id = $2 AND classification_id = $3
`

type GetBalanceCheckpointParams struct {
	AccountHolder    int64 `json:"account_holder"`
	CurrencyID       int64 `json:"currency_id"`
	ClassificationID int64 `json:"classification_id"`
}

func (q *Queries) GetBalanceCheckpoint(ctx context.Context, arg GetBalanceCheckpointParams) (BalanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, getBalanceCheckpoint, arg.AccountHolder, arg.CurrencyID, arg.ClassificationID)
	var i BalanceCheckpoint
	err := row.Scan(
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ClassificationID,
		&i.Balance,
		&i.LastEntryID,
		&i.LastEntryAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceCheckpoints = `-- name: GetBalanceCheckpoints :many
SELECT account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at, updated_at
FROM balance_checkpoints
WHERE account_holder = $1 AND currency_id = $2
`

type GetBalanceCheckpointsParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

func (q *Queries) GetBalanceCheckpoints(ctx context.Context, arg GetBalanceCheckpointsParams) ([]BalanceCheckpoint, error) {
	rows, err := q.db.Query(ctx, getBalanceCheckpoints, arg.AccountHolder, arg.CurrencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.Balance,
			&i.LastEntryID,
			&i.LastEntryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckpointMaxAgeSeconds = `-- name: GetCheckpointMaxAgeSeconds :one
SELECT COALESCE(EXTRACT(EPOCH FROM (now() - MIN(updated_at)))::bigint, 0)::bigint as max_age_seconds
FROM balance_checkpoints
`

func (q *Queries) GetCheckpointMaxAgeSeconds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getCheckpointMaxAgeSeconds)
	var max_age_seconds int64
	err := row.Scan(&max_age_seconds)
	return max_age_seconds, err
}

const getMaxEntryForAccountCurrencySince = `-- name: GetMaxEntryForAccountCurrencySince :one
SELECT
  COALESCE(MAX(id), 0)::bigint AS max_entry_id,
  COALESCE(MAX(created_at), 'epoch'::timestamptz) AS max_entry_at
FROM journal_entries
WHERE account_holder = $1
  AND currency_id = $2
  AND id > $3
`

type GetMaxEntryForAccountCurrencySinceParams struct {
	AccountHolder int64       `json:"account_holder"`
	CurrencyID    int64       `json:"currency_id"`
	ID            pgtype.Int8 `json:"id"`
}

type GetMaxEntryForAccountCurrencySinceRow struct {
	MaxEntryID int64       `json:"max_entry_id"`
	MaxEntryAt interface{} `json:"max_entry_at"`
}

func (q *Queries) GetMaxEntryForAccountCurrencySince(ctx context.Context, arg GetMaxEntryForAccountCurrencySinceParams) (GetMaxEntryForAccountCurrencySinceRow, error) {
	row := q.db.QueryRow(ctx, getMaxEntryForAccountCurrencySince, arg.AccountHolder, arg.CurrencyID, arg.ID)
	var i GetMaxEntryForAccountCurrencySinceRow
	err := row.Scan(&i.MaxEntryID, &i.MaxEntryAt)
	return i, err
}

const getMaxEntryID = `-- name: GetMaxEntryID :one
SELECT COALESCE(MAX(id), 0)::bigint as max_id FROM journal_entries
`

func (q *Queries) GetMaxEntryID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxEntryID)
	var max_id int64
	err := row.Scan(&max_id)
	return max_id, err
}

const listAllBalanceCheckpoints = `-- name: ListAllBalanceCheckpoints :many
SELECT account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at, updated_at
FROM balance_checkpoints
ORDER BY account_holder, currency_id, classification_id
`

func (q *Queries) ListAllBalanceCheckpoints(ctx context.Context) ([]BalanceCheckpoint, error) {
	rows, err := q.db.Query(ctx, listAllBalanceCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.Balance,
			&i.LastEntryID,
			&i.LastEntryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBalancesAt = `-- name: ListBalancesAt :many
SELECT
  je.account_holder,
  je.currency_id,
  je.classification_id,
  COALESCE(SUM(
    CASE
      WHEN c.normal_side = 'credit' AND je.entry_type = 'credit' THEN je.amount
      WHEN c.normal_side = 'credit' AND je.entry_type = 'debit' THEN -je.amount
      WHEN je.entry_type = 'debit' THEN je.amount
      ELSE -je.amount
    END
  ), 0)::numeric AS balance
FROM journal_entries je
INNER JOIN classifications c ON c.id = je.classification_id
WHERE je.created_at < $1
GROUP BY je.account_holder, je.currency_id, je.classification_id
ORDER BY je.account_holder, je.currency_id, je.classification_id
`

type ListBalancesAtRow struct {
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	Balance          pgtype.Numeric `json:"balance"`
}

func (q *Queries) ListBalancesAt(ctx context.Context, createdAt time.Time) ([]ListBalancesAtRow, error) {
	rows, err := q.db.Query(ctx, listBalancesAt, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBalancesAtRow{}
	for rows.Next() {
		var i ListBalancesAtRow
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRollupProcessed = `-- name: MarkRollupProcessed :exec
UPDATE rollup_queue
SET processed_at = now(), claimed_until = NULL
WHERE id = $1
`

func (q *Queries) MarkRollupProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRollupProcessed, id)
	return err
}

const releaseRollupClaim = `-- name: ReleaseRollupClaim :exec
UPDATE rollup_queue
SET claimed_until = NULL,
    failed_attempts = failed_attempts + 1
WHERE id = $1
  AND processed_at IS NULL
`

// Release the claim *and* bump failed_attempts so a permanently-failing item
// can be detected and excluded from future batches (see DequeueRollupBatch).
func (q *Queries) ReleaseRollupClaim(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, releaseRollupClaim, id)
	return err
}

const sumGlobalDebitCreditByCurrency = `-- name: SumGlobalDebitCreditByCurrency :many
SELECT
  currency_id,
  entry_type,
  COALESCE(SUM(amount), 0)::numeric AS total
FROM journal_entries
GROUP BY currency_id, entry_type
ORDER BY currency_id, entry_type
`

type SumGlobalDebitCreditByCurrencyRow struct {
	CurrencyID int64          `json:"currency_id"`
	EntryType  string         `json:"entry_type"`
	Total      pgtype.Numeric `json:"total"`
}

func (q *Queries) SumGlobalDebitCreditByCurrency(ctx context.Context) ([]SumGlobalDebitCreditByCurrencyRow, error) {
	rows, err := q.db.Query(ctx, sumGlobalDebitCreditByCurrency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumGlobalDebitCreditByCurrencyRow{}
	for rows.Next() {
		var i SumGlobalDebitCreditByCurrencyRow
		if err := rows.Scan(&i.CurrencyID, &i.EntryType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBalanceCheckpoint = `-- name: UpsertBalanceCheckpoint :exec
INSERT INTO balance_checkpoints (account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_holder, currency_id, classification_id)
DO UPDATE SET balance = $4, last_entry_id = $5, last_entry_at = $6, updated_at = now()
`

type UpsertBalanceCheckpointParams struct {
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	Balance          pgtype.Numeric `json:"balance"`
	LastEntryID      int64          `json:"last_entry_id"`
	LastEntryAt      time.Time      `json:"last_entry_at"`
}

func (q *Queries) UpsertBalanceCheckpoint(ctx context.Context, arg UpsertBalanceCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertBalanceCheckpoint,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.Balance,
		arg.LastEntryID,
		arg.LastEntryAt,
	)
	return err
}
