// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: checkpoints.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aggregateCheckpointsByClassification = `-- name: AggregateCheckpointsByClassification :many
SELECT
  currency_id,
  classification_id,
  COALESCE(SUM(balance), 0) as total_balance
FROM balance_checkpoints
GROUP BY currency_id, classification_id
ORDER BY currency_id, classification_id
`

type AggregateCheckpointsByClassificationRow struct {
	CurrencyID       int64       `json:"currency_id"`
	ClassificationID int64       `json:"classification_id"`
	TotalBalance     interface{} `json:"total_balance"`
}

func (q *Queries) AggregateCheckpointsByClassification(ctx context.Context) ([]AggregateCheckpointsByClassificationRow, error) {
	rows, err := q.db.Query(ctx, aggregateCheckpointsByClassification)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AggregateCheckpointsByClassificationRow{}
	for rows.Next() {
		var i AggregateCheckpointsByClassificationRow
		if err := rows.Scan(&i.CurrencyID, &i.ClassificationID, &i.TotalBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPendingRollups = `-- name: CountPendingRollups :one
SELECT COUNT(*) FROM rollup_queue WHERE processed_at IS NULL
`

func (q *Queries) CountPendingRollups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRollups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dequeueRollupBatch = `-- name: DequeueRollupBatch :many
SELECT id, account_holder, currency_id, classification_id, processed_at, created_at
FROM rollup_queue
WHERE processed_at IS NULL
ORDER BY created_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) DequeueRollupBatch(ctx context.Context, limit int32) ([]RollupQueue, error) {
	rows, err := q.db.Query(ctx, dequeueRollupBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RollupQueue{}
	for rows.Next() {
		var i RollupQueue
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueRollup = `-- name: EnqueueRollup :exec
INSERT INTO rollup_queue (account_holder, currency_id, classification_id)
VALUES ($1, $2, $3)
ON CONFLICT (account_holder, currency_id, classification_id) DO NOTHING
`

type EnqueueRollupParams struct {
	AccountHolder    int64 `json:"account_holder"`
	CurrencyID       int64 `json:"currency_id"`
	ClassificationID int64 `json:"classification_id"`
}

func (q *Queries) EnqueueRollup(ctx context.Context, arg EnqueueRollupParams) error {
	_, err := q.db.Exec(ctx, enqueueRollup, arg.AccountHolder, arg.CurrencyID, arg.ClassificationID)
	return err
}

const getBalanceCheckpoint = `-- name: GetBalanceCheckpoint :one
SELECT account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at, updated_at
FROM balance_checkpoints
WHERE account_holder = $1 AND currency_id = $2 AND classification_id = $3
`

type GetBalanceCheckpointParams struct {
	AccountHolder    int64 `json:"account_holder"`
	CurrencyID       int64 `json:"currency_id"`
	ClassificationID int64 `json:"classification_id"`
}

func (q *Queries) GetBalanceCheckpoint(ctx context.Context, arg GetBalanceCheckpointParams) (BalanceCheckpoint, error) {
	row := q.db.QueryRow(ctx, getBalanceCheckpoint, arg.AccountHolder, arg.CurrencyID, arg.ClassificationID)
	var i BalanceCheckpoint
	err := row.Scan(
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ClassificationID,
		&i.Balance,
		&i.LastEntryID,
		&i.LastEntryAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBalanceCheckpoints = `-- name: GetBalanceCheckpoints :many
SELECT account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at, updated_at
FROM balance_checkpoints
WHERE account_holder = $1 AND currency_id = $2
`

type GetBalanceCheckpointsParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

func (q *Queries) GetBalanceCheckpoints(ctx context.Context, arg GetBalanceCheckpointsParams) ([]BalanceCheckpoint, error) {
	rows, err := q.db.Query(ctx, getBalanceCheckpoints, arg.AccountHolder, arg.CurrencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.Balance,
			&i.LastEntryID,
			&i.LastEntryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMaxEntryID = `-- name: GetMaxEntryID :one
SELECT COALESCE(MAX(id), 0)::bigint as max_id FROM journal_entries
`

func (q *Queries) GetMaxEntryID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxEntryID)
	var max_id int64
	err := row.Scan(&max_id)
	return max_id, err
}

const listAllBalanceCheckpoints = `-- name: ListAllBalanceCheckpoints :many
SELECT account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at, updated_at
FROM balance_checkpoints
ORDER BY account_holder, currency_id, classification_id
`

func (q *Queries) ListAllBalanceCheckpoints(ctx context.Context) ([]BalanceCheckpoint, error) {
	rows, err := q.db.Query(ctx, listAllBalanceCheckpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceCheckpoint{}
	for rows.Next() {
		var i BalanceCheckpoint
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.Balance,
			&i.LastEntryID,
			&i.LastEntryAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRollupProcessed = `-- name: MarkRollupProcessed :exec
UPDATE rollup_queue SET processed_at = now() WHERE id = $1
`

func (q *Queries) MarkRollupProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRollupProcessed, id)
	return err
}

const upsertBalanceCheckpoint = `-- name: UpsertBalanceCheckpoint :exec
INSERT INTO balance_checkpoints (account_holder, currency_id, classification_id, balance, last_entry_id, last_entry_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (account_holder, currency_id, classification_id)
DO UPDATE SET balance = $4, last_entry_id = $5, last_entry_at = $6, updated_at = now()
`

type UpsertBalanceCheckpointParams struct {
	AccountHolder    int64              `json:"account_holder"`
	CurrencyID       int64              `json:"currency_id"`
	ClassificationID int64              `json:"classification_id"`
	Balance          pgtype.Numeric     `json:"balance"`
	LastEntryID      int64              `json:"last_entry_id"`
	LastEntryAt      pgtype.Timestamptz `json:"last_entry_at"`
}

func (q *Queries) UpsertBalanceCheckpoint(ctx context.Context, arg UpsertBalanceCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertBalanceCheckpoint,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.Balance,
		arg.LastEntryID,
		arg.LastEntryAt,
	)
	return err
}
