// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config_history.sql

package sqlcgen

import (
	"context"
	"time"
)

const listAccountPolicyChangesByHolder = `-- name: ListAccountPolicyChangesByHolder :many
SELECT apc.id, apc.policy_id, apc.old_state, apc.new_state, apc.actor_id, apc.created_at, ap.account_holder, ap.currency_id, ap.classification_id
FROM account_policy_changes apc
JOIN account_policies ap ON ap.id = apc.policy_id
WHERE ($1::bigint = 0 OR ap.account_holder = $1::bigint)
  AND ($2::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR apc.created_at >= $2::timestamptz)
  AND ($3::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR apc.created_at <= $3::timestamptz)
  AND ($4::bigint = 0 OR apc.id < $4::bigint)
ORDER BY apc.id DESC
LIMIT $5::int
`

type ListAccountPolicyChangesByHolderParams struct {
	AccountHolder int64     `json:"account_holder"`
	Since         time.Time `json:"since"`
	Until         time.Time `json:"until"`
	CursorID      int64     `json:"cursor_id"`
	PageLimit     int32     `json:"page_limit"`
}

type ListAccountPolicyChangesByHolderRow struct {
	ID               int64     `json:"id"`
	PolicyID         int64     `json:"policy_id"`
	OldState         []byte    `json:"old_state"`
	NewState         []byte    `json:"new_state"`
	ActorID          int64     `json:"actor_id"`
	CreatedAt        time.Time `json:"created_at"`
	AccountHolder    int64     `json:"account_holder"`
	CurrencyID       int64     `json:"currency_id"`
	ClassificationID int64     `json:"classification_id"`
}

// (Named ...ByHolder because account_policies.sql already carries a
// policy_id-scoped ListAccountPolicyChanges. That one has no caller outside
// the generated code and its own comment calls it a test/audit helper; this is
// the dimension an incident actually starts from.)
// The application-written trail for freeze/overdraft policy edits. Unlike the
// two above it carries a business actor_id, because UpsertAccountPolicy writes
// it in the caller's transaction -- and unlike them it is therefore only
// written when the change went through the application. Reading both this and
// the config_table_changes rows for account_policies is how a change made
// with raw SQL becomes visible as a change with no operator behind it.
// account_holder 0 means "every holder".
func (q *Queries) ListAccountPolicyChangesByHolder(ctx context.Context, arg ListAccountPolicyChangesByHolderParams) ([]ListAccountPolicyChangesByHolderRow, error) {
	rows, err := q.db.Query(ctx, listAccountPolicyChangesByHolder,
		arg.AccountHolder,
		arg.Since,
		arg.Until,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAccountPolicyChangesByHolderRow{}
	for rows.Next() {
		var i ListAccountPolicyChangesByHolderRow
		if err := rows.Scan(
			&i.ID,
			&i.PolicyID,
			&i.OldState,
			&i.NewState,
			&i.ActorID,
			&i.CreatedAt,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigTableChanges = `-- name: ListConfigTableChanges :many

SELECT id, table_name, old_row, new_row, changed_by, changed_at
FROM config_table_changes
WHERE ($1::text = '' OR table_name = $1::text)
  AND ($2::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR changed_at >= $2::timestamptz)
  AND ($3::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR changed_at <= $3::timestamptz)
  AND ($4::bigint = 0 OR id < $4::bigint)
ORDER BY id DESC
LIMIT $5::int
`

type ListConfigTableChangesParams struct {
	TableName string    `json:"table_name"`
	Since     time.Time `json:"since"`
	Until     time.Time `json:"until"`
	CursorID  int64     `json:"cursor_id"`
	PageLimit int32     `json:"page_limit"`
}

// config_history.sql
// The read side of the forensic trail (docs/INVARIANTS.md I-45, I-58).
//
// Migration 006 built three tables that answer "who changed the rule that
// decides where money goes", and nothing ever read them: no query file, no
// store method, no CLI subcommand, no runbook entry -- only tests. Evidence
// that is recorded but unreadable leaves "somebody tampered with the config"
// and "nothing ever happened" indistinguishable on every surface an operator
// can reach, which is the failure working-agreements §3 is about.
//
// Ordered newest-first, unlike audit_lists.sql: these are read during an
// incident, where the question is "what changed recently", not "replay this
// account's history from the beginning". Keyset cursor is therefore
// id < cursor, with 0 meaning "first page".
// Change rows for the guarded configuration and lifecycle tables.
// table_name ” means "every table". since/until zero value (year 0001) is
// treated as unbounded on that side.
func (q *Queries) ListConfigTableChanges(ctx context.Context, arg ListConfigTableChangesParams) ([]ConfigTableChange, error) {
	rows, err := q.db.Query(ctx, listConfigTableChanges,
		arg.TableName,
		arg.Since,
		arg.Until,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConfigTableChange{}
	for rows.Next() {
		var i ConfigTableChange
		if err := rows.Scan(
			&i.ID,
			&i.TableName,
			&i.OldRow,
			&i.NewRow,
			&i.ChangedBy,
			&i.ChangedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileScanCursorChanges = `-- name: ListReconcileScanCursorChanges :many
SELECT id, check_name, old_after_holder, old_after_currency, old_lap_dirty, new_after_holder, new_after_currency, new_lap_dirty, changed_by, changed_at, old_lap_scanned, new_lap_scanned
FROM reconcile_scan_cursor_changes
WHERE ($1::text = '' OR check_name = $1::text)
  AND ($2::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR changed_at >= $2::timestamptz)
  AND ($3::timestamptz <= '0001-01-02 00:00:00+00'::timestamptz OR changed_at <= $3::timestamptz)
  AND ($4::bigint = 0 OR id < $4::bigint)
ORDER BY id DESC
LIMIT $5::int
`

type ListReconcileScanCursorChangesParams struct {
	CheckName string    `json:"check_name"`
	Since     time.Time `json:"since"`
	Until     time.Time `json:"until"`
	CursorID  int64     `json:"cursor_id"`
	PageLimit int32     `json:"page_limit"`
}

// Every write to a reconciliation scan cursor. Migration 010's header records
// what this is for: forging after_holder makes the next scan see zero rows and
// report Complete=true, and the DB layer's answer to that was detection, not
// prevention -- which needs a reader to be detection at all.
// check_name ” means "every check".
func (q *Queries) ListReconcileScanCursorChanges(ctx context.Context, arg ListReconcileScanCursorChangesParams) ([]ReconcileScanCursorChange, error) {
	rows, err := q.db.Query(ctx, listReconcileScanCursorChanges,
		arg.CheckName,
		arg.Since,
		arg.Until,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileScanCursorChange{}
	for rows.Next() {
		var i ReconcileScanCursorChange
		if err := rows.Scan(
			&i.ID,
			&i.CheckName,
			&i.OldAfterHolder,
			&i.OldAfterCurrency,
			&i.OldLapDirty,
			&i.NewAfterHolder,
			&i.NewAfterCurrency,
			&i.NewLapDirty,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.OldLapScanned,
			&i.NewLapScanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
