// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposit_reorgs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOpenDepositReorg = `-- name: GetOpenDepositReorg :one
SELECT id, uid, kind, booking_uid, chain_id, tx_hash, journal_uid, detected_at, last_seen_at, resolved_at, resolution FROM deposit_reorgs
WHERE booking_uid = $1 AND kind = $2 AND resolved_at <= 'epoch'
`

type GetOpenDepositReorgParams struct {
	BookingUid pgtype.UUID `json:"booking_uid"`
	Kind       string      `json:"kind"`
}

func (q *Queries) GetOpenDepositReorg(ctx context.Context, arg GetOpenDepositReorgParams) (DepositReorg, error) {
	row := q.db.QueryRow(ctx, getOpenDepositReorg, arg.BookingUid, arg.Kind)
	var i DepositReorg
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Kind,
		&i.BookingUid,
		&i.ChainID,
		&i.TxHash,
		&i.JournalUid,
		&i.DetectedAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const listOpenDepositReorgs = `-- name: ListOpenDepositReorgs :many
SELECT id, uid, kind, booking_uid, chain_id, tx_hash, journal_uid, detected_at, last_seen_at, resolved_at, resolution FROM deposit_reorgs
WHERE resolved_at <= 'epoch'
ORDER BY id ASC
LIMIT $1
`

// Oldest first: the on-call queue is worked front to back (RUNBOOK §12).
func (q *Queries) ListOpenDepositReorgs(ctx context.Context, limit int32) ([]DepositReorg, error) {
	rows, err := q.db.Query(ctx, listOpenDepositReorgs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositReorg{}
	for rows.Next() {
		var i DepositReorg
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.Kind,
			&i.BookingUid,
			&i.ChainID,
			&i.TxHash,
			&i.JournalUid,
			&i.DetectedAt,
			&i.LastSeenAt,
			&i.ResolvedAt,
			&i.Resolution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordDepositReorg = `-- name: RecordDepositReorg :one
INSERT INTO deposit_reorgs (uid, kind, booking_uid, chain_id, tx_hash, journal_uid)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (booking_uid, kind) DO UPDATE SET
    last_seen_at = now()
RETURNING id, uid, kind, booking_uid, chain_id, tx_hash, journal_uid, detected_at, last_seen_at, resolved_at, resolution
`

type RecordDepositReorgParams struct {
	Uid        pgtype.UUID `json:"uid"`
	Kind       string      `json:"kind"`
	BookingUid pgtype.UUID `json:"booking_uid"`
	ChainID    int64       `json:"chain_id"`
	TxHash     string      `json:"tx_hash"`
	JournalUid string      `json:"journal_uid"`
}

// Upsert on (booking_uid, kind): the first detection opens the row, every
// later detection only bumps last_seen_at, so "still observable on chain"
// and "first noticed at" stay separate facts. Deliberately does NOT clear
// resolved_at -- reopening a closed-out anomaly is an operator decision, not
// something a recheck tick may do behind their back.
func (q *Queries) RecordDepositReorg(ctx context.Context, arg RecordDepositReorgParams) (DepositReorg, error) {
	row := q.db.QueryRow(ctx, recordDepositReorg,
		arg.Uid,
		arg.Kind,
		arg.BookingUid,
		arg.ChainID,
		arg.TxHash,
		arg.JournalUid,
	)
	var i DepositReorg
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Kind,
		&i.BookingUid,
		&i.ChainID,
		&i.TxHash,
		&i.JournalUid,
		&i.DetectedAt,
		&i.LastSeenAt,
		&i.ResolvedAt,
		&i.Resolution,
	)
	return i, err
}

const resolveDepositReorg = `-- name: ResolveDepositReorg :execrows
UPDATE deposit_reorgs
SET resolved_at = now(), resolution = $3
WHERE booking_uid = $1 AND kind = $2 AND resolved_at <= 'epoch'
`

type ResolveDepositReorgParams struct {
	BookingUid pgtype.UUID `json:"booking_uid"`
	Kind       string      `json:"kind"`
	Resolution string      `json:"resolution"`
}

// Closing out is idempotent by being conditional on the row still being
// open: a second resolve affects zero rows instead of overwriting the first
// operator's timestamp and note.
func (q *Queries) ResolveDepositReorg(ctx context.Context, arg ResolveDepositReorgParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveDepositReorg, arg.BookingUid, arg.Kind, arg.Resolution)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
