// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deposits.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDeposit = `-- name: GetDeposit :one
SELECT id, account_holder, currency_id, expected_amount, actual_amount, status, channel_name, channel_ref, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
FROM deposits WHERE id = $1
`

func (q *Queries) GetDeposit(ctx context.Context, id int64) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDeposit, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ExpectedAmount,
		&i.ActualAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositByChannelRef = `-- name: GetDepositByChannelRef :one
SELECT id, account_holder, currency_id, expected_amount, actual_amount, status, channel_name, channel_ref, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
FROM deposits WHERE channel_ref = $1
`

func (q *Queries) GetDepositByChannelRef(ctx context.Context, channelRef pgtype.Text) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositByChannelRef, channelRef)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ExpectedAmount,
		&i.ActualAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepositForUpdate = `-- name: GetDepositForUpdate :one
SELECT id, account_holder, currency_id, expected_amount, actual_amount, status, channel_name, channel_ref, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
FROM deposits WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetDepositForUpdate(ctx context.Context, id int64) (Deposit, error) {
	row := q.db.QueryRow(ctx, getDepositForUpdate, id)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ExpectedAmount,
		&i.ActualAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDeposit = `-- name: InsertDeposit :one
INSERT INTO deposits (account_holder, currency_id, expected_amount, channel_name, idempotency_key, metadata, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, account_holder, currency_id, expected_amount, actual_amount, status, channel_name, channel_ref, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
`

type InsertDepositParams struct {
	AccountHolder  int64              `json:"account_holder"`
	CurrencyID     int64              `json:"currency_id"`
	ExpectedAmount pgtype.Numeric     `json:"expected_amount"`
	ChannelName    string             `json:"channel_name"`
	IdempotencyKey string             `json:"idempotency_key"`
	Metadata       []byte             `json:"metadata"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertDeposit(ctx context.Context, arg InsertDepositParams) (Deposit, error) {
	row := q.db.QueryRow(ctx, insertDeposit,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ExpectedAmount,
		arg.ChannelName,
		arg.IdempotencyKey,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ExpectedAmount,
		&i.ActualAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDepositsByAccount = `-- name: ListDepositsByAccount :many
SELECT id, account_holder, currency_id, expected_amount, actual_amount, status, channel_name, channel_ref, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
FROM deposits
WHERE account_holder = $1
ORDER BY created_at DESC
LIMIT $2::int
`

type ListDepositsByAccountParams struct {
	AccountHolder int64 `json:"account_holder"`
	PageLimit     int32 `json:"page_limit"`
}

func (q *Queries) ListDepositsByAccount(ctx context.Context, arg ListDepositsByAccountParams) ([]Deposit, error) {
	rows, err := q.db.Query(ctx, listDepositsByAccount, arg.AccountHolder, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Deposit{}
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ExpectedAmount,
			&i.ActualAmount,
			&i.Status,
			&i.ChannelName,
			&i.ChannelRef,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepositConfirm = `-- name: UpdateDepositConfirm :exec
UPDATE deposits SET status = 'confirmed', actual_amount = $2, channel_ref = $3, journal_id = $4, updated_at = now() WHERE id = $1
`

type UpdateDepositConfirmParams struct {
	ID           int64          `json:"id"`
	ActualAmount pgtype.Numeric `json:"actual_amount"`
	ChannelRef   pgtype.Text    `json:"channel_ref"`
	JournalID    pgtype.Int8    `json:"journal_id"`
}

func (q *Queries) UpdateDepositConfirm(ctx context.Context, arg UpdateDepositConfirmParams) error {
	_, err := q.db.Exec(ctx, updateDepositConfirm,
		arg.ID,
		arg.ActualAmount,
		arg.ChannelRef,
		arg.JournalID,
	)
	return err
}

const updateDepositConfirming = `-- name: UpdateDepositConfirming :exec
UPDATE deposits SET status = 'confirming', channel_ref = $2, updated_at = now() WHERE id = $1
`

type UpdateDepositConfirmingParams struct {
	ID         int64       `json:"id"`
	ChannelRef pgtype.Text `json:"channel_ref"`
}

func (q *Queries) UpdateDepositConfirming(ctx context.Context, arg UpdateDepositConfirmingParams) error {
	_, err := q.db.Exec(ctx, updateDepositConfirming, arg.ID, arg.ChannelRef)
	return err
}

const updateDepositStatus = `-- name: UpdateDepositStatus :exec
UPDATE deposits SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateDepositStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDepositStatus(ctx context.Context, arg UpdateDepositStatusParams) error {
	_, err := q.db.Exec(ctx, updateDepositStatus, arg.ID, arg.Status)
	return err
}
