// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deposit_addresses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDepositAddressByAddress = `-- name: GetDepositAddressByAddress :one
SELECT id, uid, account_holder, address, factory, init_hash, created_at FROM deposit_addresses WHERE address = $1
`

// Reverse lookup used by the watcher/ingestion path (observed `to` address ->
// holder). address must be passed in the same canonical EIP-55 casing the
// row was written with (see migration 039's index comment).
func (q *Queries) GetDepositAddressByAddress(ctx context.Context, address string) (DepositAddress, error) {
	row := q.db.QueryRow(ctx, getDepositAddressByAddress, address)
	var i DepositAddress
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AccountHolder,
		&i.Address,
		&i.Factory,
		&i.InitHash,
		&i.CreatedAt,
	)
	return i, err
}

const getDepositAddressByHolder = `-- name: GetDepositAddressByHolder :one
SELECT id, uid, account_holder, address, factory, init_hash, created_at FROM deposit_addresses WHERE account_holder = $1
`

func (q *Queries) GetDepositAddressByHolder(ctx context.Context, accountHolder int64) (DepositAddress, error) {
	row := q.db.QueryRow(ctx, getDepositAddressByHolder, accountHolder)
	var i DepositAddress
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AccountHolder,
		&i.Address,
		&i.Factory,
		&i.InitHash,
		&i.CreatedAt,
	)
	return i, err
}

const listDepositAddresses = `-- name: ListDepositAddresses :many
SELECT id, uid, account_holder, address, factory, init_hash, created_at FROM deposit_addresses ORDER BY id
`

// Feeds the watcher's `to ∈ registry` filter set. Unbounded on purpose (this
// period): the registry is expected to stay small enough to hold in memory;
// revisit with pagination if that assumption breaks.
func (q *Queries) ListDepositAddresses(ctx context.Context) ([]DepositAddress, error) {
	rows, err := q.db.Query(ctx, listDepositAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DepositAddress{}
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AccountHolder,
			&i.Address,
			&i.Factory,
			&i.InitHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDepositAddress = `-- name: UpsertDepositAddress :one
INSERT INTO deposit_addresses (uid, account_holder, address, factory, init_hash)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_holder) DO UPDATE SET account_holder = EXCLUDED.account_holder
RETURNING id, uid, account_holder, address, factory, init_hash, created_at
`

type UpsertDepositAddressParams struct {
	Uid           pgtype.UUID `json:"uid"`
	AccountHolder int64       `json:"account_holder"`
	Address       string      `json:"address"`
	Factory       string      `json:"factory"`
	InitHash      string      `json:"init_hash"`
}

// Idempotent registration: account_holder is UNIQUE, so a second call for a
// holder that already has a row is a no-op that returns the existing row
// unchanged (the "DO UPDATE SET col = col" trick, since plain DO NOTHING
// would make RETURNING yield no row on conflict). Callers must not pass a
// different address/factory/init_hash for an already-registered holder --
// this query does not detect or reject that mismatch; it silently keeps the
// original row.
func (q *Queries) UpsertDepositAddress(ctx context.Context, arg UpsertDepositAddressParams) (DepositAddress, error) {
	row := q.db.QueryRow(ctx, upsertDepositAddress,
		arg.Uid,
		arg.AccountHolder,
		arg.Address,
		arg.Factory,
		arg.InitHash,
	)
	var i DepositAddress
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.AccountHolder,
		&i.Address,
		&i.Factory,
		&i.InitHash,
		&i.CreatedAt,
	)
	return i, err
}
