// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dim_active.sql

package sqlcgen

import (
	"context"
)

const inactiveDims = `-- name: InactiveDims :many
SELECT kind, code FROM (
    SELECT 'currency'::text AS kind, code
    FROM currencies
    WHERE id = ANY($1::bigint[]) AND is_active = false
    UNION ALL
    SELECT 'classification'::text AS kind, code
    FROM classifications
    WHERE id = ANY($2::bigint[]) AND is_active = false
    UNION ALL
    SELECT 'journal type'::text AS kind, code
    FROM journal_types
    WHERE id = ANY($3::bigint[]) AND is_active = false
) inactive
ORDER BY kind, code
`

type InactiveDimsParams struct {
	CurrencyIds       []int64 `json:"currency_ids"`
	ClassificationIds []int64 `json:"classification_ids"`
	JournalTypeIds    []int64 `json:"journal_type_ids"`
}

type InactiveDimsRow struct {
	Kind string `json:"kind"`
	Code string `json:"code"`
}

// Reports which of the given dimension ids are soft-deleted (is_active =
// false). One round trip for all three dimensions; the write path calls this
// once per journal, after resolving uids to ids.
//
// Not folded into the dims cache: is_active is the one mutable column on
// these tables and is deliberately NOT cached (see postgres/dims.go), so
// this has to be a read. It is also why the check cannot be a foreign key or
// a CHECK constraint -- both would have to fire on the classifications /
// currencies / journal_types row, not on the journal referencing it.
//
// Deactivation is a soft delete: 001_baseline's comment on these tables says
// so explicitly ("is_active is a soft delete that hides a row from
// pickers"), and journal_entries keeps its foreign keys forever. What was
// missing is the other half of "hides a row from pickers" -- nothing
// actually refused to use one. entry_templates.is_active was enforced
// (core.EntryTemplate.Render); these three were not, which made
// DeactivateCurrency / DeactivateClassification / DeactivateJournalType
// silent no-ops as far as the money path was concerned.
func (q *Queries) InactiveDims(ctx context.Context, arg InactiveDimsParams) ([]InactiveDimsRow, error) {
	rows, err := q.db.Query(ctx, inactiveDims, arg.CurrencyIds, arg.ClassificationIds, arg.JournalTypeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InactiveDimsRow{}
	for rows.Next() {
		var i InactiveDimsRow
		if err := rows.Scan(&i.Kind, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
