// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEvent = `-- name: GetEvent :one
SELECT id, classification_code, booking_id, account_holder, currency_id, from_status, to_status, amount, settled_amount, journal_id, metadata, occurred_at, delivery_status, attempts, max_attempts, next_attempt_at, delivered_at, created_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClassificationCode,
		&i.BookingID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Amount,
		&i.SettledAmount,
		&i.JournalID,
		&i.Metadata,
		&i.OccurredAt,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestEventForBooking = `-- name: GetLatestEventForBooking :one
SELECT id, classification_code, booking_id, account_holder, currency_id, from_status, to_status, amount, settled_amount, journal_id, metadata, occurred_at, delivery_status, attempts, max_attempts, next_attempt_at, delivered_at, created_at FROM events
WHERE booking_id = $1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) GetLatestEventForBooking(ctx context.Context, bookingID int64) (Event, error) {
	row := q.db.QueryRow(ctx, getLatestEventForBooking, bookingID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClassificationCode,
		&i.BookingID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Amount,
		&i.SettledAmount,
		&i.JournalID,
		&i.Metadata,
		&i.OccurredAt,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingEvents = `-- name: GetPendingEvents :many
WITH claimed AS (
    SELECT id
    FROM events
    WHERE delivery_status = 'pending'
      AND next_attempt_at <= now()
    ORDER BY next_attempt_at, id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE events AS e
SET next_attempt_at = $2
FROM claimed
WHERE e.id = claimed.id
RETURNING e.id, e.classification_code, e.booking_id, e.account_holder, e.currency_id, e.from_status, e.to_status, e.amount, e.settled_amount, e.journal_id, e.metadata, e.occurred_at, e.delivery_status, e.attempts, e.max_attempts, e.next_attempt_at, e.delivered_at, e.created_at
`

type GetPendingEventsParams struct {
	Limit         int32     `json:"limit"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

func (q *Queries) GetPendingEvents(ctx context.Context, arg GetPendingEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getPendingEvents, arg.Limit, arg.NextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationCode,
			&i.BookingID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Amount,
			&i.SettledAmount,
			&i.JournalID,
			&i.Metadata,
			&i.OccurredAt,
			&i.DeliveryStatus,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (
    classification_code, booking_id, account_holder, currency_id,
    from_status, to_status, amount, settled_amount, journal_id,
    metadata, occurred_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, classification_code, booking_id, account_holder, currency_id, from_status, to_status, amount, settled_amount, journal_id, metadata, occurred_at, delivery_status, attempts, max_attempts, next_attempt_at, delivered_at, created_at
`

type InsertEventParams struct {
	ClassificationCode string         `json:"classification_code"`
	BookingID          int64          `json:"booking_id"`
	AccountHolder      int64          `json:"account_holder"`
	CurrencyID         int64          `json:"currency_id"`
	FromStatus         string         `json:"from_status"`
	ToStatus           string         `json:"to_status"`
	Amount             pgtype.Numeric `json:"amount"`
	SettledAmount      pgtype.Numeric `json:"settled_amount"`
	JournalID          pgtype.Int8    `json:"journal_id"`
	Metadata           []byte         `json:"metadata"`
	OccurredAt         time.Time      `json:"occurred_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ClassificationCode,
		arg.BookingID,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Amount,
		arg.SettledAmount,
		arg.JournalID,
		arg.Metadata,
		arg.OccurredAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.ClassificationCode,
		&i.BookingID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.FromStatus,
		&i.ToStatus,
		&i.Amount,
		&i.SettledAmount,
		&i.JournalID,
		&i.Metadata,
		&i.OccurredAt,
		&i.DeliveryStatus,
		&i.Attempts,
		&i.MaxAttempts,
		&i.NextAttemptAt,
		&i.DeliveredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByFilter = `-- name: ListEventsByFilter :many
SELECT id, classification_code, booking_id, account_holder, currency_id, from_status, to_status, amount, settled_amount, journal_id, metadata, occurred_at, delivery_status, attempts, max_attempts, next_attempt_at, delivered_at, created_at FROM events
WHERE (classification_code = $1 OR $1 = '')
  AND (booking_id = $2 OR $2 = 0)
  AND (to_status = $3 OR $3 = '')
  AND id > $4
ORDER BY id
LIMIT $5
`

type ListEventsByFilterParams struct {
	ClassificationCode string `json:"classification_code"`
	BookingID          int64  `json:"booking_id"`
	ToStatus           string `json:"to_status"`
	ID                 int64  `json:"id"`
	Limit              int32  `json:"limit"`
}

func (q *Queries) ListEventsByFilter(ctx context.Context, arg ListEventsByFilterParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByFilter,
		arg.ClassificationCode,
		arg.BookingID,
		arg.ToStatus,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationCode,
			&i.BookingID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.FromStatus,
			&i.ToStatus,
			&i.Amount,
			&i.SettledAmount,
			&i.JournalID,
			&i.Metadata,
			&i.OccurredAt,
			&i.DeliveryStatus,
			&i.Attempts,
			&i.MaxAttempts,
			&i.NextAttemptAt,
			&i.DeliveredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventDead = `-- name: UpdateEventDead :exec
UPDATE events
SET delivery_status = 'dead'
WHERE id = $1
`

func (q *Queries) UpdateEventDead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateEventDead, id)
	return err
}

const updateEventDelivered = `-- name: UpdateEventDelivered :exec
UPDATE events
SET delivery_status = 'delivered', delivered_at = now()
WHERE id = $1
`

func (q *Queries) UpdateEventDelivered(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateEventDelivered, id)
	return err
}

const updateEventRetry = `-- name: UpdateEventRetry :exec
UPDATE events
SET attempts = attempts + 1,
    delivery_status = CASE
        WHEN attempts + 1 >= max_attempts THEN 'dead'
        ELSE 'pending'
    END,
    next_attempt_at = CASE
        WHEN attempts + 1 >= max_attempts THEN next_attempt_at
        ELSE $2
    END
WHERE id = $1
`

type UpdateEventRetryParams struct {
	ID            int64     `json:"id"`
	NextAttemptAt time.Time `json:"next_attempt_at"`
}

func (q *Queries) UpdateEventRetry(ctx context.Context, arg UpdateEventRetryParams) error {
	_, err := q.db.Exec(ctx, updateEventRetry, arg.ID, arg.NextAttemptAt)
	return err
}
