// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest_dead_letters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertIngestDeadLetter = `-- name: InsertIngestDeadLetter :one
INSERT INTO ingest_dead_letters (uid, chain_id, tx_hash, txlog_seq, idempotency_key, reason, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, uid, chain_id, tx_hash, txlog_seq, idempotency_key, reason, payload, created_at
`

type InsertIngestDeadLetterParams struct {
	Uid            pgtype.UUID `json:"uid"`
	ChainID        int64       `json:"chain_id"`
	TxHash         string      `json:"tx_hash"`
	TxlogSeq       int32       `json:"txlog_seq"`
	IdempotencyKey string      `json:"idempotency_key"`
	Reason         string      `json:"reason"`
	Payload        []byte      `json:"payload"`
}

// Idempotent on idempotency_key: a repeated conflict on the same sighting
// (e.g. the watcher retrying it every scan) is not a new alert -- ON CONFLICT
// DO NOTHING means callers may get zero rows back (see IngestDeadLetterStore,
// which treats pgx.ErrNoRows here as "already recorded", not an error).
func (q *Queries) InsertIngestDeadLetter(ctx context.Context, arg InsertIngestDeadLetterParams) (IngestDeadLetter, error) {
	row := q.db.QueryRow(ctx, insertIngestDeadLetter,
		arg.Uid,
		arg.ChainID,
		arg.TxHash,
		arg.TxlogSeq,
		arg.IdempotencyKey,
		arg.Reason,
		arg.Payload,
	)
	var i IngestDeadLetter
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.ChainID,
		&i.TxHash,
		&i.TxlogSeq,
		&i.IdempotencyKey,
		&i.Reason,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listIngestDeadLetters = `-- name: ListIngestDeadLetters :many
SELECT id, uid, chain_id, tx_hash, txlog_seq, idempotency_key, reason, payload, created_at FROM ingest_dead_letters ORDER BY id DESC LIMIT $1
`

// Newest first, for on-call triage (RUNBOOK). Unbounded scope is not
// expected -- ErrConflict should be rare; limit guards against a runaway
// normalization bug flooding an operator's terminal.
func (q *Queries) ListIngestDeadLetters(ctx context.Context, limit int32) ([]IngestDeadLetter, error) {
	rows, err := q.db.Query(ctx, listIngestDeadLetters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngestDeadLetter{}
	for rows.Next() {
		var i IngestDeadLetter
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.ChainID,
			&i.TxHash,
			&i.TxlogSeq,
			&i.IdempotencyKey,
			&i.Reason,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
