// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrity_auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJournalAuthByUID = `-- name: GetJournalAuthByUID :one

SELECT uid, journal_type_id, idempotency_key, actor_id, source, reversal_of,
       event_id, effective_at, auth_digest, auth_signature, auth_key_id
FROM journals
WHERE uid = $1
`

type GetJournalAuthByUIDRow struct {
	Uid            pgtype.UUID `json:"uid"`
	JournalTypeID  int64       `json:"journal_type_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	ActorID        int64       `json:"actor_id"`
	Source         string      `json:"source"`
	ReversalOf     pgtype.Int8 `json:"reversal_of"`
	EventID        pgtype.Int8 `json:"event_id"`
	EffectiveAt    time.Time   `json:"effective_at"`
	AuthDigest     []byte      `json:"auth_digest"`
	AuthSignature  []byte      `json:"auth_signature"`
	AuthKeyID      string      `json:"auth_key_id"`
}

// P5 (per-journal authorization signing) reads. See
// docs/plans/2026-08-21-integrity-hardening-contracts.md §3 -- this file is
// exclusively owned by P5; new P5 queries land here, not in journals.sql.
// Returns the stored signature material for a journal, keyed by its
// external uid. Used by core.VerifyJournalAuth-based checks (pin tests
// today; a future withdrawal gate / reconcile check / ledger-cli verify are
// explicitly NOT wired by this phase, design doc §7.3/§7.4/§12).
func (q *Queries) GetJournalAuthByUID(ctx context.Context, uid pgtype.UUID) (GetJournalAuthByUIDRow, error) {
	row := q.db.QueryRow(ctx, getJournalAuthByUID, uid)
	var i GetJournalAuthByUIDRow
	err := row.Scan(
		&i.Uid,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.EventID,
		&i.EffectiveAt,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
	)
	return i, err
}
