// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrity_attested_auth.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listContributingEntryVerdicts = `-- name: ListContributingEntryVerdicts :many
SELECT je.id AS entry_id, je.journal_id,
       COALESCE(ea.auth_verdict, '') AS verdict
FROM journal_entries je
LEFT JOIN entry_attestations ea ON ea.entry_id = je.id
WHERE je.account_holder = $1::bigint
  AND je.currency_id = $2::bigint
  AND je.classification_id = $3::bigint
`

type ListContributingEntryVerdictsParams struct {
	AccountHolder    int64 `json:"account_holder"`
	CurrencyID       int64 `json:"currency_id"`
	ClassificationID int64 `json:"classification_id"`
}

type ListContributingEntryVerdictsRow struct {
	EntryID   int64  `json:"entry_id"`
	JournalID int64  `json:"journal_id"`
	Verdict   string `json:"verdict"`
}

// Every entry contributing to (account_holder, currency_id,
// classification_id), alongside its cached T4 attestation verdict if one
// exists. ” (core.JournalAuthVerdictUnknown) means either "not yet
// attested" (the tail -- entry_attestations has no row for this entry_id)
// or "attested before migration 054 existed" -- postgres.VerifiedBalanceStore
// treats both identically: fall back to a live core.VerifyJournalAuth for
// that entry's journal, exactly as if T4 did not exist (fail-closed, never
// silently treated as authorized). Reuses idx_entries_account_id, the same
// index integrity_verified_balance.sql's ListContributingJournalIDs already
// relies on.
func (q *Queries) ListContributingEntryVerdicts(ctx context.Context, arg ListContributingEntryVerdictsParams) ([]ListContributingEntryVerdictsRow, error) {
	rows, err := q.db.Query(ctx, listContributingEntryVerdicts, arg.AccountHolder, arg.CurrencyID, arg.ClassificationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContributingEntryVerdictsRow{}
	for rows.Next() {
		var i ListContributingEntryVerdictsRow
		if err := rows.Scan(&i.EntryID, &i.JournalID, &i.Verdict); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesForJournals = `-- name: ListEntriesForJournals :many
SELECT id, journal_id, account_holder, currency_id, classification_id, entry_type, amount, effective_at
FROM journal_entries
WHERE journal_id = ANY($1::bigint[])
ORDER BY journal_id, id
`

type ListEntriesForJournalsRow struct {
	ID               int64          `json:"id"`
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
	EffectiveAt      time.Time      `json:"effective_at"`
}

// Every journal_entries row for any of journal_ids, in one round trip --
// the second half of the batched fetch ListJournalsForAuthCheck starts
// (design doc §4.5). Ordered by journal_id so the caller can group rows by
// journal without a map lookup per row; callers must not assume any
// particular id order WITHIN one journal's group beyond that.
func (q *Queries) ListEntriesForJournals(ctx context.Context, journalIds []int64) ([]ListEntriesForJournalsRow, error) {
	rows, err := q.db.Query(ctx, listEntriesForJournals, journalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesForJournalsRow{}
	for rows.Next() {
		var i ListEntriesForJournalsRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.EntryType,
			&i.Amount,
			&i.EffectiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsForAuthCheck = `-- name: ListJournalsForAuthCheck :many

SELECT
    j.id,
    j.uid,
    jt.uid AS journal_type_uid,
    j.idempotency_key,
    j.actor_id,
    j.source,
    rev.uid AS reversal_of_uid,
    j.effective_at,
    j.auth_digest,
    j.auth_signature,
    j.auth_key_id,
    j.auth_status
FROM journals j
JOIN journal_types jt ON jt.id = j.journal_type_id
LEFT JOIN journals rev ON rev.id = j.reversal_of
WHERE j.id = ANY($1::bigint[])
`

type ListJournalsForAuthCheckRow struct {
	ID             int64       `json:"id"`
	Uid            pgtype.UUID `json:"uid"`
	JournalTypeUid pgtype.UUID `json:"journal_type_uid"`
	IdempotencyKey string      `json:"idempotency_key"`
	ActorID        int64       `json:"actor_id"`
	Source         string      `json:"source"`
	ReversalOfUid  pgtype.UUID `json:"reversal_of_uid"`
	EffectiveAt    time.Time   `json:"effective_at"`
	AuthDigest     []byte      `json:"auth_digest"`
	AuthSignature  []byte      `json:"auth_signature"`
	AuthKeyID      string      `json:"auth_key_id"`
	AuthStatus     string      `json:"auth_status"`
}

// T4 of the integrity-hardening wave (docs/plans/2026-08-21-integrity-hardening-contracts.md
// §W3-0/§W3-B, docs/plans/2026-08-21-tamper-evident-ledger-design.md §8
// extended). This file is exclusively owned by T4. It does NOT include the
// ledger_attestations/entry_attestations INSERT queries -- those are
// P6's existing InsertLedgerAttestation / InsertEntryAttestations in
// integrity_attestations.sql, extended in place (the same way migration
// 048/P7 extended them for merkle_root/leaf_hash) rather than duplicated
// here.
// Batch-fetches everything core.VerifyJournalAuth needs to reconstruct a
// journal's uid-space core.JournalInput, for every id in journal_ids, in
// one round trip (design doc §4.5's batched-fetch recommendation). The
// naive VerifiedBalanceReader path measured in
// .local/bench-verify-2026-08-23.md pays one journals-JOIN-journal_entries
// round trip PER journal; this query (paired with
// ListEntriesForJournals below) pays it once per attestation batch or once
// per ledger-cli verify pass instead.
//
// reversal_of resolves to its uid via a self-join (NULL for an original,
// non-reversal journal) -- core.CanonicalJournalDigest needs
// input.ReversalOfUID, never the internal id (design doc §7.2). event_id is
// deliberately NOT selected: CanonicalJournalDigest never covers it
// (core/auth.go's authDigestDomain doc comment) -- resolving it here would
// only invite a caller to assume otherwise.
func (q *Queries) ListJournalsForAuthCheck(ctx context.Context, journalIds []int64) ([]ListJournalsForAuthCheckRow, error) {
	rows, err := q.db.Query(ctx, listJournalsForAuthCheck, journalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalsForAuthCheckRow{}
	for rows.Next() {
		var i ListJournalsForAuthCheckRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.JournalTypeUid,
			&i.IdempotencyKey,
			&i.ActorID,
			&i.Source,
			&i.ReversalOfUid,
			&i.EffectiveAt,
			&i.AuthDigest,
			&i.AuthSignature,
			&i.AuthKeyID,
			&i.AuthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
