// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: journals.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireBalanceLock = `-- name: AcquireBalanceLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('bal:' || $1::text, 0))
`

// Take a transaction-scoped advisory lock keyed on (holder, currency_id) so
// concurrent reserves and journal posts that touch the same pair serialize.
// The caller passes a stable composite text key (e.g. "balance:<holder>:<currency_id>").
//
// Single-key form pg_advisory_xact_lock(bigint), hashed through
// hashtextextended(text, seed) (returns the full 64-bit range) rather than
// hashtext() (32-bit int4). An earlier revision of this query used the
// two-key form pg_advisory_xact_lock(1::int4, hashtext(key)) to get
// namespace separation from AcquireIdempotencyLock below "for free" via
// PostgreSQL's disjoint two-key lock-tag space -- but that traded the
// 64-bit hash range for a 32-bit one, and a 32-bit hashtext() collision
// between two DIFFERENT (holder, currency_id) pairs is reachable at
// realistic account cardinalities. Because the batch-level defense
// (sortedUniquePairs in ledger_store.go) only sorts a SINGLE transaction's
// own pairs by (holder, currency_id) -- not by the hash the lock is
// actually taken on -- two transactions touching entirely disjoint holder
// sets whose pairs alias the same 32-bit hash could still interleave into
// a genuine ABBA, reintroducing the exact deadlock shape this query's
// namespace separation was meant to close (see M-6, 2026-08-26 independent
// review; postgres/lock_order_test.go's
// TestAcquireBalanceLocks_HashCollisionCrossBatchDeadlock_Fixed
// reproduces a real 40P01 against the 32-bit version using an actual
// hashtext() collision pair, confirmed by running that test before this
// fix was applied).
//
// Namespace separation from AcquireIdempotencyLock is instead carried by a
// literal string prefix baked into the hashed value itself ('bal:' here,
// 'idem:' there) rather than by a second int4 lock-tag field. The prefixes
// differ in their first byte ('b' vs 'i'), so the set of strings this
// query can hash and the set AcquireIdempotencyLock can hash are disjoint
// by construction -- no caller-supplied key (idempotency_key has no
// format restriction; server/handler_journals.go accepts it as-is) can
// pick a value that lands the two namespaces on the same lock, closing
// the same ABBA finding concurrency.md originally raised without
// narrowing the hash width that reopened it.
//
// Residual, accepted risk noted while fixing M-6 (not itself part of that
// finding): the two-key form was ALSO disjoint from every single-key
// pg_advisory_lock/pg_try_advisory_lock caller elsewhere in the codebase
// (service.advisoryLockKey, an FNV-64a hash of a small fixed set of job
// names, used by LockedJob and SnapshotService; postgres/migrate.go's
// clusterMigrationLockKey) via the same lock-tag classid mechanism -- this
// single-key form shares that 64-bit space with them. A job-name hash
// landing on the same value as a live (holder,currency) or idempotency key
// is not attacker-influenceable (job names are fixed constants, not caller
// input), so the worst case is one skipped or delayed lock-wait, never an
// incorrect result. Judged negligible; flagged here rather than silently
// assumed away, and left unmitigated because closing it would mean
// reserving a bit-pattern across both journals.sql and
// service/locked_job.go / service/snapshot.go, outside this fix's file
// scope.
//
// Why a collision cannot deadlock (corrected 2026-09-02, concurrency.md
// B-m3): the reason is NOT "every one of those other callers uses the
// non-blocking pg_try_advisory_lock", which is how this note used to read.
// The load-bearing property is that PostgreSQL scopes advisory locks to the
// DATABASE of the connection holding them -- the same property I-47's entire
// design rests on. postgres/migrate.go's acquireClusterLock deliberately
// connects to the CLUSTER's `postgres` maintenance database, so its key and
// the bal: / idem: / job: keys taken on the application database are not in
// the same lock space at all, whatever their 64-bit values.
//
// The try-variant claim happens to be true again as of 2026-09-02 (B-m4
// changed acquireClusterLock from a blocking session-level
// pg_advisory_lock to a polled pg_try_advisory_lock, and
// postgres.TestNoBlockingSessionAdvisoryLocks now keeps it that way), but it
// was false when it was written, and it is the weaker argument: it holds
// only for as long as nobody adds a blocking session lock. Database scoping
// holds regardless.
//
// Boundary, so the next reader knows where the argument stops: if someone
// installs the ledger schema INTO the cluster's `postgres` maintenance
// database (nothing prevents it), the migration key and these keys do share
// one 64-bit space, and this reasoning has to be redone.
func (q *Queries) AcquireBalanceLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, acquireBalanceLock, key)
	return err
}

const acquireIdempotencyLock = `-- name: AcquireIdempotencyLock :exec
SELECT pg_advisory_xact_lock(hashtextextended('idem:' || $1::text, 0))
`

// Serialize concurrent requests that present the same idempotency key, even if
// they touch different account dimensions. See AcquireBalanceLock's comment
// above for why the 'idem:' prefix keeps this namespace disjoint from the
// balance-lock namespace regardless of the key string a caller supplies,
// and why this is a single-key hashtextextended(text, 0) call (full 64-bit
// range) rather than the narrower two-key hashtext() form. Collisions
// within this namespace only reduce concurrency; they do not affect
// correctness.
func (q *Queries) AcquireIdempotencyLock(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, acquireIdempotencyLock, key)
	return err
}

const distinctClassificationsForAccount = `-- name: DistinctClassificationsForAccount :many
SELECT DISTINCT classification_id
FROM journal_entries
WHERE account_holder = $1 AND currency_id = $2
ORDER BY classification_id
`

type DistinctClassificationsForAccountParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

func (q *Queries) DistinctClassificationsForAccount(ctx context.Context, arg DistinctClassificationsForAccountParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, distinctClassificationsForAccount, arg.AccountHolder, arg.CurrencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var classification_id int64
		if err := rows.Scan(&classification_id); err != nil {
			return nil, err
		}
		items = append(items, classification_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJournal = `-- name: GetJournal :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals WHERE id = $1
`

func (q *Queries) GetJournal(ctx context.Context, id int64) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournal, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.EventID,
		&i.EffectiveAt,
		&i.Uid,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
		&i.AuthStatus,
	)
	return i, err
}

const getJournalByIdempotencyKey = `-- name: GetJournalByIdempotencyKey :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals WHERE idempotency_key = $1
`

func (q *Queries) GetJournalByIdempotencyKey(ctx context.Context, idempotencyKey string) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalByIdempotencyKey, idempotencyKey)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.EventID,
		&i.EffectiveAt,
		&i.Uid,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
		&i.AuthStatus,
	)
	return i, err
}

const getJournalByUID = `-- name: GetJournalByUID :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals WHERE uid = $1
`

func (q *Queries) GetJournalByUID(ctx context.Context, uid pgtype.UUID) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalByUID, uid)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.EventID,
		&i.EffectiveAt,
		&i.Uid,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
		&i.AuthStatus,
	)
	return i, err
}

const getJournalForUpdate = `-- name: GetJournalForUpdate :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals WHERE id = $1 FOR UPDATE
`

// Row-locks the original journal for the duration of the caller's
// transaction, serializing concurrent ReverseJournalFraction calls against
// the same journal so their cumulative-reversed-amount checks cannot race.
func (q *Queries) GetJournalForUpdate(ctx context.Context, id int64) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalForUpdate, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.EventID,
		&i.EffectiveAt,
		&i.Uid,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
		&i.AuthStatus,
	)
	return i, err
}

const getJournalForUpdateByUID = `-- name: GetJournalForUpdateByUID :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals WHERE uid = $1 FOR UPDATE
`

func (q *Queries) GetJournalForUpdateByUID(ctx context.Context, uid pgtype.UUID) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalForUpdateByUID, uid)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.EventID,
		&i.EffectiveAt,
		&i.Uid,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
		&i.AuthStatus,
	)
	return i, err
}

const getJournalUIDByID = `-- name: GetJournalUIDByID :one
SELECT uid FROM journals WHERE id = $1
`

func (q *Queries) GetJournalUIDByID(ctx context.Context, id int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getJournalUIDByID, id)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const insertJournal = `-- name: InsertJournal :one
INSERT INTO journals (journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status
`

type InsertJournalParams struct {
	JournalTypeID  int64          `json:"journal_type_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	TotalDebit     pgtype.Numeric `json:"total_debit"`
	TotalCredit    pgtype.Numeric `json:"total_credit"`
	Metadata       []byte         `json:"metadata"`
	ActorID        int64          `json:"actor_id"`
	Source         string         `json:"source"`
	ReversalOf     pgtype.Int8    `json:"reversal_of"`
	EventID        pgtype.Int8    `json:"event_id"`
	EffectiveAt    time.Time      `json:"effective_at"`
	Uid            pgtype.UUID    `json:"uid"`
	AuthDigest     []byte         `json:"auth_digest"`
	AuthSignature  []byte         `json:"auth_signature"`
	AuthKeyID      string         `json:"auth_key_id"`
	AuthStatus     string         `json:"auth_status"`
}

// auth_digest/auth_signature/auth_key_id (migration 046, P5) are empty when
// the caller did not sign this posting. auth_status (migration 051, design
// doc §7.5) always records WHY: 'signed' / 'unsigned_no_attestor' /
// 'unsigned_tx_mode' -- see core.AuthStatus.
func (q *Queries) InsertJournal(ctx context.Context, arg InsertJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, insertJournal,
		arg.JournalTypeID,
		arg.IdempotencyKey,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.Metadata,
		arg.ActorID,
		arg.Source,
		arg.ReversalOf,
		arg.EventID,
		arg.EffectiveAt,
		arg.Uid,
		arg.AuthDigest,
		arg.AuthSignature,
		arg.AuthKeyID,
		arg.AuthStatus,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
		&i.EventID,
		&i.EffectiveAt,
		&i.Uid,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
		&i.AuthStatus,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entries (journal_id, account_holder, currency_id, classification_id, entry_type, amount, effective_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
RETURNING id, journal_id, account_holder, currency_id, classification_id, entry_type, amount, created_at, effective_at
`

type InsertJournalEntryParams struct {
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
	EffectiveAt      time.Time      `json:"effective_at"`
}

// Column order in RETURNING matches the table's physical column order
// (effective_at was appended after created_at in migration 025) so sqlc
// matches the generated row to the JournalEntry model instead of minting a
// distinct one-off row type.
func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.JournalID,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.EntryType,
		arg.Amount,
		arg.EffectiveAt,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ClassificationID,
		&i.EntryType,
		&i.Amount,
		&i.CreatedAt,
		&i.EffectiveAt,
	)
	return i, err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT je.id, je.journal_id, je.account_holder, je.currency_id, je.classification_id, je.entry_type, je.amount, je.created_at, je.effective_at, j.uid AS journal_uid
FROM journal_entries je
JOIN journals j ON j.id = je.journal_id
WHERE je.account_holder = $1 AND je.currency_id = $2
  AND je.id > $3::bigint
ORDER BY je.id ASC
LIMIT $4::int
`

type ListEntriesByAccountParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
	CursorID      int64 `json:"cursor_id"`
	PageLimit     int32 `json:"page_limit"`
}

type ListEntriesByAccountRow struct {
	ID               int64          `json:"id"`
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
	CreatedAt        time.Time      `json:"created_at"`
	EffectiveAt      time.Time      `json:"effective_at"`
	JournalUid       pgtype.UUID    `json:"journal_uid"`
}

// Column order matches the table's physical order (see InsertJournalEntry).
func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]ListEntriesByAccountRow, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntriesByAccountRow{}
	for rows.Next() {
		var i ListEntriesByAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.EntryType,
			&i.Amount,
			&i.CreatedAt,
			&i.EffectiveAt,
			&i.JournalUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT je.id, je.journal_id, je.account_holder, je.currency_id, je.classification_id, je.entry_type, je.amount, je.created_at, je.effective_at, j.uid AS journal_uid
FROM journal_entries je
JOIN journals j ON j.id = je.journal_id
WHERE je.journal_id = $1
ORDER BY je.id
`

type ListJournalEntriesRow struct {
	ID               int64          `json:"id"`
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
	CreatedAt        time.Time      `json:"created_at"`
	EffectiveAt      time.Time      `json:"effective_at"`
	JournalUid       pgtype.UUID    `json:"journal_uid"`
}

// Column order matches the table's physical order (see InsertJournalEntry).
// j.uid rides along so the mapper can emit journal_uid without a per-row lookup.
func (q *Queries) ListJournalEntries(ctx context.Context, journalID int64) ([]ListJournalEntriesRow, error) {
	rows, err := q.db.Query(ctx, listJournalEntries, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalEntriesRow{}
	for rows.Next() {
		var i ListJournalEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.EntryType,
			&i.Amount,
			&i.CreatedAt,
			&i.EffectiveAt,
			&i.JournalUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsCursor = `-- name: ListJournalsCursor :many
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals
WHERE id > $1::bigint
ORDER BY id ASC
LIMIT $2::int
`

type ListJournalsCursorParams struct {
	CursorID  int64 `json:"cursor_id"`
	PageLimit int32 `json:"page_limit"`
}

func (q *Queries) ListJournalsCursor(ctx context.Context, arg ListJournalsCursorParams) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listJournalsCursor, arg.CursorID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
			&i.EffectiveAt,
			&i.Uid,
			&i.AuthDigest,
			&i.AuthSignature,
			&i.AuthKeyID,
			&i.AuthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentJournals = `-- name: ListRecentJournals :many
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals
ORDER BY id DESC
LIMIT $1::int
`

// The NEWEST page_limit journals, newest first -- deliberately a separate
// query from ListJournalsCursor above, which walks ASCENDING from a cursor
// (the audit-pagination shape the HTTP list endpoint needs).
//
// service.VerifyLedger's step 4 samples "the most recent journals" for a
// valid P5 signature (design doc §8.4). Before this query existed it called
// ListJournalsCursor with an empty cursor, i.e. id > 0 ORDER BY id ASC --
// the OLDEST page, which on any ledger with more than page_limit journals
// can never contain a freshly forged row (2026-09-02 audit,
// tamper-evident.md M-1). Sampling has to look where a forgery would land.
//
// No cursor argument: this is a fixed-size head sample, not a paginated
// walk. A caller that needs to page through history uses
// ListJournalsCursor.
func (q *Queries) ListRecentJournals(ctx context.Context, pageLimit int32) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listRecentJournals, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
			&i.EffectiveAt,
			&i.Uid,
			&i.AuthDigest,
			&i.AuthSignature,
			&i.AuthKeyID,
			&i.AuthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReversalEntriesByOriginal = `-- name: ListReversalEntriesByOriginal :many
SELECT je.id, je.journal_id, je.account_holder, je.currency_id, je.classification_id, je.entry_type, je.amount, je.created_at
FROM journal_entries je
JOIN journals j ON j.id = je.journal_id
WHERE j.reversal_of = $1
ORDER BY je.id
`

type ListReversalEntriesByOriginalRow struct {
	ID               int64          `json:"id"`
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
	CreatedAt        time.Time      `json:"created_at"`
}

// All entries across every reversal journal (full or partial) of the given
// original journal. Used to compute the cumulative amount already reversed
// per (holder, currency, classification, original entry_type) dimension
// before allowing another partial reversal.
func (q *Queries) ListReversalEntriesByOriginal(ctx context.Context, reversalOf pgtype.Int8) ([]ListReversalEntriesByOriginalRow, error) {
	rows, err := q.db.Query(ctx, listReversalEntriesByOriginal, reversalOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReversalEntriesByOriginalRow{}
	for rows.Next() {
		var i ListReversalEntriesByOriginalRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.EntryType,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReversalsByOriginalJournalID = `-- name: ListReversalsByOriginalJournalID :many
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at, event_id, effective_at, uid, auth_digest, auth_signature, auth_key_id, auth_status FROM journals WHERE reversal_of = $1 ORDER BY id
`

// A journal may now have more than one reversal (partial reversals), so this
// returns all of them, oldest first. Replaces the old GetReversalByOriginalJournalID
// :one query, which silently returned an arbitrary single row once multiple
// reversals became possible.
func (q *Queries) ListReversalsByOriginalJournalID(ctx context.Context, reversalOf pgtype.Int8) ([]Journal, error) {
	rows, err := q.db.Query(ctx, listReversalsByOriginalJournalID, reversalOf)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Journal{}
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.JournalTypeID,
			&i.IdempotencyKey,
			&i.TotalDebit,
			&i.TotalCredit,
			&i.Metadata,
			&i.ActorID,
			&i.Source,
			&i.ReversalOf,
			&i.CreatedAt,
			&i.EventID,
			&i.EffectiveAt,
			&i.Uid,
			&i.AuthDigest,
			&i.AuthSignature,
			&i.AuthKeyID,
			&i.AuthStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEntriesByAccountClassification = `-- name: SumEntriesByAccountClassification :many
SELECT
  je.classification_id,
  je.entry_type,
  COALESCE(SUM(je.amount), 0) as total
FROM journal_entries je
JOIN balance_checkpoints cp
  ON cp.account_holder = je.account_holder
 AND cp.currency_id = je.currency_id
 AND cp.classification_id = je.classification_id
WHERE je.account_holder = $1
  AND je.currency_id = $2
  AND je.id <= cp.last_entry_id
GROUP BY je.classification_id, je.entry_type
`

type SumEntriesByAccountClassificationParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

type SumEntriesByAccountClassificationRow struct {
	ClassificationID int64       `json:"classification_id"`
	EntryType        string      `json:"entry_type"`
	Total            interface{} `json:"total"`
}

// Reconcile Check#2 comparison basis: each classification's entries are
// bounded by that classification's OWN checkpoint watermark
// (je.id <= cp.last_entry_id), so checkpoint.balance vs this sum is an exact
// invariant regardless of in-flight rollups. An unbounded sum would flag
// every account with unmaterialized entries as "drift" — permanent false
// positives on high-frequency system accounts. Classifications with no
// checkpoint yet are excluded (their checkpoint balance is implicitly zero
// over an empty prefix — nothing to compare).
func (q *Queries) SumEntriesByAccountClassification(ctx context.Context, arg SumEntriesByAccountClassificationParams) ([]SumEntriesByAccountClassificationRow, error) {
	rows, err := q.db.Query(ctx, sumEntriesByAccountClassification, arg.AccountHolder, arg.CurrencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumEntriesByAccountClassificationRow{}
	for rows.Next() {
		var i SumEntriesByAccountClassificationRow
		if err := rows.Scan(&i.ClassificationID, &i.EntryType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEntriesSinceCheckpoint = `-- name: SumEntriesSinceCheckpoint :many
SELECT
  classification_id,
  entry_type,
  COALESCE(SUM(amount), 0) as total
FROM journal_entries
WHERE account_holder = $1
  AND currency_id = $2
  AND id > $3::bigint
GROUP BY classification_id, entry_type
`

type SumEntriesSinceCheckpointParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
	SinceEntryID  int64 `json:"since_entry_id"`
}

type SumEntriesSinceCheckpointRow struct {
	ClassificationID int64       `json:"classification_id"`
	EntryType        string      `json:"entry_type"`
	Total            interface{} `json:"total"`
}

func (q *Queries) SumEntriesSinceCheckpoint(ctx context.Context, arg SumEntriesSinceCheckpointParams) ([]SumEntriesSinceCheckpointRow, error) {
	rows, err := q.db.Query(ctx, sumEntriesSinceCheckpoint, arg.AccountHolder, arg.CurrencyID, arg.SinceEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumEntriesSinceCheckpointRow{}
	for rows.Next() {
		var i SumEntriesSinceCheckpointRow
		if err := rows.Scan(&i.ClassificationID, &i.EntryType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEntriesSinceForClassification = `-- name: SumEntriesSinceForClassification :many
SELECT
  entry_type,
  COALESCE(SUM(amount), 0) as total
FROM journal_entries
WHERE account_holder = $1
  AND currency_id = $2
  AND classification_id = $3
  AND id > $4::bigint
GROUP BY entry_type
`

type SumEntriesSinceForClassificationParams struct {
	AccountHolder    int64 `json:"account_holder"`
	CurrencyID       int64 `json:"currency_id"`
	ClassificationID int64 `json:"classification_id"`
	SinceEntryID     int64 `json:"since_entry_id"`
}

type SumEntriesSinceForClassificationRow struct {
	EntryType string      `json:"entry_type"`
	Total     interface{} `json:"total"`
}

func (q *Queries) SumEntriesSinceForClassification(ctx context.Context, arg SumEntriesSinceForClassificationParams) ([]SumEntriesSinceForClassificationRow, error) {
	rows, err := q.db.Query(ctx, sumEntriesSinceForClassification,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.SinceEntryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumEntriesSinceForClassificationRow{}
	for rows.Next() {
		var i SumEntriesSinceForClassificationRow
		if err := rows.Scan(&i.EntryType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumGlobalDebitCredit = `-- name: SumGlobalDebitCredit :many
SELECT
  entry_type,
  COALESCE(SUM(amount), 0) as total
FROM journal_entries
GROUP BY entry_type
`

type SumGlobalDebitCreditRow struct {
	EntryType string      `json:"entry_type"`
	Total     interface{} `json:"total"`
}

func (q *Queries) SumGlobalDebitCredit(ctx context.Context) ([]SumGlobalDebitCreditRow, error) {
	rows, err := q.db.Query(ctx, sumGlobalDebitCredit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumGlobalDebitCreditRow{}
	for rows.Next() {
		var i SumGlobalDebitCreditRow
		if err := rows.Scan(&i.EntryType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const verifyJournalBalanced = `-- name: VerifyJournalBalanced :one
SELECT currency_id
FROM journal_entries
WHERE journal_id = $1
GROUP BY currency_id
HAVING SUM(CASE WHEN entry_type = 'debit' THEN amount ELSE -amount END) <> 0
LIMIT 1
`

// Returns the first currency_id that does not net to zero across the journal's
// entries, or NULL if the journal is balanced. Run inside the same transaction
// as the entry inserts, before commit, so a failure rolls back cleanly with a
// precise "which currency" error. This is the application-layer half of the
// check; migration 044 restores a DB-layer deferred constraint trigger as the
// backstop for callers that bypass this query (e.g. direct SQL).
func (q *Queries) VerifyJournalBalanced(ctx context.Context, journalID int64) (int64, error) {
	row := q.db.QueryRow(ctx, verifyJournalBalanced, journalID)
	var currency_id int64
	err := row.Scan(&currency_id)
	return currency_id, err
}
