// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journals.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJournal = `-- name: GetJournal :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at
FROM journals
WHERE id = $1
`

func (q *Queries) GetJournal(ctx context.Context, id int64) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournal, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
	)
	return i, err
}

const getJournalByIdempotencyKey = `-- name: GetJournalByIdempotencyKey :one
SELECT id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at
FROM journals
WHERE idempotency_key = $1
`

func (q *Queries) GetJournalByIdempotencyKey(ctx context.Context, idempotencyKey string) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournalByIdempotencyKey, idempotencyKey)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
	)
	return i, err
}

const insertJournal = `-- name: InsertJournal :one
INSERT INTO journals (journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, journal_type_id, idempotency_key, total_debit, total_credit, metadata, actor_id, source, reversal_of, created_at
`

type InsertJournalParams struct {
	JournalTypeID  int64          `json:"journal_type_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	TotalDebit     pgtype.Numeric `json:"total_debit"`
	TotalCredit    pgtype.Numeric `json:"total_credit"`
	Metadata       []byte         `json:"metadata"`
	ActorID        pgtype.Int8    `json:"actor_id"`
	Source         pgtype.Text    `json:"source"`
	ReversalOf     pgtype.Int8    `json:"reversal_of"`
}

func (q *Queries) InsertJournal(ctx context.Context, arg InsertJournalParams) (Journal, error) {
	row := q.db.QueryRow(ctx, insertJournal,
		arg.JournalTypeID,
		arg.IdempotencyKey,
		arg.TotalDebit,
		arg.TotalCredit,
		arg.Metadata,
		arg.ActorID,
		arg.Source,
		arg.ReversalOf,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.JournalTypeID,
		&i.IdempotencyKey,
		&i.TotalDebit,
		&i.TotalCredit,
		&i.Metadata,
		&i.ActorID,
		&i.Source,
		&i.ReversalOf,
		&i.CreatedAt,
	)
	return i, err
}

const insertJournalEntry = `-- name: InsertJournalEntry :one
INSERT INTO journal_entries (journal_id, account_holder, currency_id, classification_id, entry_type, amount, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, journal_id, account_holder, currency_id, classification_id, entry_type, amount, created_at
`

type InsertJournalEntryParams struct {
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
}

func (q *Queries) InsertJournalEntry(ctx context.Context, arg InsertJournalEntryParams) (JournalEntry, error) {
	row := q.db.QueryRow(ctx, insertJournalEntry,
		arg.JournalID,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.EntryType,
		arg.Amount,
	)
	var i JournalEntry
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ClassificationID,
		&i.EntryType,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}

const listEntriesByAccount = `-- name: ListEntriesByAccount :many
SELECT id, journal_id, account_holder, currency_id, classification_id, entry_type, amount, created_at
FROM journal_entries
WHERE account_holder = $1 AND currency_id = $2
  AND id > $3::bigint
ORDER BY id ASC
LIMIT $4::int
`

type ListEntriesByAccountParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
	CursorID      int64 `json:"cursor_id"`
	PageLimit     int32 `json:"page_limit"`
}

func (q *Queries) ListEntriesByAccount(ctx context.Context, arg ListEntriesByAccountParams) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listEntriesByAccount,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.EntryType,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT id, journal_id, account_holder, currency_id, classification_id, entry_type, amount, created_at
FROM journal_entries
WHERE journal_id = $1
ORDER BY id
`

func (q *Queries) ListJournalEntries(ctx context.Context, journalID int64) ([]JournalEntry, error) {
	rows, err := q.db.Query(ctx, listJournalEntries, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEntry{}
	for rows.Next() {
		var i JournalEntry
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.EntryType,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumEntriesSinceCheckpoint = `-- name: SumEntriesSinceCheckpoint :many
SELECT
  classification_id,
  entry_type,
  COALESCE(SUM(amount), 0) as total
FROM journal_entries
WHERE account_holder = $1
  AND currency_id = $2
  AND id > $3::bigint
GROUP BY classification_id, entry_type
`

type SumEntriesSinceCheckpointParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
	SinceEntryID  int64 `json:"since_entry_id"`
}

type SumEntriesSinceCheckpointRow struct {
	ClassificationID int64       `json:"classification_id"`
	EntryType        string      `json:"entry_type"`
	Total            interface{} `json:"total"`
}

func (q *Queries) SumEntriesSinceCheckpoint(ctx context.Context, arg SumEntriesSinceCheckpointParams) ([]SumEntriesSinceCheckpointRow, error) {
	rows, err := q.db.Query(ctx, sumEntriesSinceCheckpoint, arg.AccountHolder, arg.CurrencyID, arg.SinceEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumEntriesSinceCheckpointRow{}
	for rows.Next() {
		var i SumEntriesSinceCheckpointRow
		if err := rows.Scan(&i.ClassificationID, &i.EntryType, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
