// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BalanceCheckpoint struct {
	AccountHolder    int64              `json:"account_holder"`
	CurrencyID       int64              `json:"currency_id"`
	ClassificationID int64              `json:"classification_id"`
	Balance          pgtype.Numeric     `json:"balance"`
	LastEntryID      int64              `json:"last_entry_id"`
	LastEntryAt      pgtype.Timestamptz `json:"last_entry_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
}

type BalanceSnapshot struct {
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	SnapshotDate     pgtype.Date    `json:"snapshot_date"`
	Balance          pgtype.Numeric `json:"balance"`
	CreatedAt        time.Time      `json:"created_at"`
}

type Classification struct {
	ID         int64     `json:"id"`
	Code       string    `json:"code"`
	Name       string    `json:"name"`
	NormalSide string    `json:"normal_side"`
	IsSystem   bool      `json:"is_system"`
	IsActive   bool      `json:"is_active"`
	CreatedAt  time.Time `json:"created_at"`
}

type Currency struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type Deposit struct {
	ID             int64              `json:"id"`
	AccountHolder  int64              `json:"account_holder"`
	CurrencyID     int64              `json:"currency_id"`
	ExpectedAmount pgtype.Numeric     `json:"expected_amount"`
	ActualAmount   pgtype.Numeric     `json:"actual_amount"`
	Status         string             `json:"status"`
	ChannelName    string             `json:"channel_name"`
	ChannelRef     pgtype.Text        `json:"channel_ref"`
	JournalID      pgtype.Int8        `json:"journal_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Metadata       []byte             `json:"metadata"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type EntryTemplate struct {
	ID            int64     `json:"id"`
	Code          string    `json:"code"`
	Name          string    `json:"name"`
	JournalTypeID int64     `json:"journal_type_id"`
	IsActive      bool      `json:"is_active"`
	CreatedAt     time.Time `json:"created_at"`
}

type EntryTemplateLine struct {
	ID               int64  `json:"id"`
	TemplateID       int64  `json:"template_id"`
	ClassificationID int64  `json:"classification_id"`
	EntryType        string `json:"entry_type"`
	HolderRole       string `json:"holder_role"`
	AmountKey        string `json:"amount_key"`
	SortOrder        int32  `json:"sort_order"`
}

type Journal struct {
	ID             int64          `json:"id"`
	JournalTypeID  int64          `json:"journal_type_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	TotalDebit     pgtype.Numeric `json:"total_debit"`
	TotalCredit    pgtype.Numeric `json:"total_credit"`
	Metadata       []byte         `json:"metadata"`
	ActorID        pgtype.Int8    `json:"actor_id"`
	Source         pgtype.Text    `json:"source"`
	ReversalOf     pgtype.Int8    `json:"reversal_of"`
	CreatedAt      time.Time      `json:"created_at"`
}

type JournalEntry struct {
	ID               pgtype.Int8    `json:"id"`
	JournalID        int64          `json:"journal_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	EntryType        string         `json:"entry_type"`
	Amount           pgtype.Numeric `json:"amount"`
	CreatedAt        time.Time      `json:"created_at"`
}

type JournalType struct {
	ID        int64     `json:"id"`
	Code      string    `json:"code"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type Reservation struct {
	ID             int64          `json:"id"`
	AccountHolder  int64          `json:"account_holder"`
	CurrencyID     int64          `json:"currency_id"`
	ReservedAmount pgtype.Numeric `json:"reserved_amount"`
	SettledAmount  pgtype.Numeric `json:"settled_amount"`
	Status         string         `json:"status"`
	JournalID      pgtype.Int8    `json:"journal_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	ExpiresAt      time.Time      `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type RollupQueue struct {
	ID               int64              `json:"id"`
	AccountHolder    int64              `json:"account_holder"`
	CurrencyID       int64              `json:"currency_id"`
	ClassificationID int64              `json:"classification_id"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	CreatedAt        time.Time          `json:"created_at"`
}

type SystemRollup struct {
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	TotalBalance     pgtype.Numeric `json:"total_balance"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Withdrawal struct {
	ID             int64              `json:"id"`
	AccountHolder  int64              `json:"account_holder"`
	CurrencyID     int64              `json:"currency_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	Status         string             `json:"status"`
	ChannelName    string             `json:"channel_name"`
	ChannelRef     pgtype.Text        `json:"channel_ref"`
	ReservationID  pgtype.Int8        `json:"reservation_id"`
	JournalID      pgtype.Int8        `json:"journal_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	Metadata       []byte             `json:"metadata"`
	ReviewRequired bool               `json:"review_required"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}
