// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOperation = `-- name: GetOperation :one
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM operations WHERE id = $1
`

func (q *Queries) GetOperation(ctx context.Context, id int64) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperation, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationByIdempotencyKey = `-- name: GetOperationByIdempotencyKey :one
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM operations WHERE idempotency_key = $1
`

func (q *Queries) GetOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationByIdempotencyKey, idempotencyKey)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationForUpdate = `-- name: GetOperationForUpdate :one
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM operations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOperationForUpdate(ctx context.Context, id int64) (Operation, error) {
	row := q.db.QueryRow(ctx, getOperationForUpdate, id)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOperation = `-- name: InsertOperation :one
INSERT INTO operations (
    classification_id, account_holder, currency_id, amount, status,
    channel_name, idempotency_key, metadata, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at
`

type InsertOperationParams struct {
	ClassificationID int64          `json:"classification_id"`
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	Amount           pgtype.Numeric `json:"amount"`
	Status           string         `json:"status"`
	ChannelName      string         `json:"channel_name"`
	IdempotencyKey   string         `json:"idempotency_key"`
	Metadata         []byte         `json:"metadata"`
	ExpiresAt        time.Time      `json:"expires_at"`
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) (Operation, error) {
	row := q.db.QueryRow(ctx, insertOperation,
		arg.ClassificationID,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.Amount,
		arg.Status,
		arg.ChannelName,
		arg.IdempotencyKey,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i Operation
	err := row.Scan(
		&i.ID,
		&i.ClassificationID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.Amount,
		&i.SettledAmount,
		&i.Status,
		&i.ChannelName,
		&i.ChannelRef,
		&i.ReservationID,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.Metadata,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredOperations = `-- name: ListExpiredOperations :many
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM operations
WHERE expires_at != 'epoch'
  AND expires_at < now()
  AND status NOT IN ('confirmed', 'failed', 'expired', 'settled', 'released')
LIMIT $1
`

func (q *Queries) ListExpiredOperations(ctx context.Context, limit int32) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listExpiredOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.Amount,
			&i.SettledAmount,
			&i.Status,
			&i.ChannelName,
			&i.ChannelRef,
			&i.ReservationID,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsByFilter = `-- name: ListOperationsByFilter :many
SELECT id, classification_id, account_holder, currency_id, amount, settled_amount, status, channel_name, channel_ref, reservation_id, journal_id, idempotency_key, metadata, expires_at, created_at, updated_at FROM operations
WHERE (account_holder = $1 OR $1 = 0)
  AND (classification_id = $2 OR $2 = 0)
  AND (status = $3 OR $3 = '')
  AND id > $4
ORDER BY id
LIMIT $5
`

type ListOperationsByFilterParams struct {
	AccountHolder    int64  `json:"account_holder"`
	ClassificationID int64  `json:"classification_id"`
	Status           string `json:"status"`
	ID               int64  `json:"id"`
	Limit            int32  `json:"limit"`
}

func (q *Queries) ListOperationsByFilter(ctx context.Context, arg ListOperationsByFilterParams) ([]Operation, error) {
	rows, err := q.db.Query(ctx, listOperationsByFilter,
		arg.AccountHolder,
		arg.ClassificationID,
		arg.Status,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Operation{}
	for rows.Next() {
		var i Operation
		if err := rows.Scan(
			&i.ID,
			&i.ClassificationID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.Amount,
			&i.SettledAmount,
			&i.Status,
			&i.ChannelName,
			&i.ChannelRef,
			&i.ReservationID,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.Metadata,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOperationTransition = `-- name: UpdateOperationTransition :exec
UPDATE operations
SET status = $2, channel_ref = $3, settled_amount = $4,
    journal_id = $5, metadata = $6, updated_at = now()
WHERE id = $1
`

type UpdateOperationTransitionParams struct {
	ID            int64          `json:"id"`
	Status        string         `json:"status"`
	ChannelRef    string         `json:"channel_ref"`
	SettledAmount pgtype.Numeric `json:"settled_amount"`
	JournalID     int64          `json:"journal_id"`
	Metadata      []byte         `json:"metadata"`
}

func (q *Queries) UpdateOperationTransition(ctx context.Context, arg UpdateOperationTransitionParams) error {
	_, err := q.db.Exec(ctx, updateOperationTransition,
		arg.ID,
		arg.Status,
		arg.ChannelRef,
		arg.SettledAmount,
		arg.JournalID,
		arg.Metadata,
	)
	return err
}
