// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: periods.sql

package sqlcgen

import (
	"context"
	"time"
)

const getActivePeriodClose = `-- name: GetActivePeriodClose :one
SELECT id, close_before, note, actor_id, created_at FROM period_closes
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The active close line is the most recently created row. Returns
// pgx.ErrNoRows when the period has never been closed.
func (q *Queries) GetActivePeriodClose(ctx context.Context) (PeriodClose, error) {
	row := q.db.QueryRow(ctx, getActivePeriodClose)
	var i PeriodClose
	err := row.Scan(
		&i.ID,
		&i.CloseBefore,
		&i.Note,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const insertPeriodClose = `-- name: InsertPeriodClose :one
INSERT INTO period_closes (close_before, note, actor_id)
VALUES ($1, $2, $3)
RETURNING id, close_before, note, actor_id, created_at
`

type InsertPeriodCloseParams struct {
	CloseBefore time.Time `json:"close_before"`
	Note        string    `json:"note"`
	ActorID     int64     `json:"actor_id"`
}

// Append-only: latest-row-wins semantics come from ordering by created_at in
// GetActivePeriodClose, not from any uniqueness constraint here.
func (q *Queries) InsertPeriodClose(ctx context.Context, arg InsertPeriodCloseParams) (PeriodClose, error) {
	row := q.db.QueryRow(ctx, insertPeriodClose, arg.CloseBefore, arg.Note, arg.ActorID)
	var i PeriodClose
	err := row.Scan(
		&i.ID,
		&i.CloseBefore,
		&i.Note,
		&i.ActorID,
		&i.CreatedAt,
	)
	return i, err
}

const listPeriodCloses = `-- name: ListPeriodCloses :many
SELECT id, close_before, note, actor_id, created_at FROM period_closes
ORDER BY created_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListPeriodCloses(ctx context.Context, limit int32) ([]PeriodClose, error) {
	rows, err := q.db.Query(ctx, listPeriodCloses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeriodClose{}
	for rows.Next() {
		var i PeriodClose
		if err := rows.Scan(
			&i.ID,
			&i.CloseBefore,
			&i.Note,
			&i.ActorID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
