// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReconcileScanCursor = `-- name: GetReconcileScanCursor :one
SELECT after_holder, after_currency, lap_dirty, lap_scanned
FROM reconcile_scan_cursors
WHERE check_name = $1::text
`

type GetReconcileScanCursorRow struct {
	AfterHolder   int64 `json:"after_holder"`
	AfterCurrency int64 `json:"after_currency"`
	LapDirty      bool  `json:"lap_dirty"`
	LapScanned    int64 `json:"lap_scanned"`
}

// Persisted resume cursor for check #2's fleet-wide scan (C4b). Zero rows
// (no cursor persisted yet, e.g. first run ever) is a normal state, not an
// error — the adapter maps it to the same (MinInt64, MinInt64, false, 0) start
// the in-memory cursor always used, NOT (0, 0): system holders are negative
// (core.SystemHolder), so a zero start would reintroduce the bug fixed in
// docs/bugs/2026-08-21-reconcile-coverage-blind-spots.md (B1). lap_dirty
// carries "did an earlier segment of this lap already find a violation" so
// the check that completes the lap can still report Passed=false. lap_scanned
// (M-1 fix, migration 010) carries the cumulative count of pairs verified by
// every run of the current lap so far, independent of the resumed cursor's
// own position.
func (q *Queries) GetReconcileScanCursor(ctx context.Context, checkName string) (GetReconcileScanCursorRow, error) {
	row := q.db.QueryRow(ctx, getReconcileScanCursor, checkName)
	var i GetReconcileScanCursorRow
	err := row.Scan(
		&i.AfterHolder,
		&i.AfterCurrency,
		&i.LapDirty,
		&i.LapScanned,
	)
	return i, err
}

const reconcileAccountingEquation = `-- name: ReconcileAccountingEquation :many
SELECT
  je.currency_id,
  je.classification_id,
  c.normal_side,
  COALESCE(SUM(CASE WHEN je.entry_type = 'debit'  THEN je.amount ELSE 0 END), 0)::numeric AS total_debit,
  COALESCE(SUM(CASE WHEN je.entry_type = 'credit' THEN je.amount ELSE 0 END), 0)::numeric AS total_credit
FROM journal_entries je
INNER JOIN classifications c ON c.id = je.classification_id
GROUP BY je.currency_id, je.classification_id, c.normal_side
ORDER BY je.currency_id, je.classification_id
`

type ReconcileAccountingEquationRow struct {
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	NormalSide       string         `json:"normal_side"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// Check #4: per-currency, per-classification balance sums with normal_side.
// Returns one row per (currency_id, classification_id) so the caller can
// compute the equation A = L + E per currency.
func (q *Queries) ReconcileAccountingEquation(ctx context.Context) ([]ReconcileAccountingEquationRow, error) {
	rows, err := q.db.Query(ctx, reconcileAccountingEquation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileAccountingEquationRow{}
	for rows.Next() {
		var i ReconcileAccountingEquationRow
		if err := rows.Scan(
			&i.CurrencyID,
			&i.ClassificationID,
			&i.NormalSide,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileCountCheckpointAccountPairs = `-- name: ReconcileCountCheckpointAccountPairs :one
SELECT COUNT(*)::bigint AS total
FROM (SELECT DISTINCT account_holder, currency_id FROM balance_checkpoints) pairs
`

// Check #2 (M-1 fix, migration 010): the total number of distinct
// (account_holder, currency_id) pairs currently present in
// balance_checkpoints -- the same population ReconcileListCheckpointAccountsPage
// paginates over. Used as the independent cross-check a resumed lap's
// cumulative lap_scanned must reach before "no more rows after this cursor"
// is trusted as full coverage.
func (q *Queries) ReconcileCountCheckpointAccountPairs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, reconcileCountCheckpointAccountPairs)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const reconcileDuplicateIdempotencyKeys = `-- name: ReconcileDuplicateIdempotencyKeys :many
SELECT
  idempotency_key,
  COUNT(*)::bigint AS occurrences,
  MIN(id)::bigint AS first_id,
  MAX(id)::bigint AS last_id
FROM journals
GROUP BY idempotency_key
HAVING COUNT(*) > 1
ORDER BY occurrences DESC
LIMIT 50
`

type ReconcileDuplicateIdempotencyKeysRow struct {
	IdempotencyKey string `json:"idempotency_key"`
	Occurrences    int64  `json:"occurrences"`
	FirstID        int64  `json:"first_id"`
	LastID         int64  `json:"last_id"`
}

// Check #9: defensive scan for journals with duplicate idempotency_key values.
// The UNIQUE index should prevent this, but we verify the invariant explicitly.
func (q *Queries) ReconcileDuplicateIdempotencyKeys(ctx context.Context) ([]ReconcileDuplicateIdempotencyKeysRow, error) {
	rows, err := q.db.Query(ctx, reconcileDuplicateIdempotencyKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileDuplicateIdempotencyKeysRow{}
	for rows.Next() {
		var i ReconcileDuplicateIdempotencyKeysRow
		if err := rows.Scan(
			&i.IdempotencyKey,
			&i.Occurrences,
			&i.FirstID,
			&i.LastID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileListCheckpointAccountsPage = `-- name: ReconcileListCheckpointAccountsPage :many
SELECT DISTINCT account_holder, currency_id
FROM balance_checkpoints
WHERE account_holder > $1::bigint
   OR (account_holder = $1::bigint AND currency_id > $2::bigint)
ORDER BY account_holder, currency_id
LIMIT $3::int
`

type ReconcileListCheckpointAccountsPageParams struct {
	AfterHolder   int64 `json:"after_holder"`
	AfterCurrency int64 `json:"after_currency"`
	PageLimit     int32 `json:"page_limit"`
}

type ReconcileListCheckpointAccountsPageRow struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

// Check #2: keyset-paginated list of distinct (account_holder, currency_id)
// pairs present in balance_checkpoints, used to drive a fleet-wide
// checkpoint-vs-entries verification (one ReconcileAccount call per pair).
// Ordered by (account_holder, currency_id) so pagination is stable and
// resumable from the last-seen pair. Pass (math.MinInt64, math.MinInt64) for
// the first page, NOT (0, 0): system holders are negative (core.SystemHolder),
// so a zero cursor makes this predicate skip the entire system side forever.
func (q *Queries) ReconcileListCheckpointAccountsPage(ctx context.Context, arg ReconcileListCheckpointAccountsPageParams) ([]ReconcileListCheckpointAccountsPageRow, error) {
	rows, err := q.db.Query(ctx, reconcileListCheckpointAccountsPage, arg.AfterHolder, arg.AfterCurrency, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileListCheckpointAccountsPageRow{}
	for rows.Next() {
		var i ReconcileListCheckpointAccountsPageRow
		if err := rows.Scan(&i.AccountHolder, &i.CurrencyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileNonNegativeBalances = `-- name: ReconcileNonNegativeBalances :many
SELECT
  je.account_holder,
  je.currency_id,
  je.classification_id,
  c.normal_side,
  COALESCE(SUM(CASE WHEN je.entry_type = 'debit'  THEN je.amount ELSE 0 END), 0)::numeric AS total_debit,
  COALESCE(SUM(CASE WHEN je.entry_type = 'credit' THEN je.amount ELSE 0 END), 0)::numeric AS total_credit
FROM journal_entries je
INNER JOIN classifications c ON c.id = je.classification_id
WHERE je.account_holder > 0
GROUP BY je.account_holder, je.currency_id, je.classification_id, c.normal_side
HAVING ledger_signed_delta(
  MIN(c.normal_side),
  COALESCE(SUM(CASE WHEN je.entry_type = 'debit' THEN je.amount ELSE 0 END), 0),
  COALESCE(SUM(CASE WHEN je.entry_type = 'credit' THEN je.amount ELSE 0 END), 0)
) < 0
ORDER BY je.account_holder, je.classification_id
LIMIT $1::int
`

type ReconcileNonNegativeBalancesRow struct {
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	NormalSide       string         `json:"normal_side"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// Check #6: every positive holder × classification with a negative computed balance.
// "Positive holder" = user account (holder > 0).
func (q *Queries) ReconcileNonNegativeBalances(ctx context.Context, pageLimit int32) ([]ReconcileNonNegativeBalancesRow, error) {
	rows, err := q.db.Query(ctx, reconcileNonNegativeBalances, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileNonNegativeBalancesRow{}
	for rows.Next() {
		var i ReconcileNonNegativeBalancesRow
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.NormalSide,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileOrphanEntriesCount = `-- name: ReconcileOrphanEntriesCount :one

SELECT COUNT(*)::bigint AS orphan_count
FROM journal_entries je
LEFT JOIN journals j ON je.journal_id = j.id
WHERE j.id IS NULL
`

// Reconciliation queries for the full reconciliation suite
// (service.FullReconciliationService).
// All queries are read-only (no mutations).
// Check #3: count entries whose journal_id does not match any journal row.
func (q *Queries) ReconcileOrphanEntriesCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, reconcileOrphanEntriesCount)
	var orphan_count int64
	err := row.Scan(&orphan_count)
	return orphan_count, err
}

const reconcileOrphanEntriesSample = `-- name: ReconcileOrphanEntriesSample :many
SELECT je.id::bigint AS entry_id, je.journal_id
FROM journal_entries je
LEFT JOIN journals j ON je.journal_id = j.id
WHERE j.id IS NULL
ORDER BY je.id
LIMIT 10
`

type ReconcileOrphanEntriesSampleRow struct {
	EntryID   int64 `json:"entry_id"`
	JournalID int64 `json:"journal_id"`
}

// Fetch a small sample of orphan entries for the Finding descriptions.
func (q *Queries) ReconcileOrphanEntriesSample(ctx context.Context) ([]ReconcileOrphanEntriesSampleRow, error) {
	rows, err := q.db.Query(ctx, reconcileOrphanEntriesSample)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileOrphanEntriesSampleRow{}
	for rows.Next() {
		var i ReconcileOrphanEntriesSampleRow
		if err := rows.Scan(&i.EntryID, &i.JournalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileOrphanReservations = `-- name: ReconcileOrphanReservations :many
SELECT
  r.id,
  r.uid,
  r.account_holder,
  r.currency_id,
  r.status,
  r.journal_id
FROM reservations r
WHERE r.journal_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM journals j WHERE j.id = r.journal_id)
ORDER BY r.id
LIMIT 100
`

type ReconcileOrphanReservationsRow struct {
	ID            int64       `json:"id"`
	Uid           pgtype.UUID `json:"uid"`
	AccountHolder int64       `json:"account_holder"`
	CurrencyID    int64       `json:"currency_id"`
	Status        string      `json:"status"`
	JournalID     pgtype.Int8 `json:"journal_id"`
}

// Check #7: reservations whose journal_id references a non-existent journal.
// Since migration 035 journal_id is a nullable FK (NULL = no journal), so
// this can only fire if the FK is ever dropped or disabled — kept as
// defense-in-depth.
func (q *Queries) ReconcileOrphanReservations(ctx context.Context) ([]ReconcileOrphanReservationsRow, error) {
	rows, err := q.db.Query(ctx, reconcileOrphanReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileOrphanReservationsRow{}
	for rows.Next() {
		var i ReconcileOrphanReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.Status,
			&i.JournalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileRoleLessLiabilities = `-- name: ReconcileRoleLessLiabilities :many
SELECT
  je.account_holder,
  je.currency_id,
  je.classification_id,
  c.normal_side,
  COALESCE(SUM(CASE WHEN je.entry_type = 'debit'  THEN je.amount ELSE 0 END), 0)::numeric AS total_debit,
  COALESCE(SUM(CASE WHEN je.entry_type = 'credit' THEN je.amount ELSE 0 END), 0)::numeric AS total_credit
FROM journal_entries je
INNER JOIN classifications c ON c.id = je.classification_id
WHERE je.account_holder > 0
  AND c.balance_role = ''
  AND NOT c.is_system
GROUP BY je.account_holder, je.currency_id, je.classification_id, c.normal_side
HAVING ledger_signed_delta(
  MIN(c.normal_side),
  COALESCE(SUM(CASE WHEN je.entry_type = 'debit' THEN je.amount ELSE 0 END), 0),
  COALESCE(SUM(CASE WHEN je.entry_type = 'credit' THEN je.amount ELSE 0 END), 0)
) != 0
ORDER BY je.account_holder, je.classification_id
LIMIT $1::int
`

type ReconcileRoleLessLiabilitiesRow struct {
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	NormalSide       string         `json:"normal_side"`
	TotalDebit       pgtype.Numeric `json:"total_debit"`
	TotalCredit      pgtype.Numeric `json:"total_credit"`
}

// M-4 fix (`.local/independent-review-2026-08-26.md`,
// docs/plans/2026-08-26-audit-remediation-contracts.md follow-on
// fix-backend-1 batch, board #43): GetTotalUserSideBalance (I-37) sums only
// user-side classifications tagged with a non-empty balance_role. That is
// correct GIVEN every real liability classification is actually tagged --
// nothing in ClassificationInput enforced that (closed separately by
// ClassificationInput.Validate, docs/INVARIANTS.md I-37 addendum).
//
// This query does NOT filter on normal_side: an earlier version of this fix
// filtered `c.normal_side = 'credit'`, reasoning "liability-shaped by
// construction". That reasoning does not hold in THIS library's own
// convention -- main_wallet, the canonical real liability, is DEBIT-normal
// (DR increases what the platform owes the holder). balance_role is the
// ONLY signal that distinguishes a real liability from a legitimate
// role-less memo/cost account (fee_expense and friends, also debit-normal)
// -- normal_side cannot do it. Filtering on normal_side therefore missed
// exactly the shape a consumer would produce by copying main_wallet without
// also copying its balance_role, which independent review confirmed
// end-to-end: SolvencyCheck.Liability stayed unchanged (understated) with
// such a classification carrying a real, nonzero balance.
//
// False positives on role-less memo accounts (fee_expense) are avoided by
// BalanceRoleMemo (migration 011), not by a normal_side filter:
// ClassificationInput.Validate requires every new non-system classification
// to declare EITHER a spendable role OR 'memo' explicitly, so "balance_role
// = ”" on a non-system classification means exactly one thing going
// forward -- nobody tagged it -- and is safe to treat uniformly as
// suspicious, regardless of normal_side.
func (q *Queries) ReconcileRoleLessLiabilities(ctx context.Context, pageLimit int32) ([]ReconcileRoleLessLiabilitiesRow, error) {
	rows, err := q.db.Query(ctx, reconcileRoleLessLiabilities, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileRoleLessLiabilitiesRow{}
	for rows.Next() {
		var i ReconcileRoleLessLiabilitiesRow
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.NormalSide,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileSettlementNetting = `-- name: ReconcileSettlementNetting :many
SELECT
  je.currency_id,
  COALESCE(SUM(CASE WHEN je.entry_type = 'debit'  THEN je.amount ELSE -je.amount END), 0)::numeric AS net_balance
FROM journal_entries je
INNER JOIN classifications c ON c.id = je.classification_id
WHERE c.code = $1::text
  AND je.created_at < now() - ($2::int * INTERVAL '1 minute')
GROUP BY je.currency_id
HAVING COALESCE(SUM(CASE WHEN je.entry_type = 'debit' THEN je.amount ELSE -je.amount END), 0) != 0
ORDER BY je.currency_id
`

type ReconcileSettlementNettingParams struct {
	ClassificationCode string `json:"classification_code"`
	WindowMinutes      int32  `json:"window_minutes"`
}

type ReconcileSettlementNettingRow struct {
	CurrencyID int64          `json:"currency_id"`
	NetBalance pgtype.Numeric `json:"net_balance"`
}

// Check #5: per-currency net balance of a named classification,
// excluding entries within the given window (in minutes) to tolerate in-flight transactions.
// Returns only rows where the net is non-zero (violations).
func (q *Queries) ReconcileSettlementNetting(ctx context.Context, arg ReconcileSettlementNettingParams) ([]ReconcileSettlementNettingRow, error) {
	rows, err := q.db.Query(ctx, reconcileSettlementNetting, arg.ClassificationCode, arg.WindowMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileSettlementNettingRow{}
	for rows.Next() {
		var i ReconcileSettlementNettingRow
		if err := rows.Scan(&i.CurrencyID, &i.NetBalance); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileStaleRollupItems = `-- name: ReconcileStaleRollupItems :many
SELECT
  q.id,
  q.account_holder,
  q.currency_id,
  q.classification_id,
  q.claimed_until,
  q.failed_attempts
FROM rollup_queue q
WHERE q.processed_at IS NULL
  AND q.claimed_until IS NOT NULL
  AND q.claimed_until < now() - ($1::int * INTERVAL '1 minute')
ORDER BY q.claimed_until
LIMIT 100
`

type ReconcileStaleRollupItemsRow struct {
	ID               int64              `json:"id"`
	AccountHolder    int64              `json:"account_holder"`
	CurrencyID       int64              `json:"currency_id"`
	ClassificationID int64              `json:"classification_id"`
	ClaimedUntil     pgtype.Timestamptz `json:"claimed_until"`
	FailedAttempts   int32              `json:"failed_attempts"`
}

// Check #10: rollup_queue items that are claimed but the claim has expired,
// older than @threshold_minutes minutes. These indicate stuck workers.
func (q *Queries) ReconcileStaleRollupItems(ctx context.Context, thresholdMinutes int32) ([]ReconcileStaleRollupItemsRow, error) {
	rows, err := q.db.Query(ctx, reconcileStaleRollupItems, thresholdMinutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileStaleRollupItemsRow{}
	for rows.Next() {
		var i ReconcileStaleRollupItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.ClaimedUntil,
			&i.FailedAttempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileUntaggedHolderKindJournalTypes = `-- name: ReconcileUntaggedHolderKindJournalTypes :many
SELECT DISTINCT jt.uid, jt.code, jt.name
FROM journal_types jt
JOIN journals j ON j.journal_type_id = jt.id
JOIN journal_entries je ON je.journal_id = j.id
JOIN classifications c ON c.id = je.classification_id
WHERE jt.holder_kind = ''
  AND je.account_holder > 0
  AND c.balance_role <> ''
ORDER BY jt.uid
LIMIT $1::int
`

type ReconcileUntaggedHolderKindJournalTypesRow struct {
	Uid  pgtype.UUID `json:"uid"`
	Code string      `json:"code"`
	Name string      `json:"name"`
}

// M-7 follow-up (Team Lead, 2026-08-27, board #49, docs/INVARIANTS.md I-44):
// a journal type visible in the holder-facing transaction view (the same
// population holder.sql's ListHolderTransactionRows draws from -- a
// journal entry posted for a user holder against a role-bearing
// classification) but not tagged with a core.HolderTxKind reads as the
// generic 'other' bucket on the wire. That fallback is safe (never a
// financial miscalculation, never a raw internal identifier) but
// INVISIBLE: nothing tells a deployer they forgot to tag a journal type
// until a user notices their transaction list shows "other" instead of a
// specific label. This check surfaces it as a Finding -- detection, not
// prevention; it does not change what `kind` resolves to on the wire, and
// fixing a Finding here is a JournalTypeStore.SetHolderKind call, not a
// migration.
func (q *Queries) ReconcileUntaggedHolderKindJournalTypes(ctx context.Context, pageLimit int32) ([]ReconcileUntaggedHolderKindJournalTypesRow, error) {
	rows, err := q.db.Query(ctx, reconcileUntaggedHolderKindJournalTypes, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReconcileUntaggedHolderKindJournalTypesRow{}
	for rows.Next() {
		var i ReconcileUntaggedHolderKindJournalTypesRow
		if err := rows.Scan(&i.Uid, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReconcileScanCursor = `-- name: UpsertReconcileScanCursor :exec
INSERT INTO reconcile_scan_cursors (check_name, after_holder, after_currency, lap_dirty, lap_scanned, updated_at)
VALUES ($1::text, $2::bigint, $3::bigint, $4::boolean, $5::bigint, now())
ON CONFLICT (check_name)
DO UPDATE SET after_holder = EXCLUDED.after_holder, after_currency = EXCLUDED.after_currency,
              lap_dirty = EXCLUDED.lap_dirty, lap_scanned = EXCLUDED.lap_scanned, updated_at = now()
`

type UpsertReconcileScanCursorParams struct {
	CheckName     string `json:"check_name"`
	AfterHolder   int64  `json:"after_holder"`
	AfterCurrency int64  `json:"after_currency"`
	LapDirty      bool   `json:"lap_dirty"`
	LapScanned    int64  `json:"lap_scanned"`
}

// Called at the end of every check #2 run: persists the resume point,
// lap_dirty flag and cumulative lap_scanned when the scan was capped or
// timed out (partial coverage), or resets all three to their start values
// ((MinInt64, MinInt64), false, 0) when a full lap completed, so the next
// run begins a fresh lap rather than replaying the same resume point (or a
// stale dirty flag/count) forever.
func (q *Queries) UpsertReconcileScanCursor(ctx context.Context, arg UpsertReconcileScanCursorParams) error {
	_, err := q.db.Exec(ctx, upsertReconcileScanCursor,
		arg.CheckName,
		arg.AfterHolder,
		arg.AfterCurrency,
		arg.LapDirty,
		arg.LapScanned,
	)
	return err
}
