// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveReservations = `-- name: CountActiveReservations :one
SELECT COUNT(*) FROM reservations WHERE status = 'active'
`

func (q *Queries) CountActiveReservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReservations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalizeReservationSettlement = `-- name: FinalizeReservationSettlement :exec
UPDATE reservations SET status = 'settled', updated_at = now() WHERE id = $1
`

// Moves a 'settling' reservation to 'settled' without touching settled_amount
// — the remaining (reserved_amount - settled_amount) is implicitly released,
// same as the one-shot Settle's unused-remainder semantics.
func (q *Queries) FinalizeReservationSettlement(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, finalizeReservationSettlement, id)
	return err
}

const getExpiredReservations = `-- name: GetExpiredReservations :many
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE status IN ('active', 'settling') AND expires_at < now()
ORDER BY expires_at ASC
LIMIT $1
`

// Includes 'settling' alongside 'active': a partially-settled reservation
// that expires must still be wound down (auto-finalized, keeping the settled
// portion and releasing the rest — see service.ExpirationService), not left
// dangling forever. NB: idx_reservations_expired is a partial index WHERE
// status = 'active', so this query no longer hits it for 'settling' rows;
// acceptable at current scale (see docs/plans/2026-07-02-financial-core-hardening-design.md §5b).
func (q *Queries) GetExpiredReservations(ctx context.Context, limit int32) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getExpiredReservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ReservedAmount,
			&i.SettledAmount,
			&i.Status,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservation = `-- name: GetReservation :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE idempotency_key = $1
`

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationByUID = `-- name: GetReservationByUID :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE uid = $1
`

func (q *Queries) GetReservationByUID(ctx context.Context, uid pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByUID, uid)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationForUpdate = `-- name: GetReservationForUpdate :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetReservationForUpdate(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdate, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationForUpdateByUID = `-- name: GetReservationForUpdateByUID :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE uid = $1 FOR UPDATE
`

func (q *Queries) GetReservationForUpdateByUID(ctx context.Context, uid pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdateByUID, uid)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationOperationReceiptByIdempotencyKey = `-- name: GetReservationOperationReceiptByIdempotencyKey :one
SELECT id, reservation_id, operation, idempotency_key, amount, created_at, auth_digest, auth_signature, auth_key_id
FROM reservation_operation_receipts
WHERE idempotency_key = $1
`

func (q *Queries) GetReservationOperationReceiptByIdempotencyKey(ctx context.Context, idempotencyKey string) (ReservationOperationReceipt, error) {
	row := q.db.QueryRow(ctx, getReservationOperationReceiptByIdempotencyKey, idempotencyKey)
	var i ReservationOperationReceipt
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.Amount,
		&i.CreatedAt,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
	)
	return i, err
}

const getReservationUIDByID = `-- name: GetReservationUIDByID :one
SELECT uid FROM reservations WHERE id = $1
`

func (q *Queries) GetReservationUIDByID(ctx context.Context, id int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getReservationUIDByID, id)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const getSettlementLegByIdempotencyKey = `-- name: GetSettlementLegByIdempotencyKey :one
SELECT id, reservation_id, idempotency_key, amount, created_at, auth_digest, auth_signature, auth_key_id
FROM reservation_settlement_legs
WHERE idempotency_key = $1
`

func (q *Queries) GetSettlementLegByIdempotencyKey(ctx context.Context, idempotencyKey string) (ReservationSettlementLeg, error) {
	row := q.db.QueryRow(ctx, getSettlementLegByIdempotencyKey, idempotencyKey)
	var i ReservationSettlementLeg
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.CreatedAt,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
	)
	return i, err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (account_holder, currency_id, reserved_amount, idempotency_key, expires_at, uid, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
RETURNING id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
`

type InsertReservationParams struct {
	AccountHolder  int64          `json:"account_holder"`
	CurrencyID     int64          `json:"currency_id"`
	ReservedAmount pgtype.Numeric `json:"reserved_amount"`
	IdempotencyKey string         `json:"idempotency_key"`
	ExpiresAt      time.Time      `json:"expires_at"`
	Uid            pgtype.UUID    `json:"uid"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ReservedAmount,
		arg.IdempotencyKey,
		arg.ExpiresAt,
		arg.Uid,
		arg.CreatedAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const insertReservationOperationReceipt = `-- name: InsertReservationOperationReceipt :one
INSERT INTO reservation_operation_receipts (reservation_id, operation, idempotency_key, amount, created_at, auth_digest, auth_signature, auth_key_id)
VALUES (
    $1, $2, $3, $4,
    COALESCE(NULLIF($5::timestamptz, 'epoch'::timestamptz), now()),
    $6, $7, $8
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, reservation_id, operation, idempotency_key, amount, created_at, auth_digest, auth_signature, auth_key_id
`

type InsertReservationOperationReceiptParams struct {
	ReservationID  int64          `json:"reservation_id"`
	Operation      string         `json:"operation"`
	IdempotencyKey string         `json:"idempotency_key"`
	Amount         pgtype.Numeric `json:"amount"`
	RecordedAt     time.Time      `json:"recorded_at"`
	AuthDigest     []byte         `json:"auth_digest"`
	AuthSignature  []byte         `json:"auth_signature"`
	AuthKeyID      string         `json:"auth_key_id"`
}

// Durable idempotency record for one Settle/Release/FinalizeSettlement
// application (I-3), mirroring InsertReservationSettlementLeg's pattern. On
// a replayed key this inserts nothing and returns no row; the caller then
// fetches the existing receipt and compares payloads.
//
// The auth_* columns and the passed-in created_at are exactly
// InsertReservationSettlementLeg's -- see that query's comment for why the
// timestamp cannot be left to the column default once it is signed.
func (q *Queries) InsertReservationOperationReceipt(ctx context.Context, arg InsertReservationOperationReceiptParams) (ReservationOperationReceipt, error) {
	row := q.db.QueryRow(ctx, insertReservationOperationReceipt,
		arg.ReservationID,
		arg.Operation,
		arg.IdempotencyKey,
		arg.Amount,
		arg.RecordedAt,
		arg.AuthDigest,
		arg.AuthSignature,
		arg.AuthKeyID,
	)
	var i ReservationOperationReceipt
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.Operation,
		&i.IdempotencyKey,
		&i.Amount,
		&i.CreatedAt,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
	)
	return i, err
}

const insertReservationSettlementLeg = `-- name: InsertReservationSettlementLeg :one
INSERT INTO reservation_settlement_legs (reservation_id, idempotency_key, amount, created_at, auth_digest, auth_signature, auth_key_id)
VALUES (
    $1, $2, $3,
    COALESCE(NULLIF($4::timestamptz, 'epoch'::timestamptz), now()),
    $5, $6, $7
)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, reservation_id, idempotency_key, amount, created_at, auth_digest, auth_signature, auth_key_id
`

type InsertReservationSettlementLegParams struct {
	ReservationID  int64          `json:"reservation_id"`
	IdempotencyKey string         `json:"idempotency_key"`
	Amount         pgtype.Numeric `json:"amount"`
	RecordedAt     time.Time      `json:"recorded_at"`
	AuthDigest     []byte         `json:"auth_digest"`
	AuthSignature  []byte         `json:"auth_signature"`
	AuthKeyID      string         `json:"auth_key_id"`
}

// Durable idempotency record for one SettlePartial application (I-3). On a
// replayed key this inserts nothing and returns no row; the caller then
// fetches the existing leg and compares payloads.
//
// auth_digest / auth_signature / auth_key_id carry the signature over this
// leg's canonical discharge digest (migration 028, docs/INVARIANTS.md I-65);
// all three are ” when no Attestor is configured or the caller is inside
// its own transaction, in which case a gated Reserve keeps holding the whole
// reservation (I-49's conservative rule).
//
// created_at is passed rather than defaulted because it is COVERED by that
// digest: a signature computed over one instant and a row storing a
// different one can never be re-verified. 'epoch' is the sentinel for "no
// signed instant, let the database assign it", which keeps the unsigned path
// byte-for-byte what it was before 028.
func (q *Queries) InsertReservationSettlementLeg(ctx context.Context, arg InsertReservationSettlementLegParams) (ReservationSettlementLeg, error) {
	row := q.db.QueryRow(ctx, insertReservationSettlementLeg,
		arg.ReservationID,
		arg.IdempotencyKey,
		arg.Amount,
		arg.RecordedAt,
		arg.AuthDigest,
		arg.AuthSignature,
		arg.AuthKeyID,
	)
	var i ReservationSettlementLeg
	err := row.Scan(
		&i.ID,
		&i.ReservationID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.CreatedAt,
		&i.AuthDigest,
		&i.AuthSignature,
		&i.AuthKeyID,
	)
	return i, err
}

const listReservationOperationReceiptsForReservations = `-- name: ListReservationOperationReceiptsForReservations :many
SELECT o.id, o.reservation_id, r.uid AS reservation_uid, o.operation, o.idempotency_key,
       o.amount, o.created_at, o.auth_digest, o.auth_signature, o.auth_key_id
FROM reservation_operation_receipts o
JOIN reservations r ON r.id = o.reservation_id
WHERE o.reservation_id = ANY($1::bigint[])
ORDER BY o.id
`

type ListReservationOperationReceiptsForReservationsRow struct {
	ID             int64          `json:"id"`
	ReservationID  int64          `json:"reservation_id"`
	ReservationUid pgtype.UUID    `json:"reservation_uid"`
	Operation      string         `json:"operation"`
	IdempotencyKey string         `json:"idempotency_key"`
	Amount         pgtype.Numeric `json:"amount"`
	CreatedAt      time.Time      `json:"created_at"`
	AuthDigest     []byte         `json:"auth_digest"`
	AuthSignature  []byte         `json:"auth_signature"`
	AuthKeyID      string         `json:"auth_key_id"`
}

// Every operation receipt belonging to the given reservations, with the
// signature material a verifier needs and the reservation uid the digest
// covers. Read by the gate OUTSIDE the transaction (an AuthVerifier may be a
// remote call and financial.md forbids that inside one), so the answer is
// authorized-but-not-current; the under-lock recompute is what makes that
// safe (see postgres.ReserverStore.reserveWithQueries and I-65).
func (q *Queries) ListReservationOperationReceiptsForReservations(ctx context.Context, reservationIds []int64) ([]ListReservationOperationReceiptsForReservationsRow, error) {
	rows, err := q.db.Query(ctx, listReservationOperationReceiptsForReservations, reservationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReservationOperationReceiptsForReservationsRow{}
	for rows.Next() {
		var i ListReservationOperationReceiptsForReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.ReservationUid,
			&i.Operation,
			&i.IdempotencyKey,
			&i.Amount,
			&i.CreatedAt,
			&i.AuthDigest,
			&i.AuthSignature,
			&i.AuthKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationSettlementLegsForReservations = `-- name: ListReservationSettlementLegsForReservations :many
SELECT l.id, l.reservation_id, r.uid AS reservation_uid, l.idempotency_key,
       l.amount, l.created_at, l.auth_digest, l.auth_signature, l.auth_key_id
FROM reservation_settlement_legs l
JOIN reservations r ON r.id = l.reservation_id
WHERE l.reservation_id = ANY($1::bigint[])
ORDER BY l.id
`

type ListReservationSettlementLegsForReservationsRow struct {
	ID             int64          `json:"id"`
	ReservationID  int64          `json:"reservation_id"`
	ReservationUid pgtype.UUID    `json:"reservation_uid"`
	IdempotencyKey string         `json:"idempotency_key"`
	Amount         pgtype.Numeric `json:"amount"`
	CreatedAt      time.Time      `json:"created_at"`
	AuthDigest     []byte         `json:"auth_digest"`
	AuthSignature  []byte         `json:"auth_signature"`
	AuthKeyID      string         `json:"auth_key_id"`
}

// The settlement-leg half of the same fetch. Legs have no `operation`
// column: the record kind IS the operation, and the caller labels these
// core.ReservationOpSettlePartial when it rebuilds the digest preimage (see
// that constant's doc comment for why the two record kinds must not share
// one).
func (q *Queries) ListReservationSettlementLegsForReservations(ctx context.Context, reservationIds []int64) ([]ListReservationSettlementLegsForReservationsRow, error) {
	rows, err := q.db.Query(ctx, listReservationSettlementLegsForReservations, reservationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReservationSettlementLegsForReservationsRow{}
	for rows.Next() {
		var i ListReservationSettlementLegsForReservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReservationID,
			&i.ReservationUid,
			&i.IdempotencyKey,
			&i.Amount,
			&i.CreatedAt,
			&i.AuthDigest,
			&i.AuthSignature,
			&i.AuthKeyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByAccount = `-- name: ListReservationsByAccount :many
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations
WHERE ($1::bigint = 0 OR account_holder = $1)
  AND ($2::text = '' OR status = $2)
  AND ($3::bigint = 0 OR id < $3)
ORDER BY id DESC
LIMIT $4::int
`

type ListReservationsByAccountParams struct {
	AccountHolder int64  `json:"account_holder"`
	FilterStatus  string `json:"filter_status"`
	BeforeID      int64  `json:"before_id"`
	PageLimit     int32  `json:"page_limit"`
}

// Keyset pagination on id DESC (api-contract §6): before_id = 0 means first
// page; the caller encodes the last row's id as the opaque next_cursor.
func (q *Queries) ListReservationsByAccount(ctx context.Context, arg ListReservationsByAccountParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByAccount,
		arg.AccountHolder,
		arg.FilterStatus,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ReservedAmount,
			&i.SettledAmount,
			&i.Status,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnexpiredReservationHolds = `-- name: ListUnexpiredReservationHolds :many
SELECT r.id, r.uid, r.reserved_amount
FROM reservations r
WHERE r.account_holder = $1
  AND r.currency_id = $2
  AND r.expires_at > now()
ORDER BY r.id
`

type ListUnexpiredReservationHoldsParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

type ListUnexpiredReservationHoldsRow struct {
	ID             int64          `json:"id"`
	Uid            pgtype.UUID    `json:"uid"`
	ReservedAmount pgtype.Numeric `json:"reserved_amount"`
}

// The per-reservation form of SumUnexpiredReservationHolds, for the gated
// path that can subtract a VERIFIED discharge (docs/INVARIANTS.md I-65).
//
// Same WHERE clause, same trust basis: only columns ledger_reservations_guard
// refuses to let anyone change (reserved_amount, expires_at, uid) are read.
// status and settled_amount are deliberately absent, exactly as in the SUM
// form -- the discharge is decided by signature, not by the state machine.
//
// Returned per row rather than summed because the caller subtracts a
// different, individually-verified discharge from each reservation and must
// floor each difference at zero independently; summing first would let one
// reservation's over-discharge (only reachable via a claim that fails
// verification, hence never credited) offset another's hold.
//
// uid is returned because it is what the discharge digest covers -- the
// verifier recomputes a uid-space preimage and never needs to know the
// BIGSERIAL id, which is only used to join the claims back to their
// reservation.
//
// now() (transaction start, the earliest reading in this transaction) for
// the same reason SumUnexpiredReservationHolds uses it: a row on the
// boundary is treated as still held.
func (q *Queries) ListUnexpiredReservationHolds(ctx context.Context, arg ListUnexpiredReservationHoldsParams) ([]ListUnexpiredReservationHoldsRow, error) {
	rows, err := q.db.Query(ctx, listUnexpiredReservationHolds, arg.AccountHolder, arg.CurrencyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnexpiredReservationHoldsRow{}
	for rows.Next() {
		var i ListUnexpiredReservationHoldsRow
		if err := rows.Scan(&i.ID, &i.Uid, &i.ReservedAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reservationExpiredNow = `-- name: ReservationExpiredNow :one
SELECT (expires_at <= clock_timestamp())::boolean AS expired
FROM reservations WHERE id = $1
`

// Whether this reservation is past its expires_at, evaluated by the database
// so an application clock that drifts from the database's cannot decide it.
//
// clock_timestamp(), not now(): now() is fixed at transaction start, and a
// long-running settlement transaction that began before the expiry would
// read as not-yet-expired. Taking the LATEST reading makes the settle path
// refuse as early as possible, which is the opposite corner from
// SumUnexpiredReservationHolds' now() -- each picks the reading that errs
// toward "the funds are still held" (I-49).
func (q *Queries) ReservationExpiredNow(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, reservationExpiredNow, id)
	var expired bool
	err := row.Scan(&expired)
	return expired, err
}

const settleReservationPartial = `-- name: SettleReservationPartial :exec
UPDATE reservations SET status = 'settling', settled_amount = settled_amount + $2, updated_at = now() WHERE id = $1
`

type SettleReservationPartialParams struct {
	ID            int64          `json:"id"`
	SettledAmount pgtype.Numeric `json:"settled_amount"`
}

// Accumulates settled_amount (unlike UpdateReservationSettle, which overwrites
// it) and moves status to 'settling' — a no-op status change if it's already
// there. Caller (ReserverStore.SettlePartial) has already row-locked this
// reservation via GetReservationForUpdate and verified the cumulative amount
// stays within reserved_amount; chk_settled_lte_reserved is the DB-level backstop.
func (q *Queries) SettleReservationPartial(ctx context.Context, arg SettleReservationPartialParams) error {
	_, err := q.db.Exec(ctx, settleReservationPartial, arg.ID, arg.SettledAmount)
	return err
}

const sumActiveReservations = `-- name: SumActiveReservations :one
SELECT COALESCE(SUM(
    CASE WHEN status = 'active' THEN reserved_amount
         ELSE reserved_amount - settled_amount
    END), 0) as total
FROM reservations
WHERE account_holder = $1 AND currency_id = $2 AND status IN ('active', 'settling')
`

type SumActiveReservationsParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

// Outstanding hold across the holder's not-yet-terminal reservations. An
// 'active' reservation holds its full reserved_amount; a 'settling' one
// (partially settled via SettlePartial) still holds the unsettled remainder
// (reserved - settled) — counting it as zero would let a concurrent Reserve
// over-commit the balance the moment the first partial settlement lands
// (the exact TOCTOU class I-4/I-11 exist to prevent). NB: the partial index
// idx_reservations_account_status covers only status='active'; the extra
// 'settling' rows are expected to be few at any moment.
func (q *Queries) SumActiveReservations(ctx context.Context, arg SumActiveReservationsParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumActiveReservations, arg.AccountHolder, arg.CurrencyID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const sumUnexpiredReservationHolds = `-- name: SumUnexpiredReservationHolds :one
SELECT COALESCE(SUM(r.reserved_amount), 0) as total
FROM reservations r
WHERE r.account_holder = $1
  AND r.currency_id = $2
  AND r.expires_at > now()
`

type SumUnexpiredReservationHoldsParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

// The hold Reserve subtracts when the caller opts into
// RequireVerifiedBalance AND no Attestor/AuthVerifier is configured (I-49).
// Deliberately the crudest possible sum: the full reserved_amount of every
// reservation on the dimension whose expires_at is still in the future, with
// no credit for anything that claims the reservation is over.
//
// With signing configured the gate uses ListUnexpiredReservationHolds
// instead and subtracts, per reservation, the discharge a VALIDLY SIGNED
// claim accounts for (I-65). A signature is the only other signal this
// comment's argument admits -- see "expires_at is the one exception" below,
// which says so -- so that path is the same reasoning carried one step
// further, not a relaxation of it.
//
// SumActiveReservations, its ordinary-path twin, reads reservations.status
// and reservations.settled_amount, and ledger_reservations_guard permits
// exactly the writes that zero a hold through those columns (active ->
// settling/settled/released, settled_amount growing) because those are the
// legitimate transitions. ledger_app holds UPDATE, so one permitted
// statement made a live 1000 hold report as zero and the gate authorized
// 2000 against a balance of 1000 (2026-09-02 audit,
// w3-review/money-path.md C-1).
//
// Sourcing the discharge from the append-only settlement record instead
// (reservation_settlement_legs / reservation_operation_receipts) does not
// fix it: ledger_app must keep INSERT on both -- the application writes them
// -- so a forged INSERT discharges a hold at the same one-statement cost
// (measured 2026-09-03). In this threat model the application's credential
// IS the attacker, so every discharge the application can perform the
// attacker can perform, and no trigger or ACL can tell them apart.
//
// expires_at is the one exception, and it is why this query has the shape it
// does: the guard refuses any UPDATE that changes it (verified: even a
// superuser statement is rejected), no INSERT can shorten another row's
// lifetime, and time passing is not a privilege. So "not expired yet" is the
// only claim about a reservation that a leaked credential cannot manufacture
// -- and it is therefore the only discharge signal this query accepts.
//
// Consequence, intended and documented (core.ReserveInput.
// RequireVerifiedBalance, docs/INVARIANTS.md I-49): on THIS path a settled
// or released reservation goes on holding its full reserved_amount under the
// gate until it expires. The settled portion is double-counted (it already left through
// its own journal, so E fell too) and a released one is counted at all. Both
// errors are conservative -- they refuse reservations, never allow them --
// and both self-heal at expires_at. Callers who need faster recycling set a
// shorter ExpiresIn.
//
// now() is the transaction timestamp, i.e. the EARLIEST reading available in
// this transaction, so a row on the boundary is treated as still held. The
// settle path uses clock_timestamp() for the mirror-image reason (see
// ReservationExpiredNow).
func (q *Queries) SumUnexpiredReservationHolds(ctx context.Context, arg SumUnexpiredReservationHoldsParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumUnexpiredReservationHolds, arg.AccountHolder, arg.CurrencyID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateReservationSettle = `-- name: UpdateReservationSettle :exec
UPDATE reservations SET status = 'settled', settled_amount = $2, journal_id = $3, updated_at = now() WHERE id = $1
`

type UpdateReservationSettleParams struct {
	ID            int64          `json:"id"`
	SettledAmount pgtype.Numeric `json:"settled_amount"`
	JournalID     pgtype.Int8    `json:"journal_id"`
}

func (q *Queries) UpdateReservationSettle(ctx context.Context, arg UpdateReservationSettleParams) error {
	_, err := q.db.Exec(ctx, updateReservationSettle, arg.ID, arg.SettledAmount, arg.JournalID)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE reservations SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status)
	return err
}
