// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservations.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveReservations = `-- name: CountActiveReservations :one
SELECT COUNT(*) FROM reservations WHERE status = 'active'
`

func (q *Queries) CountActiveReservations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveReservations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const finalizeReservationSettlement = `-- name: FinalizeReservationSettlement :exec
UPDATE reservations SET status = 'settled', updated_at = now() WHERE id = $1
`

// Moves a 'settling' reservation to 'settled' without touching settled_amount
// — the remaining (reserved_amount - settled_amount) is implicitly released,
// same as the one-shot Settle's unused-remainder semantics.
func (q *Queries) FinalizeReservationSettlement(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, finalizeReservationSettlement, id)
	return err
}

const getExpiredReservations = `-- name: GetExpiredReservations :many
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE status IN ('active', 'settling') AND expires_at < now()
ORDER BY expires_at ASC
LIMIT $1
`

// Includes 'settling' alongside 'active': a partially-settled reservation
// that expires must still be wound down (auto-finalized, keeping the settled
// portion and releasing the rest — see service.ExpirationService), not left
// dangling forever. NB: idx_reservations_expired is a partial index WHERE
// status = 'active', so this query no longer hits it for 'settling' rows;
// acceptable at current scale (see docs/plans/2026-07-02-financial-core-hardening-design.md §5b).
func (q *Queries) GetExpiredReservations(ctx context.Context, limit int32) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, getExpiredReservations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ReservedAmount,
			&i.SettledAmount,
			&i.Status,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReservation = `-- name: GetReservation :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE id = $1
`

func (q *Queries) GetReservation(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationByIdempotencyKey = `-- name: GetReservationByIdempotencyKey :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE idempotency_key = $1
`

func (q *Queries) GetReservationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByIdempotencyKey, idempotencyKey)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationByUID = `-- name: GetReservationByUID :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE uid = $1
`

func (q *Queries) GetReservationByUID(ctx context.Context, uid pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationByUID, uid)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationForUpdate = `-- name: GetReservationForUpdate :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetReservationForUpdate(ctx context.Context, id int64) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdate, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationForUpdateByUID = `-- name: GetReservationForUpdateByUID :one
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations WHERE uid = $1 FOR UPDATE
`

func (q *Queries) GetReservationForUpdateByUID(ctx context.Context, uid pgtype.UUID) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdateByUID, uid)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const getReservationUIDByID = `-- name: GetReservationUIDByID :one
SELECT uid FROM reservations WHERE id = $1
`

func (q *Queries) GetReservationUIDByID(ctx context.Context, id int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getReservationUIDByID, id)
	var uid pgtype.UUID
	err := row.Scan(&uid)
	return uid, err
}

const insertReservation = `-- name: InsertReservation :one
INSERT INTO reservations (account_holder, currency_id, reserved_amount, idempotency_key, expires_at, uid)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
`

type InsertReservationParams struct {
	AccountHolder  int64          `json:"account_holder"`
	CurrencyID     int64          `json:"currency_id"`
	ReservedAmount pgtype.Numeric `json:"reserved_amount"`
	IdempotencyKey string         `json:"idempotency_key"`
	ExpiresAt      time.Time      `json:"expires_at"`
	Uid            pgtype.UUID    `json:"uid"`
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, insertReservation,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ReservedAmount,
		arg.IdempotencyKey,
		arg.ExpiresAt,
		arg.Uid,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.AccountHolder,
		&i.CurrencyID,
		&i.ReservedAmount,
		&i.SettledAmount,
		&i.Status,
		&i.JournalID,
		&i.IdempotencyKey,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Uid,
	)
	return i, err
}

const listReservationsByAccount = `-- name: ListReservationsByAccount :many
SELECT id, account_holder, currency_id, reserved_amount, settled_amount, status, journal_id, idempotency_key, expires_at, created_at, updated_at, uid
FROM reservations
WHERE ($1::bigint = 0 OR account_holder = $1)
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3::int
`

type ListReservationsByAccountParams struct {
	AccountHolder int64  `json:"account_holder"`
	FilterStatus  string `json:"filter_status"`
	PageLimit     int32  `json:"page_limit"`
}

func (q *Queries) ListReservationsByAccount(ctx context.Context, arg ListReservationsByAccountParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByAccount, arg.AccountHolder, arg.FilterStatus, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ReservedAmount,
			&i.SettledAmount,
			&i.Status,
			&i.JournalID,
			&i.IdempotencyKey,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Uid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settleReservationPartial = `-- name: SettleReservationPartial :exec
UPDATE reservations SET status = 'settling', settled_amount = settled_amount + $2, updated_at = now() WHERE id = $1
`

type SettleReservationPartialParams struct {
	ID            int64          `json:"id"`
	SettledAmount pgtype.Numeric `json:"settled_amount"`
}

// Accumulates settled_amount (unlike UpdateReservationSettle, which overwrites
// it) and moves status to 'settling' — a no-op status change if it's already
// there. Caller (ReserverStore.SettlePartial) has already row-locked this
// reservation via GetReservationForUpdate and verified the cumulative amount
// stays within reserved_amount; chk_settled_lte_reserved is the DB-level backstop.
func (q *Queries) SettleReservationPartial(ctx context.Context, arg SettleReservationPartialParams) error {
	_, err := q.db.Exec(ctx, settleReservationPartial, arg.ID, arg.SettledAmount)
	return err
}

const sumActiveReservations = `-- name: SumActiveReservations :one
SELECT COALESCE(SUM(
    CASE WHEN status = 'active' THEN reserved_amount
         ELSE reserved_amount - settled_amount
    END), 0) as total
FROM reservations
WHERE account_holder = $1 AND currency_id = $2 AND status IN ('active', 'settling')
`

type SumActiveReservationsParams struct {
	AccountHolder int64 `json:"account_holder"`
	CurrencyID    int64 `json:"currency_id"`
}

// Outstanding hold across the holder's not-yet-terminal reservations. An
// 'active' reservation holds its full reserved_amount; a 'settling' one
// (partially settled via SettlePartial) still holds the unsettled remainder
// (reserved - settled) — counting it as zero would let a concurrent Reserve
// over-commit the balance the moment the first partial settlement lands
// (the exact TOCTOU class I-4/I-11 exist to prevent). NB: the partial index
// idx_reservations_account_status covers only status='active'; the extra
// 'settling' rows are expected to be few at any moment.
func (q *Queries) SumActiveReservations(ctx context.Context, arg SumActiveReservationsParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumActiveReservations, arg.AccountHolder, arg.CurrencyID)
	var total interface{}
	err := row.Scan(&total)
	return total, err
}

const updateReservationSettle = `-- name: UpdateReservationSettle :exec
UPDATE reservations SET status = 'settled', settled_amount = $2, journal_id = $3, updated_at = now() WHERE id = $1
`

type UpdateReservationSettleParams struct {
	ID            int64          `json:"id"`
	SettledAmount pgtype.Numeric `json:"settled_amount"`
	JournalID     int64          `json:"journal_id"`
}

func (q *Queries) UpdateReservationSettle(ctx context.Context, arg UpdateReservationSettleParams) error {
	_, err := q.db.Exec(ctx, updateReservationSettle, arg.ID, arg.SettledAmount, arg.JournalID)
	return err
}

const updateReservationStatus = `-- name: UpdateReservationStatus :exec
UPDATE reservations SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateReservationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateReservationStatus, arg.ID, arg.Status)
	return err
}
