// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: snapshots.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSnapshotBalances = `-- name: GetSnapshotBalances :many
SELECT account_holder, currency_id, classification_id, snapshot_date, balance, created_at
FROM balance_snapshots
WHERE account_holder = $1 AND currency_id = $2 AND snapshot_date = $3
`

type GetSnapshotBalancesParams struct {
	AccountHolder int64       `json:"account_holder"`
	CurrencyID    int64       `json:"currency_id"`
	SnapshotDate  pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) GetSnapshotBalances(ctx context.Context, arg GetSnapshotBalancesParams) ([]BalanceSnapshot, error) {
	rows, err := q.db.Query(ctx, getSnapshotBalances, arg.AccountHolder, arg.CurrencyID, arg.SnapshotDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceSnapshot{}
	for rows.Next() {
		var i BalanceSnapshot
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.SnapshotDate,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemRollups = `-- name: GetSystemRollups :many
SELECT currency_id, classification_id, total_balance, updated_at
FROM system_rollups ORDER BY currency_id, classification_id
`

func (q *Queries) GetSystemRollups(ctx context.Context) ([]SystemRollup, error) {
	rows, err := q.db.Query(ctx, getSystemRollups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemRollup{}
	for rows.Next() {
		var i SystemRollup
		if err := rows.Scan(
			&i.CurrencyID,
			&i.ClassificationID,
			&i.TotalBalance,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO balance_snapshots (account_holder, currency_id, classification_id, snapshot_date, balance)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_holder, currency_id, classification_id, snapshot_date) DO NOTHING
`

type InsertSnapshotParams struct {
	AccountHolder    int64          `json:"account_holder"`
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	SnapshotDate     pgtype.Date    `json:"snapshot_date"`
	Balance          pgtype.Numeric `json:"balance"`
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.ClassificationID,
		arg.SnapshotDate,
		arg.Balance,
	)
	return err
}

const listSnapshotsByDateRange = `-- name: ListSnapshotsByDateRange :many
SELECT account_holder, currency_id, classification_id, snapshot_date, balance, created_at
FROM balance_snapshots
WHERE account_holder = $1 AND currency_id = $2
  AND snapshot_date BETWEEN $3 AND $4
ORDER BY snapshot_date
`

type ListSnapshotsByDateRangeParams struct {
	AccountHolder int64       `json:"account_holder"`
	CurrencyID    int64       `json:"currency_id"`
	StartDate     pgtype.Date `json:"start_date"`
	EndDate       pgtype.Date `json:"end_date"`
}

func (q *Queries) ListSnapshotsByDateRange(ctx context.Context, arg ListSnapshotsByDateRangeParams) ([]BalanceSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByDateRange,
		arg.AccountHolder,
		arg.CurrencyID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BalanceSnapshot{}
	for rows.Next() {
		var i BalanceSnapshot
		if err := rows.Scan(
			&i.AccountHolder,
			&i.CurrencyID,
			&i.ClassificationID,
			&i.SnapshotDate,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemRollup = `-- name: UpsertSystemRollup :exec
INSERT INTO system_rollups (currency_id, classification_id, total_balance)
VALUES ($1, $2, $3)
ON CONFLICT (currency_id, classification_id)
DO UPDATE SET total_balance = $3, updated_at = now()
`

type UpsertSystemRollupParams struct {
	CurrencyID       int64          `json:"currency_id"`
	ClassificationID int64          `json:"classification_id"`
	TotalBalance     pgtype.Numeric `json:"total_balance"`
}

func (q *Queries) UpsertSystemRollup(ctx context.Context, arg UpsertSystemRollupParams) error {
	_, err := q.db.Exec(ctx, upsertSystemRollup, arg.CurrencyID, arg.ClassificationID, arg.TotalBalance)
	return err
}
