// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package sqlcgen

import (
	"context"
)

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO entry_templates (code, name, journal_type_id)
VALUES ($1, $2, $3)
RETURNING id, code, name, journal_type_id, is_active, created_at
`

type CreateTemplateParams struct {
	Code          string `json:"code"`
	Name          string `json:"name"`
	JournalTypeID int64  `json:"journal_type_id"`
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (EntryTemplate, error) {
	row := q.db.QueryRow(ctx, createTemplate, arg.Code, arg.Name, arg.JournalTypeID)
	var i EntryTemplate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.JournalTypeID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createTemplateLine = `-- name: CreateTemplateLine :one
INSERT INTO entry_template_lines (template_id, classification_id, entry_type, holder_role, amount_key, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, template_id, classification_id, entry_type, holder_role, amount_key, sort_order
`

type CreateTemplateLineParams struct {
	TemplateID       int64  `json:"template_id"`
	ClassificationID int64  `json:"classification_id"`
	EntryType        string `json:"entry_type"`
	HolderRole       string `json:"holder_role"`
	AmountKey        string `json:"amount_key"`
	SortOrder        int32  `json:"sort_order"`
}

func (q *Queries) CreateTemplateLine(ctx context.Context, arg CreateTemplateLineParams) (EntryTemplateLine, error) {
	row := q.db.QueryRow(ctx, createTemplateLine,
		arg.TemplateID,
		arg.ClassificationID,
		arg.EntryType,
		arg.HolderRole,
		arg.AmountKey,
		arg.SortOrder,
	)
	var i EntryTemplateLine
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.ClassificationID,
		&i.EntryType,
		&i.HolderRole,
		&i.AmountKey,
		&i.SortOrder,
	)
	return i, err
}

const deactivateTemplate = `-- name: DeactivateTemplate :exec
UPDATE entry_templates SET is_active = false WHERE id = $1
`

func (q *Queries) DeactivateTemplate(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deactivateTemplate, id)
	return err
}

const getTemplateByCode = `-- name: GetTemplateByCode :one
SELECT id, code, name, journal_type_id, is_active, created_at
FROM entry_templates
WHERE code = $1
`

func (q *Queries) GetTemplateByCode(ctx context.Context, code string) (EntryTemplate, error) {
	row := q.db.QueryRow(ctx, getTemplateByCode, code)
	var i EntryTemplate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.JournalTypeID,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getTemplateLines = `-- name: GetTemplateLines :many
SELECT id, template_id, classification_id, entry_type, holder_role, amount_key, sort_order
FROM entry_template_lines
WHERE template_id = $1
ORDER BY sort_order
`

func (q *Queries) GetTemplateLines(ctx context.Context, templateID int64) ([]EntryTemplateLine, error) {
	rows, err := q.db.Query(ctx, getTemplateLines, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryTemplateLine{}
	for rows.Next() {
		var i EntryTemplateLine
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.ClassificationID,
			&i.EntryType,
			&i.HolderRole,
			&i.AmountKey,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, code, name, journal_type_id, is_active, created_at
FROM entry_templates
WHERE ($1::boolean = false OR is_active = true)
ORDER BY code
`

func (q *Queries) ListTemplates(ctx context.Context, activeOnly bool) ([]EntryTemplate, error) {
	rows, err := q.db.Query(ctx, listTemplates, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryTemplate{}
	for rows.Next() {
		var i EntryTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.JournalTypeID,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
