// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhook_subscribers.sql

package sqlcgen

import (
	"context"
)

const deleteWebhookSubscriber = `-- name: DeleteWebhookSubscriber :exec
DELETE FROM webhook_subscribers WHERE id = $1
`

func (q *Queries) DeleteWebhookSubscriber(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWebhookSubscriber, id)
	return err
}

const getWebhookSubscriber = `-- name: GetWebhookSubscriber :one
SELECT id, name, url, secret, filter_class, filter_to_status, is_active, created_at FROM webhook_subscribers WHERE id = $1
`

func (q *Queries) GetWebhookSubscriber(ctx context.Context, id int64) (WebhookSubscriber, error) {
	row := q.db.QueryRow(ctx, getWebhookSubscriber, id)
	var i WebhookSubscriber
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.FilterClass,
		&i.FilterToStatus,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertWebhookSubscriber = `-- name: InsertWebhookSubscriber :one
INSERT INTO webhook_subscribers (name, url, secret, filter_class, filter_to_status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, secret, filter_class, filter_to_status, is_active, created_at
`

type InsertWebhookSubscriberParams struct {
	Name           string `json:"name"`
	Url            string `json:"url"`
	Secret         string `json:"secret"`
	FilterClass    string `json:"filter_class"`
	FilterToStatus string `json:"filter_to_status"`
}

func (q *Queries) InsertWebhookSubscriber(ctx context.Context, arg InsertWebhookSubscriberParams) (WebhookSubscriber, error) {
	row := q.db.QueryRow(ctx, insertWebhookSubscriber,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.FilterClass,
		arg.FilterToStatus,
	)
	var i WebhookSubscriber
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.FilterClass,
		&i.FilterToStatus,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveWebhookSubscribers = `-- name: ListActiveWebhookSubscribers :many
SELECT id, name, url, secret, filter_class, filter_to_status, is_active, created_at FROM webhook_subscribers WHERE is_active = true
`

func (q *Queries) ListActiveWebhookSubscribers(ctx context.Context) ([]WebhookSubscriber, error) {
	rows, err := q.db.Query(ctx, listActiveWebhookSubscribers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookSubscriber{}
	for rows.Next() {
		var i WebhookSubscriber
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.FilterClass,
			&i.FilterToStatus,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
