{{- if and (not .Values.existingSecret) .Values.databaseUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger.fullname" . }}-db
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
---
{{- end }}
{{- if .Values.apiKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger.fullname" . }}-config
  labels:
    {{- include "ledger.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_KEYS: {{ .Values.apiKeys | quote }}
{{- end }}
